force-app/main/default/objects/AFD_Validator_URL__mdt/AFD_Validator_URL__mdt.object-meta.xml
<CustomObject>
    <description>This metadata contains URL with keys used to authorize AFD endpoint</description>
    <label>AFD Validator URL</label>
    <pluralLabel>AFD Validator URL</pluralLabel>
</CustomObject>

force-app/main/default/objects/AFD_Validator_URL__mdt/fields/Endpoint_URL__c.field-meta.xml
<CustomField>
    <fullName>Endpoint_URL__c</fullName>
    <description>Endpoint URL to authorize AFD verification process</description>
    <inlineHelpText>Please enter a valid endpoint url with keys</inlineHelpText>
    <label>Endpoint URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Event_Clone_Setting__mdt/Event_Clone_Setting__mdt.object-meta.xml
<CustomObject>
    <description>This object is introduced to track the events and events related fields</description>
    <label>Event Clone Setting</label>
    <pluralLabel>Event Clone Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Event_Clone_Setting__mdt/fields/Fields__c.field-meta.xml
<CustomField>
    <fullName>Fields__c</fullName>
    <description>This is to track the fields details</description>
    <label>Fields</label>
    <metadataRelationshipControllingField>Event_Clone_Setting__mdt.Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Event_Clone_Settings</relationshipLabel>
    <relationshipName>Event_Clone_Settings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Event_Clone_Setting__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>This is to get the object detail</description>
    <label>Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Event_Clone_Settings</relationshipLabel>
    <relationshipName>Event_Clone_Settings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Event_Clone_Setting__mdt/fields/Values__c.field-meta.xml
<CustomField>
    <fullName>Values__c</fullName>
    <description>This is to track the values of each field related to the object</description>
    <label>Values</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_From_Email_Address__mdt/Event_From_Email_Address__mdt.object-meta.xml
<CustomObject>
    <label>Event From Email Address</label>
    <pluralLabel>Event From Email Address</pluralLabel>
</CustomObject>

force-app/main/default/objects/Event_From_Email_Address__mdt/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <description>Used to store the event type values</description>
    <label>Event Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applicant Experience Day</fullName>
                <default>true</default>
                <label>Applicant Experience Day</label>
            </value>
            <value>
                <fullName>Campus Visit</fullName>
            </value>
            <value>
                <fullName>Career Cafe</fullName>
            </value>
            <value>
                <fullName>Clearing Visit</fullName>
            </value>
            <value>
                <fullName>Collaboration Event</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Dinner</fullName>
            </value>
            <value>
                <fullName>Faculty Conference</fullName>
            </value>
            <value>
                <fullName>Major Community</fullName>
            </value>
            <value>
                <fullName>Networking</fullName>
            </value>
            <value>
                <fullName>Open Day</fullName>
            </value>
            <value>
                <fullName>PG Open Visit</fullName>
            </value>
            <value>
                <fullName>Reunion</fullName>
            </value>
            <value>
                <fullName>Stewardship</fullName>
            </value>
            <value>
                <fullName>Talk / Lecture</fullName>
            </value>
            <value>
                <fullName>Taster Day</fullName>
            </value>
            <value>
                <fullName>Teacher &amp; Advisor Event</fullName>
            </value>
            <value>
                <fullName>Training / Workshop</fullName>
            </value>
            <value>
                <fullName>Vice-Chancellor</fullName>
            </value>
            <value>
                <fullName>Workshop</fullName>
            </value>
            <value>
                <fullName>Virtual Helpdesk</fullName>
            </value>
            <value>
                <fullName>In Conversation With</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_From_Email_Address__mdt/fields/From_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>From_Email_Address__c</fullName>
    <description>Used to store the respective email address for the event type</description>
    <label>From Email Address</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Event_GDPR__mdt/Event_GDPR__mdt.object-meta.xml
<CustomObject>
    <description>To store the Event GDPR content based on the business area.</description>
    <label>Event GDPR</label>
    <pluralLabel>Events GDPR</pluralLabel>
</CustomObject>

force-app/main/default/objects/Event_GDPR__mdt/fields/Consent_Required_to_Register__c.field-meta.xml
<CustomField>
    <fullName>Consent_Required_to_Register__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set Consent is required or not for particular GDPR Statement Used.</description>
    <label>Consent Required to Register</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_GDPR__mdt/fields/Declaration_Text__c.field-meta.xml
<CustomField>
    <fullName>Declaration_Text__c</fullName>
    <label>Declaration Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Event_GDPR__mdt/fields/GDPR_Statement_Used__c.field-meta.xml
<CustomField>
    <fullName>GDPR_Statement_Used__c</fullName>
    <description>Business Area Picklist values.</description>
    <label>GDPR Statement Used</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_GDPR__mdt/fields/Statement_Text_above_dec__c.field-meta.xml
<CustomField>
    <fullName>Statement_Text_above_dec__c</fullName>
    <description>Statement Text according to picklist value.</description>
    <label>Statement Text (above dec)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Event_GDPR__mdt/fields/Statement_Text_below_dec__c.field-meta.xml
<CustomField>
    <fullName>Statement_Text_below_dec__c</fullName>
    <label>Statement Text (below dec)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Event_GDPR__mdt/fields/Statement_Title__c.field-meta.xml
<CustomField>
    <fullName>Statement_Title__c</fullName>
    <label>Statement Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Setting__mdt/Event_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Metadata for saving common configuration for UoP Events</description>
    <label>Event Setting</label>
    <pluralLabel>Event Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Event_Setting__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <description>Field to store metadata value</description>
    <inlineHelpText>Field to store metadata value</inlineHelpText>
    <label>Value</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Event_Type__mdt/Event_Type__mdt.object-meta.xml
<CustomObject>
    <label>Event Type</label>
    <pluralLabel>Event Types</pluralLabel>
</CustomObject>

force-app/main/default/objects/Event_Type__mdt/fields/Is_Complex_Event__c.field-meta.xml
<CustomField>
    <fullName>Is_Complex_Event__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Complex Event</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Legacy_Donation_Opportunity_Mapping__mdt/Legacy_Donation_Opportunity_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>This metadata used to map the mandatory values for legacy Donation Opportunities created from the Alumni Registration form.</description>
    <label>Legacy Donation Opportunity Mapping</label>
    <pluralLabel>Legacy Donation Opportunity Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Legacy_Donation_Opportunity_Mapping__mdt/fields/Opportunity_Amount__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Amount__c</fullName>
    <description>Field to hold default Opportunity Amount value to map Legacy Donation Opportunity Amount</description>
    <inlineHelpText>Please enter the Amount value needs to be mapped</inlineHelpText>
    <label>Opportunity Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Legacy_Donation_Opportunity_Mapping__mdt/fields/Opportunity_Close_Date__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Close_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Field to hold default Opportunity Close Date value to map Legacy Donation Opportunity Close Date</description>
    <inlineHelpText>Please choose the Close Date for the Legacy Donation Opportunity</inlineHelpText>
    <label>Opportunity Close Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Legacy_Donation_Opportunity_Mapping__mdt/fields/Opportunity_Currency__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Currency__c</fullName>
    <description>Field to hold default Opportunity currency value to map Legacy Donation Opportunity currency</description>
    <inlineHelpText>Please provide a valid Currency Iso Code</inlineHelpText>
    <label>Opportunity Currency</label>
    <length>3</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Legacy_Donation_Opportunity_Mapping__mdt/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <description>Field to hold default Opportunity Stage value to map Legacy Donation Opportunity Stage</description>
    <inlineHelpText>Please provide a valid Opportunity Stage value</inlineHelpText>
    <label>Opportunity Stage</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Site_Domain_URL__mdt/Site_Domain_URL__mdt.object-meta.xml
<CustomObject>
    <description>This Metadata is used to get site domain to populate PersonalSiteContactInfo URL field in Contact</description>
    <label>Site Domain URL</label>
    <pluralLabel>Site Domain URL</pluralLabel>
</CustomObject>

force-app/main/default/objects/Site_Domain_URL__mdt/fields/PersonalSiteContactInfoURL__c.field-meta.xml
<CustomField>
    <fullName>PersonalSiteContactInfoURL__c</fullName>
    <description>This field used to hold URL for PersonalSiteContactInfo Page</description>
    <inlineHelpText>Please enter a valid Site URL for PersonalSiteContactInfo page</inlineHelpText>
    <label>PersonalSiteContactInfoURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/ct_MetadataService.cls
/**
 * @File Name          : ct_MetadataService.cls
 * @Description        : Service class for Metadata Objects
 * @Author             : Creation Admin
 * @Last Modified By   : Umashankar Creation
 * @Last Modified On   : 12-23-2020
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    2/27/2020   Creation Admin     Initial Version
**/
global without sharing class ct_MetadataService {



  global static Map<String,  Event_Type__mdt> eventTypeMetaData {
    get {
      if(eventTypeMetaData == null) {
        eventTypeMetaData = new Map<String,  Event_Type__mdt>();
        // run a for loop for fetching the Site Domain URL and stores in  eventTypeMetaData Map
        for(Event_Type__mdt thisSiteSetting : [SELECT DeveloperName, is_Complex_Event__c                                                              
                                                                  FROM Event_Type__mdt]){
          eventTypeMetaData.put(thisSiteSetting.DeveloperName, thisSiteSetting);
        }
      }
      return eventTypeMetaData;
    }
    set;
  }

  /**
  * @description Get Site Domain URL metadata records
  * @return Map<String, Site_Domain_URL__mdt> 
  **/
  global static Map<String,  Site_Domain_URL__mdt> siteDomainMetaData {
    get {
      if(siteDomainMetaData == null) {
        siteDomainMetaData = new Map<String,  Site_Domain_URL__mdt>();
        // run a for loop for fetching the Site Domain URL and stores in  siteDomainMetaData Map
        for(Site_Domain_URL__mdt thisSiteSetting : [SELECT DeveloperName, PersonalSiteContactInfoURL__c                                                              
                                                                  FROM Site_Domain_URL__mdt]){
          siteDomainMetaData.put(thisSiteSetting.DeveloperName, thisSiteSetting);
        }
      }
      return siteDomainMetaData;
    }
    set;
  }

 /**
  * @description get AFD Endpoint URL MetaData
  * @return Map<String, AFD_Validator_URL__mdt> 
  **/
  global static Map<String,  AFD_Validator_URL__mdt> AFDEndpointURLMetadataSetting {
    get {
      if(AFDEndpointURLMetadataSetting == null) {
        AFDEndpointURLMetadataSetting = new Map<String,  AFD_Validator_URL__mdt>();
        // run a for loop for fetching the Webform default record user metadata records
        for(AFD_Validator_URL__mdt thisAFDMetadata : [SELECT DeveloperName, 
                                                        Endpoint_URL__c
                                                        FROM AFD_Validator_URL__mdt]){
          AFDEndpointURLMetadataSetting.put(thisAFDMetadata.DeveloperName, thisAFDMetadata);
        }
      }
      return AFDEndpointURLMetadataSetting;
    }
    set;
  }

  /**
  * @description Boolean variable indicate whether apex is executed in Sandbox or Production Org
  * @return Boolean 
  **/
  global static Boolean isRunningInASandbox {
    get {
        if (isRunningInASandbox == null) {
            isRunningInASandbox = [SELECT IsSandbox FROM Organization LIMIT 1].IsSandbox;
        }
        return isRunningInASandbox;
    }
    set;
  }

  /**
  * @description get EVent Settings Metadata
  * @return Map<String, Event_Setting__mdt> 
  **/
  global static Map<String,  Event_Setting__mdt> eventSettingsMetaData {
    get {
      if(eventSettingsMetaData == null) {
        eventSettingsMetaData = new Map<String,  Event_Setting__mdt>();
        // run a for loop for fetching the Webform default record user metadata records
        for(Event_Setting__mdt thisEventSetting : [SELECT DeveloperName, 
                                                    Value__c
                                                    FROM Event_Setting__mdt]){
          eventSettingsMetaData.put(thisEventSetting.DeveloperName, thisEventSetting);
        }
      }
      return eventSettingsMetaData;
    }
    set;
  }

  /**
  * @description get map of Personal Site Contact Info URL by Developer name
  * @param developerName 
  * @return String 
  **/
  global static String getSiteDomainMetaDataByDeveloperName(String developerName){
    if(!siteDomainMetaData.isEmpty()
    && siteDomainMetaData.containsKey(developerName)){
      return siteDomainMetaData.get(developerName).PersonalSiteContactInfoURL__c;
    }
    return null;
  }

  /**
  * @description get Event Setting By Developer Name
  * @param developerName 
  * @return Event_Setting__mdt 
  **/
  global static Event_Setting__mdt getEventSettingByDeveloperName(String developerName){
    if(!eventSettingsMetaData.isEmpty()
    && eventSettingsMetaData.containsKey(developerName)){
      return eventSettingsMetaData.get(developerName);
    }
    return null;
  }

    /**
  * @description get AFD Endpoint URL Based whether apex is executed in Sandbox or Production Org
  * @return AFD End Point URL based on Organisation Type
  **/
  global static String getAFDEndPointURL(){
    if(!AFDEndpointURLMetadataSetting.isEmpty()){
      if(isRunningInASandbox
       && AFDEndpointURLMetadataSetting.containsKey(ct_Constants.SANDBOX_AFD_ENDPOINT_URL)){
        return AFDEndpointURLMetadataSetting.get(ct_Constants.SANDBOX_AFD_ENDPOINT_URL).Endpoint_URL__c;
      }
      else if(AFDEndpointURLMetadataSetting.containsKey(ct_Constants.PRODUCTION_AFD_ENDPOINT_URL)){
        return AFDEndpointURLMetadataSetting.get(ct_Constants.PRODUCTION_AFD_ENDPOINT_URL).Endpoint_URL__c;
      }
    }
    return null;
  }

  /**
  * @description Get default mapping record from legacy donation opportunity mapping metadata
  * @author Creation Admin | 29/5/2020 
  * @return Legacy_Donation_Opportunity_Mapping__mdt 
  **/
  global static Legacy_Donation_Opportunity_Mapping__mdt getLegacyDonationOpportunityMapping(){
    Legacy_Donation_Opportunity_Mapping__mdt thislegacyDonationMapping = new Legacy_Donation_Opportunity_Mapping__mdt();

    for(Legacy_Donation_Opportunity_Mapping__mdt thisLegacyMDT : [SELECT Id, Opportunity_Close_Date__c, Opportunity_Currency__c,
                                                                          Opportunity_Stage__c, Opportunity_Amount__c
                                                                          FROM Legacy_Donation_Opportunity_Mapping__mdt
                                                                          LIMIT 1]){
      thislegacyDonationMapping = thisLegacyMDT;
    }

    return thislegacyDonationMapping;
  }
    
  /**
  * @description Event GDPR metadata records.
  * @return Map<String, Event_GDPR__mdt> 
  **/
  global static Map<String,  Event_GDPR__mdt> eventGDPRStatementMetadata {
    get {
      if(eventGDPRStatementMetadata == null) {
        eventGDPRStatementMetadata = new Map<String,  Event_GDPR__mdt>();
        //run a forloop for fetching the Advancement Setting Metadata records 
        for(Event_GDPR__mdt thisEventGDPR : [Select id, GDPR_Statement_Used__c, Declaration_Text__c,Statement_Text_above_dec__c,Statement_Text_below_dec__c, Statement_Title__c, Consent_Required_to_Register__c
                                                   from Event_GDPR__mdt]){
          eventGDPRStatementMetadata.put(thisEventGDPR.GDPR_Statement_Used__c, thisEventGDPR);
        }
      }
      return eventGDPRStatementMetadata;
    }
    set;
  }
  /**
  * @description Fetch Event Clone Setting metadata records to clone the Event.
  * @return Map<String,  Event_Clone_Setting__mdt> 
  **/
  global static Map<String, Map<String,  Event_Clone_Setting__mdt>> eventCloneSettingsMetadata {
    get {
      if(eventCloneSettingsMetadata == null) {
        eventCloneSettingsMetadata = new Map<String, Map<String,  Event_Clone_Setting__mdt>>();
        //run a forloop for fetching the Advancement Setting Metadata records 
        for(Event_Clone_Setting__mdt thisEventClone : [SELECT Id, MasterLabel, DeveloperName, Object__r.QualifiedApiName, Fields__r.QualifiedApiName, Fields__r.DataType, Values__c FROM Event_Clone_Setting__mdt]){
          if(!eventCloneSettingsMetadata.containskey(thisEventClone.Object__r.QualifiedApiName)){
            eventCloneSettingsMetadata.put(thisEventClone.Object__r.QualifiedApiName, new Map<String,  Event_Clone_Setting__mdt>());
          }
          eventCloneSettingsMetadata.get(thisEventClone.Object__r.QualifiedApiName).put(thisEventClone.Fields__r.QualifiedApiName, thisEventClone);
        }
      }
      return eventCloneSettingsMetadata;
    }
    set;
  }

  /**
  * @description get Event Clone Setting By Object API Name
  * @param objectAPIName 
  * @return Map<String,  Event_Clone_Setting__mdt> 
  **/
  global static Map<String,  Event_Clone_Setting__mdt> getEventCloneSettingByObjectName(String objectAPIName){
    if(!eventCloneSettingsMetadata.isEmpty()
    && eventCloneSettingsMetadata.containsKey(objectAPIName)){
      return eventCloneSettingsMetadata.get(objectAPIName);
    }
    return null;
  }
  /**
  * @description Fetch Event From Email Address metadata records.
  * @return Map<String,  String> 
  **/
  global static Map<String, String> eventFromAddressMap {
      get {
        if(eventFromAddressMap == null) {
          eventFromAddressMap = new Map<String, String>();
          //run a forloop for fetching the Metadata records 
          for(Event_From_Email_Address__mdt thisMetadata : [SELECT Id, MasterLabel, DeveloperName, Event_Type__c,From_Email_Address__c FROM Event_From_Email_Address__mdt]){
            if(String.isNotBlank(thisMetadata.From_Email_Address__c)){
              eventFromAddressMap.put(thisMetadata.Event_Type__c, thisMetadata.From_Email_Address__c);
            }
        }
      }
      return eventFromAddressMap;
    }
    set;
  }
   /**
  * @description Fetch OrgWideEmail Addresses
  * @return Map<String,  OrgWideEmailAddress> 
  **/	
  global static Map<String, OrgWideEmailAddress> getOrgwireAddress(){
    Map<String, OrgWideEmailAddress> orgwideAddressMap = new Map<String, OrgWideEmailAddress>();
    for(OrgWideEmailAddress thisEmailAddress : [SELECT Id, Address, DisplayName FROM OrgWideEmailAddress WHERE Address =: eventFromAddressMap.values()]){
      orgwideAddressMap.put(thisEmailAddress.Address, thisEmailAddress);
    }
    return orgwideAddressMap;
  }
}