force-app/main/default/objects/Campaign/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This associates a Campaign to an Event</description>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Order__c/Event_Order__c.object-meta.xml
<CustomObject>
    <label>Event Order</label>
    <nameField>
        <displayFormat>O - {00000000}</displayFormat>
        <label>Event Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Ticket_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Ticket_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/QR_Code_URL__c.field-meta.xml
<CustomField>
    <fullName>QR_Code_URL__c</fullName>
    <label>QR Code URL</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Event_Product__c/Event_Product__c.object-meta.xml
<CustomObject>
    <label>Event Product</label>
    <nameField>
        <label>Event Product	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Product__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <displayFormat>REG-{0000000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This allows an event registration to be associated to an Account</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Enquirer__c.field-meta.xml
<CustomField>
    <fullName>Enquirer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Enquirer that has registered for the Event</description>
    <label>Enquirer</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Event_Email__c.field-meta.xml
<CustomField>
    <fullName>Event_Email__c</fullName>
    <label>Event Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Event_Order__c.field-meta.xml
<CustomField>
    <fullName>Event_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Order</label>
    <referenceTo>Event_Order__c</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Event_Product__c.field-meta.xml
<CustomField>
    <fullName>Event_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Product</label>
    <referenceTo>Event_Product__c</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Event_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration_Status__c</fullName>
    <description>Event Registration Status</description>
    <inlineHelpText>Event Registration Status</inlineHelpText>
    <label>Event Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Attended / Checked In</fullName>
            </value>
            <value>
                <fullName>Attended / Checked Out</fullName>
            </value>
            <value>
                <fullName>Did Not Attend</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Primary_Subject_Area_Interest__c.field-meta.xml
<CustomField>
    <fullName>Primary_Subject_Area_Interest__c</fullName>
    <description>This field is used to store Primary Subject Area interest value form Session</description>
    <inlineHelpText>This field is automated through Web Registration process</inlineHelpText>
    <label>Primary Subject Area Interest</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/QR_Code_URL__c.field-meta.xml
<CustomField>
    <fullName>QR_Code_URL__c</fullName>
    <description>Field to store QR Code Data which is rendered as QR Code</description>
    <inlineHelpText>Field to store QR Code Data which is rendered as QR Code</inlineHelpText>
    <label>QR Code URL</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Registration_Type__c</fullName>
    <label>Registration Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Complementary - Speaker</fullName>
            </value>
            <value>
                <fullName>Complementary - Vendor</fullName>
            </value>
            <value>
                <fullName>Complementary - Prospect</fullName>
            </value>
            <value>
                <fullName>Complementary - Media</fullName>
            </value>
            <value>
                <fullName>Myself</fullName>
            </value>
            <value>
                <fullName>Someone Else</fullName>
            </value>
            <value>
                <fullName>Unknown Guest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Event_Email__c.field-meta.xml
<CustomField>
    <fullName>Event_Email__c</fullName>
    <description>This refers to the email address provided as part of an Event registration</description>
    <label>Event Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/ct_Event_RegistrationTriggerHandler.cls
/**
 * @description       : Trigger Handler class for Event Registration
 * @author            : Creation Admin
**/
global without sharing class ct_Event_RegistrationTriggerHandler {

  //Set to store Event Order Ids for which roll-up needs to be calculated 
  global static Set<Id> eventOrderIds                 = new Set<Id>();
  //Set to store Event Product Order Ids for which Quantity Allocated roll-up needs to be calculated 
  global static Set<Id> eventProductIds               = new Set<Id>();
  global static List<Event_Registration__c> eventReg  = new List<Event_Registration__c>();
  global static List<String> eventDetailsDataList     = new List<String>();
  global static Set<Id> eventIdsForRollUpcalculation  = new Set<Id>();
  global static Set<String> eventRegistrationIdsToSync    = new Set<String>();
  global static Set<Id> processEventOrderRollUp       = new Set<Id>();
  global static Set<Id> enquirerIds                   = new Set<Id>();
  global static Set<Id> contactIds                    = new Set<Id>();
  global static Set<Id> accountIds                    = new Set<Id>();
  global static Set<Id> eventIds                      = new Set<Id>();
  global static Set<String> eventRegistrationForCampaignMemberSync  = new Set<String>();
  global static Set<String> leadIdForCampaignMember             = new Set<String>();
  global static Set<String> contactIdForCampaignMember          = new Set<String>();
  global static Set<String> accountIdForCampaignMember          = new Set<String>();

  global static Map<Id, Contact> contactMap = new Map<Id, Contact>();
  global static Map<Id, Lead> enquirerMap   = new Map<Id, Lead>();
  global static Map<Id, Account> accountMap   = new Map<Id, Account>();

  global static Map<Id, Set<Id>> existingContactEventRegistrationMap = new  Map<Id, Set<Id>>();
  global static Map<Id, Set<Id>> existingLeadEventRegistrationMap    = new  Map<Id, Set<Id>>();
  global static Map<Id, Set<Id>> existingAccountEventRegistrationMap = new  Map<Id, Set<Id>>();

  /* SAREN 
  06/10/2025
  To control recursion for Event Registration Trigger*/
  //  private static Boolean isActive = true;

  //   global static void turnOff() {
  //       isActive = false;
  //   }

  //   global static void turnOn() {
  //       isActive = true;
  //   }

  //   global static Boolean isActive() {
  //       return isActive;
  //   }

  global static void turnOff() {
    ct_ProcessControl.turnOffRecursionFlag(ct_ProcessControl.registeredTrigger.ct_Event_RegistrationTriggerHandler_After_Insert);
    ct_ProcessControl.turnOffRecursionFlag(ct_ProcessControl.registeredTrigger.ct_Event_RegistrationTriggerHandler_After_Update);
  }

  /*******************************************************************************************************
  * @description Turns class on.
  * @return void
  ********************************************************************************************************/
  global static void turnOn() {
      ct_ProcessControl.resetRecursionFlag(ct_ProcessControl.registeredTrigger.ct_Event_RegistrationTriggerHandler_After_Insert);
      ct_ProcessControl.resetRecursionFlag(ct_ProcessControl.registeredTrigger.ct_Event_RegistrationTriggerHandler_After_Update);
  }




    global static void handleBeforeInsert(list<Event_Registration__c> newlist){
        

      if (!ct_ProcessControl.getRecursionFlag(ct_ProcessControl.registeredTrigger.ct_Event_RegistrationTriggerHandler_Before_Insert)){

        System.debug('>>>>>>>>>>>>>>>>>>>>>>>>>>>EVENT REGISTRATION BEFORE INSERT TRIGGER<<<<<<<<<<<<<<<<<<<<<<<<<<<');
        //Loop to get The required Ids 
        for(Event_Registration__c thisEventRegistration : newlist){
          if(thisEventRegistration.Event__c != null){
            eventIds.add(thisEventRegistration.Event__c);
          }
          
          /*if(thisEventRegistration.Contact__c != null){
            contactIds.add(thisEventRegistration.Contact__c);
          }*/
          if(thisEventRegistration.Enquirer__c != null){
            enquirerIds.add(thisEventRegistration.Enquirer__c);
          }
          if(thisEventRegistration.Account_Name__c != null){
            accountIds.add(thisEventRegistration.Account_Name__c);
          }
        }

        /*if(!contactIds.isEmpty()){
          contactMap = ct_Event_RegistrationTriggerHelper.getContactMap(contactIds);
        }*/

        if(!enquirerIds.isEmpty()){
          enquirerMap = ct_Event_RegistrationTriggerHelper.getEnquirerMap(enquirerIds);
        }
        
        if(!accountIds.isEmpty()){
          accountMap = ct_Event_RegistrationTriggerHelper.getAccountMap(accountIds);
        }

        if(!contactIds.isEmpty() || !enquirerIds.isEmpty() || !accountIds.isEmpty()){
          //Method to get exisiting Lead or Contact
          //Method to get exisiting Lead or Contact or Account(30/10/2025)
          ct_Event_RegistrationTriggerHelper.getExistingLeadContactRegistration(enquirerIds, contactIds, accountIds, eventIds, existingContactEventRegistrationMap, existingLeadEventRegistrationMap, existingAccountEventRegistrationMap);
        }

        for(Event_Registration__c thisEventRegistration : (list<Event_Registration__c>)newlist){
          // method to get validate duplicate event registration records(Last Modified: 30/10/2025 with Person Account)
          ct_Event_RegistrationTriggerHelper.validateDuplicateEventRegistartion(existingContactEventRegistrationMap, existingLeadEventRegistrationMap, existingAccountEventRegistrationMap, thisEventRegistration);


          /*if(thisEventRegistration.Contact__c != null
            && !contactMap.isEmpty()
            && contactMap.containsKey(thisEventRegistration.Contact__c)){
              ct_Event_RegistrationTriggerHelper.processRegistrationDataFromContact(contactMap.get(thisEventRegistration.Contact__c), thisEventRegistration);
          }*/
          if(thisEventRegistration.Enquirer__c != null
          && !enquirerMap.isEmpty()
          && enquirerMap.containsKey(thisEventRegistration.Enquirer__c)){
            ct_Event_RegistrationTriggerHelper.processRegistrationDataFromLead(enquirerMap.get(thisEventRegistration.Enquirer__c), thisEventRegistration);
          }
          if(thisEventRegistration.Account_Name__c != null
          && !accountMap.isEmpty()
          && accountMap.containsKey(thisEventRegistration.Account_Name__c)){
            ct_Event_RegistrationTriggerHelper.processRegistrationDataFromAccount(accountMap.get(thisEventRegistration.Account_Name__c), thisEventRegistration);
          }
        }
              
        ct_ProcessControl.setRecursionFlag(ct_ProcessControl.registeredTrigger.ct_Event_RegistrationTriggerHandler_Before_Insert, true);

      }
    }

    global static void handleAfterInsert(list<Event_Registration__c> newlist){

      if (!ct_ProcessControl.getRecursionFlag(ct_ProcessControl.registeredTrigger.ct_Event_RegistrationTriggerHandler_After_Insert)){
      
        System.debug('>>>>>>>>>>>>>>>>>>>>>>>>>>>EVENT REGISTRATION AFTER INSERT TRIGGER<<<<<<<<<<<<<<<<<<<<<<<<<<<');
        
        Set<Id> eventRegistrationIds = new Set<Id>();
        
        //Loop to get The required Ids 
        for(Event_Registration__c thisEventRegistration : newlist){
          if(thisEventRegistration.Registration_Type__c != ct_EventConstants.EVENT_REGISTRATION_TYPE_UNKNOWN_GUEST
            && ((thisEventRegistration.Enquirer__c == null && /*thisEventRegistration.Contact__c == null &&*/ thisEventRegistration.Account_Name__c == null))){
              Map<String,String> orderMap = new Map<String,String>();
              orderMap.put('recId', thisEventRegistration.Id);
              orderMap.put('firstName', thisEventRegistration.First_Name__c);
              orderMap.put('lastName', thisEventRegistration.Last_Name__c);
              orderMap.put('email', thisEventRegistration.Event_Email__c);
              String jsonStr = JSON.serialize(orderMap);
              eventDetailsDataList.add(jsonStr); 
          }

          //For Campaign Member Sync
          if(thisEventRegistration.Enquirer__c != null 
              /*|| thisEventRegistration.Contact__c != null*/
              || thisEventRegistration.Account_Name__c != null){
              eventRegistrationForCampaignMemberSync.add( String.valueOf(Id.valueOf(thisEventRegistration.Id)).substring(0, 15));
              if(thisEventRegistration.Enquirer__c != null){
                leadIdForCampaignMember.add(thisEventRegistration.Enquirer__c);
              }
              /*if(thisEventRegistration.Contact__c != null){
                contactIdForCampaignMember.add(thisEventRegistration.Contact__c);
              }*/
              if(thisEventRegistration.Account_Name__c != null){
                accountIdForCampaignMember.add(thisEventRegistration.Account_Name__c);
              }
            }

          if(thisEventRegistration.Event_Product__c != null){
            eventProductIds.add(thisEventRegistration.Event_Product__c);
          }
          if(thisEventRegistration.Event__c != null){
            eventIdsForRollUpcalculation.add(thisEventRegistration.Event__c);
          }
          if(thisEventRegistration.Event_Order__c != null
            && thisEventRegistration.QR_Code_URL__c != null){
            processEventOrderRollUp.add(thisEventRegistration.Event_Order__c);
          }
          
          eventRegistrationIds.add(thisEventRegistration.Id);
        }
        ct_ProcessControl.setRecursionFlag(ct_ProcessControl.registeredTrigger.ct_Event_RegistrationTriggerHandler_After_Insert, true);
        
        //queueable job to update the event status
        //System.enqueueJob(new updateEventRegistrationStatusQueueable(eventRegistrationIds));
            /*String hour = String.valueOf(Datetime.now().hour());
            String min = String.valueOf(Datetime.now().minute() + 2); 
            String ss = String.valueOf(Datetime.now().second());
            String nextFireTime = ss + ' ' + min + ' ' + hour + ' * * ?';
            scheduleRegisteredStatus s = new scheduleRegisteredStatus(eventRegistrationIds); 
            System.schedule('Job Started At ' + String.valueOf(Datetime.now()), nextFireTime, s);*/
            
        
        if(!eventDetailsDataList.isEmpty()){
          //Trigger the Web site submission platform event
          ct_Event_RegistrationTriggerHelper.triggerWebSiteSubmissionPlatformEvent(eventDetailsDataList);
        }
        
        handleAyncProcesses(eventProductIds,eventIdsForRollUpcalculation,processEventOrderRollUp,eventRegistrationForCampaignMemberSync); // saren
      }
    }

    global static void handleAfterUpdate(list<Event_Registration__c> newlist,  list<Event_Registration__c> oldlist){
    
      if(!ct_ProcessControl.getRecursionFlag(ct_ProcessControl.registeredTrigger.ct_Event_RegistrationTriggerHandler_After_Update)){

        System.debug('>>>>>>>>>>>>>>>>>>>>>>>>>>>EVENT REGISTRATION AFTER UPDATE TRIGGER<<<<<<<<<<<<<<<<<<<<<<<<<<<');
        Set<Id> leadIdConsentSync = new Set<Id>();
        Set<Id> contactIdConsentSync = new Set<Id>();
        Set<Id> accountIdConsentSync = new Set<Id>();

        Map<Id, Event_Registration__c> triggerOldMap = new Map<Id, Event_Registration__c>(oldlist);
        Map<Id, Event_Registration__c> triggerNewMap = new Map<Id, Event_Registration__c>(newlist);
      
        //Loop to get The required Ids 
        for(Event_Registration__c thisEventRegistration : newlist){
          if((thisEventRegistration.Registration_Type__c != ct_EventConstants.EVENT_REGISTRATION_TYPE_UNKNOWN_GUEST
          || thisEventRegistration.Registration_Type__c != triggerOldMap.get(thisEventRegistration.Id).Registration_Type__c)
            && (/*thisEventRegistration.Contact__c == null &&*/ thisEventRegistration.Enquirer__c == null && thisEventRegistration.Account_Name__c == null) 
            && (thisEventRegistration.First_Name__c != null && thisEventRegistration.Last_Name__c != null && thisEventRegistration.Event_Email__c != null)){
              Map<String,String> orderMap = new Map<String,String>();
              orderMap.put('recId', thisEventRegistration.Id);
              orderMap.put('firstName', thisEventRegistration.First_Name__c);
              orderMap.put('lastName', thisEventRegistration.Last_Name__c);
              orderMap.put('email', thisEventRegistration.Event_Email__c);
              
              String jsonStr = JSON.serialize(orderMap);
              eventDetailsDataList.add(jsonStr); 
            }
            
            if((thisEventRegistration.Enquirer__c != null && thisEventRegistration.Enquirer__c != triggerOldMap.get(thisEventRegistration.Id).Enquirer__c) 
              /*|| (thisEventRegistration.Contact__c != null && thisEventRegistration.Contact__c != triggerOldMap.get(thisEventRegistration.Id).Contact__c)*/
              || (thisEventRegistration.Account_Name__c != null && thisEventRegistration.Account_Name__c != triggerOldMap.get(thisEventRegistration.Id).Account_Name__c)){
                eventOrderIds.add(thisEventRegistration.Event_Order__c);
            }
            
            if((thisEventRegistration.Event_Product__c != triggerOldMap.get(thisEventRegistration.Id).Event_Product__c)
              ||
              (thisEventRegistration.Event_Registration_Status__c != triggerOldMap.get(thisEventRegistration.Id).Event_Registration_Status__c)){

              if(thisEventRegistration.Event_Product__c != null){
                eventProductIds.add(thisEventRegistration.Event_Product__c);
              }
              if(triggerOldMap.get(thisEventRegistration.Id).Event_Product__c != null){
                eventProductIds.add(triggerOldMap.get(thisEventRegistration.Id).Event_Product__c);
              }
            }

          //For Campaign Member Sync
          if((thisEventRegistration.Enquirer__c != null 
              && thisEventRegistration.Enquirer__c != triggerOldMap.get(thisEventRegistration.Id).Enquirer__c) 
              /*|| (thisEventRegistration.Contact__c != null 
                  && thisEventRegistration.Contact__c != triggerOldMap.get(thisEventRegistration.Id).Contact__c)*/
              || (thisEventRegistration.Account_Name__c != null
                  && thisEventRegistration.Account_Name__c != triggerOldMap.get(thisEventRegistration.Id).Account_Name__c)){
              
            eventRegistrationForCampaignMemberSync.add( String.valueOf(Id.valueOf(thisEventRegistration.Id)).substring(0, 15));

            if(thisEventRegistration.Enquirer__c != null){
              leadIdForCampaignMember.add(thisEventRegistration.Enquirer__c);
            }
            /*if(thisEventRegistration.Contact__c != null){
              contactIdForCampaignMember.add(thisEventRegistration.Contact__c);
            }*/
            if(thisEventRegistration.Account_Name__c != null){
              accountIdForCampaignMember.add(thisEventRegistration.Account_Name__c);
            }
          }

          if(thisEventRegistration.Event_Registration_Status__c != triggerOldMap.get(thisEventRegistration.Id).Event_Registration_Status__c
          || thisEventRegistration.Primary_Subject_Area_Interest__c != triggerOldMap.get(thisEventRegistration.Id).Primary_Subject_Area_Interest__c
          ){
            eventRegistrationIdsToSync.add( String.valueOf(Id.valueOf(thisEventRegistration.Id)).substring(0, 15));
            if(thisEventRegistration.Enquirer__c != null){
              leadIdConsentSync.add(thisEventRegistration.Enquirer__c);
            }
            /*if(thisEventRegistration.Contact__c != null){
              contactIdConsentSync.add(thisEventRegistration.Contact__c);
            }*/
            if(thisEventRegistration.Account_Name__c != null){
              accountIdConsentSync.add(thisEventRegistration.Account_Name__c);
            }
          }

          if(thisEventRegistration.Event_Order__c != null
            && thisEventRegistration.QR_Code_URL__c != null){
            processEventOrderRollUp.add(thisEventRegistration.Event_Order__c);
          }
        }

        for(Event_Registration__c thisEventRegistration : triggerNewMap.values()){
          if((thisEventRegistration.Event_Registration_Status__c != null 
            && thisEventRegistration.Event__c != null 
            && thisEventRegistration.Event_Registration_Status__c != triggerOldMap.get(thisEventRegistration.Id).Event_Registration_Status__c)
            || (thisEventRegistration.Event__c != triggerOldMap.get(thisEventRegistration.Id).Event__c)){
              //eventReg.add(thisEventRegistration);
              eventIdsForRollUpcalculation.add(thisEventRegistration.Event__c);
              if(thisEventRegistration.Event__c != triggerOldMap.get(thisEventRegistration.Id).Event__c){
                eventIdsForRollUpcalculation.add(triggerOldMap.get(thisEventRegistration.Id).Event__c);
              }
          }
        }


        ct_ProcessControl.setRecursionFlag(ct_ProcessControl.registeredTrigger.ct_Event_RegistrationTriggerHandler_After_Update, true);

        if(!eventDetailsDataList.isEmpty()){
          ct_Event_RegistrationTriggerHelper.triggerWebSiteSubmissionPlatformEvent(eventDetailsDataList);
        }

        if(!eventOrderIds.isEmpty()){
          ct_Event_RegistrationTriggerHelper.updateOrderWithLeadOrContact(eventOrderIds);
        }
        if(!eventRegistrationIdsToSync.isEmpty()){
          ct_Event_RegistrationTriggerHelper.syncCampaignMemberWithEventRegistration(eventRegistrationIdsToSync, leadIdConsentSync, /*contactIdConsentSync,*/ accountIdConsentSync);
        }
      
        handleAyncProcesses(eventProductIds,eventIdsForRollUpcalculation,processEventOrderRollUp,eventRegistrationForCampaignMemberSync); // saren
      } 
    }

    global static void handleAfterDelete(list<Event_Registration__c> oldlist){
      System.debug('>>>>>>>>>>>>>>>>>>>>>>>>>>>EVENT REGISTRATION AFTER DELETE TRIGGER<<<<<<<<<<<<<<<<<<<<<<<<<<<');

      //Loop to get The required Ids 
      for(Event_Registration__c thisEventRegistration : oldlist){
        if(thisEventRegistration.Event_Product__c != null){
          eventProductIds.add(thisEventRegistration.Event_Product__c);
        }

        if(thisEventRegistration.Event__c != null){
          eventIdsForRollUpcalculation.add(thisEventRegistration.Event__c);
        }
      }
    
      handleAyncProcesses(eventProductIds,eventIdsForRollUpcalculation,processEventOrderRollUp,eventRegistrationForCampaignMemberSync); // saren
    }


    global static void handleAyncProcesses(Set<Id> eventProductIds,Set<Id> eventIdsForRollUpcalculation,Set<Id> processEventOrderRollUp,Set<String> eventRegistrationForCampaignMemberSync){
    
      if(!eventProductIds.isEmpty() && !System.isFuture() && !System.isBatch()){
        //Used to update the Quantity allocated rollup
        ct_Event_RegistrationTriggerHelper.updateQuantityAllocated(eventProductIds);
      }
      if(!eventIdsForRollUpcalculation.isEmpty() && !System.isFuture() && !System.isBatch()){
        //
        ct_Event_RegistrationTriggerHelper.processEventRegistartionCountOnEvent(eventIdsForRollUpcalculation);
      }

      if(!processEventOrderRollUp.isEmpty() && !System.isFuture() && !System.isBatch()){
        ct_Event_RegistrationTriggerHelper.processEventRegistrationRollUp(processEventOrderRollUp);
      }
      
      if(!eventRegistrationForCampaignMemberSync.isEmpty()){
        ct_CampaignMemberEventReg_Sync_Queueable campaignMemberSyncQueueableJob = new ct_CampaignMemberEventReg_Sync_Queueable(eventRegistrationForCampaignMemberSync, contactIdForCampaignMember, leadIdForCampaignMember, accountIdForCampaignMember);
        ID jobID = System.enqueueJob(campaignMemberSyncQueueableJob);
      }
    }

}