force-app/main/default/objects/Campaign/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This associates a Campaign to an Event</description>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/Year_of_Entry__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Entry__c</fullName>
    <description>The Year of Entry the Campaign is targeted at</description>
    <label>Year of Entry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For Syncing Campaign Member / Event Registration</description>
    <inlineHelpText>For Syncing Campaign Member with Event Registration</inlineHelpText>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/CM_ER_Auto_Sync__c.field-meta.xml
<CustomField>
    <fullName>CM_ER_Auto_Sync__c</fullName>
    <description>Should Sync Campaign Member and Event Registration</description>
    <inlineHelpText>Should Sync Campaign Member and Event Registration</inlineHelpText>
    <label>CM / ER Auto Sync</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Description__c.field-meta.xml
<CustomField>
    <fullName>Event_Description__c</fullName>
    <inlineHelpText>255 characters are allowed on this field.</inlineHelpText>
    <label>Event Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_End_Date__c</fullName>
    <label>Event End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Group__c.field-meta.xml
<CustomField>
    <fullName>Event_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Group</label>
    <referenceTo>Event_Group__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Start_Date__c</fullName>
    <label>Event Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Status__c</fullName>
    <label>Event Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Pre-Event</fullName>
            </value>
            <value>
                <fullName>Check In / Management</fullName>
            </value>
            <value>
                <fullName>Post Event</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/GDPR_Statement_Used__c.field-meta.xml
<CustomField>
    <fullName>GDPR_Statement_Used__c</fullName>
    <inlineHelpText>Each university business area has its own consent message / statement. The below consent capture fields will be auto populated further to the values in the custom settings. To change values contact the Salesforce Administrator.</inlineHelpText>
    <label>Consent Statement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consent 1</fullName>
            </value>
            <value>
                <fullName>Consent 2</fullName>
            </value>
            <value>
                <fullName>Alumni &amp; Advancement</fullName>
                <isActive>false</isActive>
                <label>Alumni &amp; Advancement</label>
            </value>
            <value>
                <fullName>Marketing (RAO)</fullName>
                <isActive>false</isActive>
                <label>Marketing (RAO)</label>
            </value>
            <value>
                <fullName>Marketing (Student Recruitment)</fullName>
                <isActive>false</isActive>
                <label>Marketing (Student Recruitment)</label>
            </value>
            <value>
                <fullName>R&amp;I / B2B</fullName>
                <isActive>false</isActive>
                <label>R&amp;I / B2B</label>
            </value>
            <value>
                <fullName>Student Recruitment &amp; RAO</fullName>
                <isActive>false</isActive>
                <label>Student Recruitment &amp; RAO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Request_Move_to_Post_Event__c.field-meta.xml
<CustomField>
    <fullName>Request_Move_to_Post_Event__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox based on which the record will be submitted for Approval for moving the Event status to Post Event</description>
    <inlineHelpText>Request approval from Event Manager to change status to Post Event. On status change Event Registrations will automatically update as follows; ‘Attended / Checked In’ will update to ‘Attended / Checked Out’ AND ‘Registered’ will update to ‘Did Not Attend</inlineHelpText>
    <label>Request Move to Post Event</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Success_Message__c.field-meta.xml
<CustomField>
    <fullName>Success_Message__c</fullName>
    <description>Success message shown in event booking confirmation</description>
    <inlineHelpText>Event Booking confirmation Message</inlineHelpText>
    <label>Success Message</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Year_of_Entry__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Entry__c</fullName>
    <description>This is the Year of Entry that this Event is aimed at.</description>
    <label>Year of Entry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Group__c/Event_Group__c.object-meta.xml
<CustomObject>
    <label>Event Group</label>
    <nameField>
        <label>Event Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Group__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This Field is used to determine whether this Event Group is Active or not</description>
    <inlineHelpText>Check this field is this Event Group needs to be active</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Year.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2019</fullName>
    </customValue>
    <customValue>
        <fullName>2020</fullName>
    </customValue>
    <customValue>
        <fullName>2021</fullName>
    </customValue>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2017</fullName>
        <isActive>false</isActive>
        <label>2017</label>
    </customValue>
    <customValue>
        <fullName>2016</fullName>
        <isActive>false</isActive>
        <label>2016</label>
    </customValue>
    <customValue>
        <fullName>2018</fullName>
        <isActive>false</isActive>
        <label>2018</label>
    </customValue>
    <description>Year of study</description>
    <masterLabel>Year</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ct_EventTriggerHandler.cls
/**
 * @File Name          : ct_EventTriggerHandler.cls
 * @Description        : Trigger Handler class for Event Trigger
**/
//global class ct_EventTriggerHandler {
   
  //global static final Id EVENT_RECORDTYPE_FACULTY_RECRUITMENT_OUTREACH_EVENTS = CT_Util.getRecordTypeIdByDevName('Event__c', 'Faculty_Recruitment_and_Outreach_Event');

  /**
    * createCampaignFromEvent - Method to create Campaign records for events
    * @param eventNewMap  Event Trigger New Map 
  **/
  // global static void createCampaignFromEvent(Map<Id, Event__c> eventNewMap) {
  //   List<Campaign> campaignListToInsert = new List<Campaign>();
  //   for(Event__c thisEvent : eventNewMap.values()){
  //     if(thisEvent.RecordTypeId == EVENT_RECORDTYPE_FACULTY_RECRUITMENT_OUTREACH_EVENTS){
  //       campaignListToInsert.add(createCampaignObject(thisEvent));
  //     }
  //   }
  //   if(!campaignListToInsert.isEmpty()){
  //     insert campaignListToInsert;
  //   }
  // }

  /**
    * createCampaignObject - Method to create Campaign from an event
    * @param thisEvent  - Event record for which Campaign to be created
  **/
  // global static Campaign createCampaignObject(Event__c thisEvent) {
  //   Campaign thisCampaign               = new Campaign();
  //   thisCampaign.IsActive               = true;
  //   thisCampaign.Name                   = thisEvent.Name;
  //   //Populate RAO Team Email address for sending Notification configured in Custom Label values
  //   thisCampaign.Rao_team_email__c      = 'saravanan@creation.technology';
  //   thisCampaign.Description            = thisEvent.Event_Description__c;
  //   thisCampaign.EndDate                = thisEvent.Event_End_Date__c;
  //   thisCampaign.Event__c               = thisEvent.Id;
  //   thisCampaign.StartDate              = thisEvent.Event_Start_Date__c;
  //   thisCampaign.Year_of_Entry__c       = thisEvent.Year_of_Entry__c;
  //   return thisCampaign;
  // }
//}

/*global without sharing class ct_EventTriggerHandler_TDTM {

	global override hed.TDTM_Runnable.DmlWrapper run(List<SObject> newlist, List<SObject> oldlist,
		hed.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult) {

		System.debug('>>>>>>>>>>>>>>>>>>>>>>>>>>>CT EVENT TDTM TRIGGER<<<<<<<<<<<<<<<<<<<<<<<<<<<');

		hed.TDTM_Runnable.dmlWrapper dmlWrapper = new hed.TDTM_Runnable.DmlWrapper();
            Set<Id> postEventApprovedIds          = new Set<Id>();
            List<Event__c> lstEvent               = new List<Event__c>();
            Set<Id> setOfEvtGrpIds                = new Set<Id>();
            //Campaign Ids for populating Event look up
            Map<Id, Id> campaignIdToEventIdMap    = new Map<Id, Id>();
            Set<Id> eventIdsForCampaignMemberSync = new Set<Id>();
            // Before Insert Logic
            if (triggerAction == hed.TDTM_Runnable.Action.BeforeInsert){
                System.debug('>>>>>>>>>>>>>>>>>>>>>>>>>>>EVENT BEFORE INSERT TRIGGER<<<<<<<<<<<<<<<<<<<<<<<<<<<');
                for(Event__c evt : (list<Event__c>)newlist){
                    if(evt.GDPR_Statement_Used__c != null){
                        //Method to update GDPR statement text on Event.
                        ct_EventTriggerHelper.updateGDPRStatements(evt);
                    }
                    if(evt.Success_Message__c == null){
                        ct_EventTriggerHelper.updateSuccessMessage(evt);
                    }
                }

            }
            //After Insert Logic
            if (triggerAction == hed.TDTM_Runnable.Action.AfterInsert){
                System.debug('>>>>>>>>>>>>>>>>>>>>>>>>>>>EVENT AFTER INSERT TRIGGER<<<<<<<<<<<<<<<<<<<<<<<<<<<');
                //Loop to get The required Ids 
                for(Event__c thisEvent : (list<Event__c>)newlist){
                  if(thisEvent.Campaign__c != null){
                    //Collect Campaign Ids for populating Event Look up in Campaign records
                        campaignIdToEventIdMap.put(thisEvent.Campaign__c, thisEvent.Id);
                    }
                }
            }
            // Before Update Logic
            if (triggerAction == hed.TDTM_Runnable.Action.BeforeUpdate){
                System.debug('>>>>>>>>>>>>>>>>>>>>>>>>>>>EVENT BEFORE UPDATE TRIGGER<<<<<<<<<<<<<<<<<<<<<<<<<<<');
                Map<Id, Event__c> triggerOldMap = new Map<Id, Event__c>((list<Event__c>)oldlist);
                Map<Id, Event__c> triggerNewMap = new Map<Id, Event__c>((list<Event__c>)newlist);
                System.debug('Calling before update -- Anshul');
                for(Event__c evt : triggerNewMap.values()){
                    System.debug('Anshul - in Loop');
                    if(evt.GDPR_Statement_Used__c != null && evt.GDPR_Statement_Used__c != triggerOldMap.get(evt.Id).GDPR_Statement_Used__c){
                        System.debug('Anshul - in GDPR Used');
                        //Method to update GDPR statement text on Event.
                        ct_EventTriggerHelper.updateGDPRStatements(evt);
                    }
                    if(evt.Success_Message__c == null){
                        ct_EventTriggerHelper.updateSuccessMessage(evt);
                    }
                    ct_EventTriggerHelper.checkEvtProdAvailable(evt, triggerOldMap.get(evt.Id));
                        
                }
            } 
            // After Update Logic
		    if (triggerAction == hed.TDTM_Runnable.Action.AfterUpdate){
                System.debug('>>>>>>>>>>>>>>>>>>>>>>>>>>>EVENT AFTER UPDATE TRIGGER<<<<<<<<<<<<<<<<<<<<<<<<<<<');

                Map<Id, Event__c> triggerOldMap = new Map<Id, Event__c>((list<Event__c>)oldlist);
                Map<Id, Event__c> triggerNewMap = new Map<Id, Event__c>((list<Event__c>)newlist);

                for(Event__c thisEvent : triggerNewMap.values()){
                    if(thisEvent.Request_Move_to_Post_Event__c 
                    && thisEvent.Event_Status__c != triggerOldMap.get(thisEvent.Id).Event_Status__c
                    && thisEvent.Event_Status__c == ct_EventConstants.EVENT_STATUS_POST_EVENT){
                        postEventApprovedIds.add(thisEvent.Id);
                    }
                                    
                    if(thisEvent.Active__c != triggerOldMap.get(thisEvent.Id).Active__c 
                        || thisEvent.Event_Group__c != triggerOldMap.get(thisEvent.Id).Event_Group__c){
                        if(thisEvent.Event_Group__c != null){
                            setOfEvtGrpIds.add(thisEvent.Event_Group__c);
                        }
                        if(thisEvent.Event_Group__c != triggerOldMap.get(thisEvent.Id).Event_Group__c
                            && triggerOldMap.get(thisEvent.Id).Event_Group__c != null){
                            setOfEvtGrpIds.add(triggerOldMap.get(thisEvent.Id).Event_Group__c);
                        }
                    }
                    
                    if(thisEvent.Campaign__c != null
                        && thisEvent.Campaign__c != triggerOldMap.get(thisEvent.Id).Campaign__c){
                        campaignIdToEventIdMap.put(thisEvent.Campaign__c, thisEvent.Id);

                        if(triggerOldMap.get(thisEvent.Id).Campaign__c != null){
                            campaignIdToEventIdMap.put(triggerOldMap.get(thisEvent.Id).Campaign__c, null);
                        }
                    }

                    if(thisEvent.CM_ER_Auto_Sync__c != null
                        && thisEvent.CM_ER_Auto_Sync__c != triggerOldMap.get(thisEvent.Id).CM_ER_Auto_Sync__c
                        && thisEvent.CM_ER_Auto_Sync__c == ct_EventConstants.EVENT_CM_ER_AUTO_SYNC_YES){
                            eventIdsForCampaignMemberSync.add(thisEvent.Id);
                    }
			    }
            
			if(!postEventApprovedIds.isEmpty()){
				dmlWrapper.objectsToUpdate.addAll(ct_EventTriggerHelper.processApprovedPostEvents(postEventApprovedIds));
			}
            if(!setOfEvtGrpIds.isEmpty() && !System.isFuture() && !System.isBatch()){
                //Calculate number of events under the event group
                ct_EventTriggerHelper.updateNumberOfEvtOnEVtGrp(setOfEvtGrpIds);
            }
            if(!eventIdsForCampaignMemberSync.isEmpty()){
                // Logic of Campaign member Event Registration Sync
                ct_EventTriggerHelper.syncEventRegistrationToCampaignMember(eventIdsForCampaignMemberSync);
            }
		}
        // After Delete Logic 
        if (triggerAction == hed.TDTM_Runnable.Action.AfterDelete){
            System.debug('>>>>>>>>>>>>>>>>>>>>>>>>>>>EVENT AFTER DELETE TRIGGER<<<<<<<<<<<<<<<<<<<<<<<<<<<');
            for(Event__c evt : (list<Event__c>)oldlist){
                if(evt.Event_Group__c != null){
                    setOfEvtGrpIds.add(evt.Event_Group__c);
                }
            }
            if(!setOfEvtGrpIds.isEmpty() && !System.isFuture() && !System.isBatch()){
                //Calculate number of events under the event group
                ct_EventTriggerHelper.updateNumberOfEvtOnEVtGrp(setOfEvtGrpIds);
            }
        }

        if(!campaignIdToEventIdMap.isEmpty()){
            ct_EventTriggerHelper.processEventIdOnCampaign(campaignIdToEventIdMap);
        }
		return dmlWrapper;
	}
} */

global without sharing class ct_EventTriggerHandler{

    global static Set<Id> postEventApprovedIds          = new Set<Id>();
    global static List<Event__c> lstEvent               = new List<Event__c>();
    global static Set<Id> setOfEvtGrpIds                = new Set<Id>();
    //Campaign Ids for populating Event look up
    global static Map<Id, Id> campaignIdToEventIdMap    = new Map<Id, Id>();
    global static Set<Id> eventIdsForCampaignMemberSync = new Set<Id>();
    
    global static void handleBeforeInsert(list<Event__c> newlist){

        System.debug('>>>>>>>>>>>>>>>>>>>>>>>>>>>EVENT BEFORE INSERT TRIGGER<<<<<<<<<<<<<<<<<<<<<<<<<<<');
        for(Event__c evt : newlist){
            if(evt.GDPR_Statement_Used__c != null){
                //Method to update GDPR statement text on Event.
                ct_EventTriggerHelper.updateGDPRStatements(evt);
            }
            if(evt.Success_Message__c == null){
                ct_EventTriggerHelper.updateSuccessMessage(evt);
            }
        }

    }

    global static void handleAfterInsert(list<Event__c> newlist){
        System.debug('>>>>>>>>>>>>>>>>>>>>>>>>>>>EVENT AFTER INSERT TRIGGER<<<<<<<<<<<<<<<<<<<<<<<<<<<');
        for(Event__c thisEvent : newlist){
            if(thisEvent.Campaign__c != null){
                //Collect Campaign Ids for populating Event Look up in Campaign records
                campaignIdToEventIdMap.put(thisEvent.Campaign__c, thisEvent.Id);
            }
        }
        if(!campaignIdToEventIdMap.isEmpty()){
            //ct_EventTriggerHelper.processEventIdOnCampaign(campaignIdToEventIdMap);
            ProcessingEventIdOnCampaign(campaignIdToEventIdMap);
        }
    }

    global static void handleBeforeUpdate(Map<Id,Event__c> oldMap, Map<Id,Event__c> newMap){

        System.debug('>>>>>>>>>>>>>>>>>>>>>>>>>>>EVENT BEFORE UPDATE TRIGGER<<<<<<<<<<<<<<<<<<<<<<<<<<<');
        Map<Id, Event__c> triggerOldMap = oldMap;
        Map<Id, Event__c> triggerNewMap = newMap;
        System.debug('Calling before update -- Anshul');
        for(Event__c evt : triggerNewMap.values()){
            System.debug('Anshul - in Loop');
            if(evt.GDPR_Statement_Used__c != null && evt.GDPR_Statement_Used__c != triggerOldMap.get(evt.Id).GDPR_Statement_Used__c){
                System.debug('Anshul - in GDPR Used');
                //Method to update GDPR statement text on Event.
                ct_EventTriggerHelper.updateGDPRStatements(evt);
            }
            if(evt.Success_Message__c == null){
                ct_EventTriggerHelper.updateSuccessMessage(evt);
            }
            ct_EventTriggerHelper.checkEvtProdAvailable(evt, triggerOldMap.get(evt.Id));
                        
        }
    }

    global static void handleAfterUpdate(Map<Id,Event__c> oldMap, Map<Id,Event__c> newMap){

        System.debug('>>>>>>>>>>>>>>>>>>>>>>>>>>>EVENT AFTER UPDATE TRIGGER<<<<<<<<<<<<<<<<<<<<<<<<<<<');

        Map<Id, Event__c> triggerOldMap = oldMap;
        Map<Id, Event__c> triggerNewMap = newMap;

        for(Event__c thisEvent : triggerNewMap.values()){
            if(thisEvent.Request_Move_to_Post_Event__c 
                && thisEvent.Event_Status__c != triggerOldMap.get(thisEvent.Id).Event_Status__c
                    && thisEvent.Event_Status__c == ct_EventConstants.EVENT_STATUS_POST_EVENT){
                postEventApprovedIds.add(thisEvent.Id);
            }
                                    
            if(thisEvent.Active__c != triggerOldMap.get(thisEvent.Id).Active__c 
                    || thisEvent.Event_Group__c != triggerOldMap.get(thisEvent.Id).Event_Group__c){
                if(thisEvent.Event_Group__c != null){
                    setOfEvtGrpIds.add(thisEvent.Event_Group__c);
                }
                if(thisEvent.Event_Group__c != triggerOldMap.get(thisEvent.Id).Event_Group__c
                            && triggerOldMap.get(thisEvent.Id).Event_Group__c != null){
                    setOfEvtGrpIds.add(triggerOldMap.get(thisEvent.Id).Event_Group__c);
                }
            }
                    
            if(thisEvent.Campaign__c != null
                        && thisEvent.Campaign__c != triggerOldMap.get(thisEvent.Id).Campaign__c){
                campaignIdToEventIdMap.put(thisEvent.Campaign__c, thisEvent.Id);

                if(triggerOldMap.get(thisEvent.Id).Campaign__c != null){
                    campaignIdToEventIdMap.put(triggerOldMap.get(thisEvent.Id).Campaign__c, null);
                }
            }

            if(thisEvent.CM_ER_Auto_Sync__c != null
                        && thisEvent.CM_ER_Auto_Sync__c != triggerOldMap.get(thisEvent.Id).CM_ER_Auto_Sync__c
                        && thisEvent.CM_ER_Auto_Sync__c == ct_EventConstants.EVENT_CM_ER_AUTO_SYNC_YES){
                eventIdsForCampaignMemberSync.add(thisEvent.Id);
            }
		}
            
	    if(!postEventApprovedIds.isEmpty()){
                        System.debug('postEventApprovedIds'+postEventApprovedIds);

			// dmlWrapper.objectsToUpdate.addAll(
                List<SObject> sObjecttoUpdate = ct_EventTriggerHelper.processApprovedPostEvents(postEventApprovedIds);
                update sObjecttoUpdate;
                // );
		}
        if(!setOfEvtGrpIds.isEmpty() && !System.isFuture() && !System.isBatch()){
            //Calculate number of events under the event group
            ct_EventTriggerHelper.updateNumberOfEvtOnEVtGrp(setOfEvtGrpIds);
        }
        if(!eventIdsForCampaignMemberSync.isEmpty()){
            // Logic of Campaign member Event Registration Sync
            ct_EventTriggerHelper.syncEventRegistrationToCampaignMember(eventIdsForCampaignMemberSync);
        }
        if(!campaignIdToEventIdMap.isEmpty()){
            //ct_EventTriggerHelper.processEventIdOnCampaign(campaignIdToEventIdMap);
            ProcessingEventIdOnCampaign(campaignIdToEventIdMap);
        }
    }

    global static void handleAfterDelete(list<Event__c> oldlist){

        System.debug('>>>>>>>>>>>>>>>>>>>>>>>>>>>EVENT AFTER DELETE TRIGGER<<<<<<<<<<<<<<<<<<<<<<<<<<<');
        for(Event__c evt : oldlist){
            if(evt.Event_Group__c != null){
                setOfEvtGrpIds.add(evt.Event_Group__c);
            }
        }
        if(!setOfEvtGrpIds.isEmpty() && !System.isFuture() && !System.isBatch()){
            //Calculate number of events under the event group
            ct_EventTriggerHelper.updateNumberOfEvtOnEVtGrp(setOfEvtGrpIds);
        }
    }

    global static void ProcessingEventIdOnCampaign(Map<Id, Id> campaignToEventMap){
        
        if(!campaignToEventMap.isEmpty()){
            ct_EventTriggerHelper.processEventIdOnCampaign(campaignToEventMap);
        }

    }
}