force-app/main/default/objects/Campaign/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This associates a Campaign to an Event</description>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Event_Registration__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the Event Registration for the associated Campaign</description>
    <label>Event Registration</label>
    <referenceTo>Event_Registration__c</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Primary_Subject_Area_Interest__c.field-meta.xml
<CustomField>
    <fullName>Primary_Subject_Area_Interest__c</fullName>
    <description>The Primary Subject Area Interest of the Campaign Member</description>
    <label>Primary Subject Area Interest</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Course_Options</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For Syncing Campaign Member / Event Registration</description>
    <inlineHelpText>For Syncing Campaign Member with Event Registration</inlineHelpText>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/CM_ER_Auto_Sync__c.field-meta.xml
<CustomField>
    <fullName>CM_ER_Auto_Sync__c</fullName>
    <description>Should Sync Campaign Member and Event Registration</description>
    <inlineHelpText>Should Sync Campaign Member and Event Registration</inlineHelpText>
    <label>CM / ER Auto Sync</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Reg_Cancelled_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Reg_Cancelled_Status__c</fullName>
    <description>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</description>
    <inlineHelpText>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</inlineHelpText>
    <label>Event Reg &apos;Cancelled&apos; Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Reg_Checked_In_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Reg_Checked_In_Status__c</fullName>
    <description>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</description>
    <inlineHelpText>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</inlineHelpText>
    <label>Event Reg ‘Attended/Checked In’ Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Reg_Checked_Out_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Reg_Checked_Out_Status__c</fullName>
    <description>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</description>
    <inlineHelpText>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</inlineHelpText>
    <label>Event Reg ‘Attended/Checked Out’ Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Reg_Declined_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Reg_Declined_Status__c</fullName>
    <description>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</description>
    <inlineHelpText>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</inlineHelpText>
    <label>Event Reg &apos;Declined&apos; Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Reg_Did_Not_Attend_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Reg_Did_Not_Attend_Status__c</fullName>
    <description>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</description>
    <inlineHelpText>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</inlineHelpText>
    <label>Event Reg &apos;Did Not Attend&apos; Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Reg_Invited_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Reg_Invited_Status__c</fullName>
    <description>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</description>
    <inlineHelpText>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</inlineHelpText>
    <label>Event Reg &apos;Invited&apos; Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Reg_New_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Reg_New_Status__c</fullName>
    <description>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</description>
    <inlineHelpText>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</inlineHelpText>
    <label>Event Reg &apos;New&apos; Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Reg_Registered_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Reg_Registered_Status__c</fullName>
    <description>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</description>
    <inlineHelpText>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</inlineHelpText>
    <label>Event Reg &apos;Registered&apos; Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Object_for_New_Attendees__c.field-meta.xml
<CustomField>
    <fullName>Object_for_New_Attendees__c</fullName>
    <label>Object for New Attendees</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Create New Person Accounts</fullName>
            </value>
            <value>
                <fullName>Create New Leads</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Record_Type_for_New_Attendees__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_for_New_Attendees__c</fullName>
    <label>Record Type for New Attendees</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Object_for_New_Attendees__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LED_Contact</fullName>
                <label>LED Contact</label>
            </value>
            <value>
                <fullName>PersonAccount</fullName>
            </value>
            <value>
                <fullName>Employer</fullName>
                <isActive>false</isActive>
                <label>Employer</label>
            </value>
            <value>
                <fullName>Influencer</fullName>
                <isActive>false</isActive>
                <label>Influencer</label>
            </value>
            <value>
                <fullName>Person Account</fullName>
                <isActive>false</isActive>
                <label>Person Account</label>
            </value>
            <value>
                <fullName>Student</fullName>
                <isActive>false</isActive>
                <label>Student</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <displayFormat>REG-{0000000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This allows an event registration to be associated to an Account</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Enquirer__c.field-meta.xml
<CustomField>
    <fullName>Enquirer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Enquirer that has registered for the Event</description>
    <label>Enquirer</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Event_Email__c.field-meta.xml
<CustomField>
    <fullName>Event_Email__c</fullName>
    <label>Event Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Object_for_New_Attendees__c.field-meta.xml
<CustomField>
    <fullName>Object_for_New_Attendees__c</fullName>
    <formula>IF( NOT( ISBLANK( TEXT( Event_Product__r.Object_for_New_Attendees__c ) ) ) ,  TEXT( Event_Product__r.Object_for_New_Attendees__c ) , TEXT( Event__r.Object_for_New_Attendees__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Object for New Attendees</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Primary_Subject_Area_Interest__c.field-meta.xml
<CustomField>
    <fullName>Primary_Subject_Area_Interest__c</fullName>
    <description>This field is used to store Primary Subject Area interest value form Session</description>
    <inlineHelpText>This field is automated through Web Registration process</inlineHelpText>
    <label>Primary Subject Area Interest</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Record_Type_for_New_Attendees__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_for_New_Attendees__c</fullName>
    <formula>IF( NOT( ISBLANK( TEXT( Event_Product__r.Record_Type_for_New_Attendees__c ) ) ) , TEXT( Event_Product__r.Record_Type_for_New_Attendees__c ), TEXT( Event__r.Record_Type_for_New_Attendees__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record Type for New Attendees</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Event_Email__c.field-meta.xml
<CustomField>
    <fullName>Event_Email__c</fullName>
    <description>This refers to the email address provided as part of an Event registration</description>
    <label>Event Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/globalValueSets/Course_Options.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accounting and Financial Management</fullName>
    </customValue>
    <customValue>
        <fullName>American Studies</fullName>
    </customValue>
    <customValue>
        <fullName>Architecture</fullName>
    </customValue>
    <customValue>
        <fullName>Art &amp; Design</fullName>
    </customValue>
    <customValue>
        <fullName>Biological Sciences</fullName>
    </customValue>
    <customValue>
        <fullName>Building Surveying, Property Development and Quantity Surveying</fullName>
    </customValue>
    <customValue>
        <fullName>Business and Management</fullName>
    </customValue>
    <customValue>
        <fullName>Childhood Studies</fullName>
    </customValue>
    <customValue>
        <fullName>Civil Engineering and Construction Engineering Management</fullName>
    </customValue>
    <customValue>
        <fullName>Computing</fullName>
    </customValue>
    <customValue>
        <fullName>Computing &amp; ICT</fullName>
    </customValue>
    <customValue>
        <fullName>Creative &amp; Digital Technologies</fullName>
    </customValue>
    <customValue>
        <fullName>Creative Writing</fullName>
    </customValue>
    <customValue>
        <fullName>Criminology</fullName>
    </customValue>
    <customValue>
        <fullName>Dental Hygiene, Therapy and Nursing</fullName>
    </customValue>
    <customValue>
        <fullName>Earth and Environmental Sciences</fullName>
    </customValue>
    <customValue>
        <fullName>Economics</fullName>
    </customValue>
    <customValue>
        <fullName>Energy &amp; Electronic Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering and Technology - Other</fullName>
    </customValue>
    <customValue>
        <fullName>English Language and Linguistics</fullName>
    </customValue>
    <customValue>
        <fullName>English Literature</fullName>
    </customValue>
    <customValue>
        <fullName>Film and Media</fullName>
    </customValue>
    <customValue>
        <fullName>Games &amp; Animation</fullName>
    </customValue>
    <customValue>
        <fullName>Geography</fullName>
    </customValue>
    <customValue>
        <fullName>Graphics, Design &amp; Art</fullName>
    </customValue>
    <customValue>
        <fullName>History</fullName>
    </customValue>
    <customValue>
        <fullName>Human Resources Management</fullName>
    </customValue>
    <customValue>
        <fullName>International Development</fullName>
    </customValue>
    <customValue>
        <fullName>International Relations and Politics</fullName>
    </customValue>
    <customValue>
        <fullName>Journalism</fullName>
    </customValue>
    <description>Provides a list of all available subject area options</description>
    <masterLabel>Subject Areas</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ct_Campaign_MemberTriggerHelper.cls
/**
 * @description       : Helper class for Campaign Member TDTM Trigger Handler. Using this class to process the
 *                       Event Registrations if new campaign member is added to the campaign
 * @author            : Creation Admin
 * @last modified on  : 01-19-2021
 * @last modified by  : Creation Admin
 * Modifications Log 
 * Ver   Date         Author           Modification
 * 1.0   11-10-2020   Creation Admin   Initial Version
**/
global without sharing class ct_Campaign_MemberTriggerHelper {


    /**
    * @description Method to create event registration if new campaign member is added to campaign
    * @param campaignIds : Set of campaign Ids where campaign members were added
    * @param campaignMemberIds : Set of new campaign member Ids added to the campaign
    * @param leadIdToCampaignIdMap : Map of lead Id added to campaign
    * @param contactToCampaignIdMap : Map contact Id added to campaign
    * @param accountToCampaignIdMap : Map account Id added to campaign
    * @return void                                                                                                                                                                                                          
    **/
    global static void createEventRegistration(Set<Id> campaignIds, Set<Id> campaignMemberIds, Map<Id, Set<Id>> leadIdToCampaignIdMap, Map<Id, Set<Id>> contactToCampaignIdMap, Map<Id,Set<Id>> accountToCampaignIdMap){
        try{
            Boolean hasExistingEventRegistration = false;
            Map<Id, List<CampaignMember>> campaignToCampaignMemberMap = new Map<Id, List<CampaignMember>>();
            //Campaign Member Id To Event Registration
            Map<Id, Event_Registration__c> eventRegistrationToUpsert = new Map<Id, Event_Registration__c>();
            List<CampaignMember> campaignMemberList = new List<CampaignMember>();
            //Get all campaign members of the Campaigns 
            campaignMemberList = [SELECT 
                                                                Id,
                                                                FirstName,
                                                                LastName,
                                                                Email,
                                                                LeadId,
                                                                ContactId,
                                                                Account__c,
                                                                CampaignId,
                                                                Phone,
                                                                MobilePhone,
                                                                Status,
                                                                Primary_Subject_Area_Interest__c
                                                        FROM CampaignMember
                                                        WHERE ID IN:campaignMemberIds];

            for(CampaignMember thisCampaignMember: campaignMemberList){
                if(campaignToCampaignMemberMap.isEmpty() 
                || !campaignToCampaignMemberMap.containsKey(thisCampaignMember.CampaignId)){
                    campaignToCampaignMemberMap.put(thisCampaignMember.CampaignId, new List<CampaignMember>());
                }
                campaignToCampaignMemberMap.get(thisCampaignMember.CampaignId).add(thisCampaignMember);
            }
            //Map of Lead Id and campaign Id to Existing Event Registrations (Lead Id +'_'+Campaign Id+'_' => Event Registration)
            Map<String, Event_Registration__c> leadIdToCampaignIdEventRegistrationMap = new Map<String, Event_Registration__c>();
            //Map of Contact Id and campaign Id to Existing Event Registrations (Contact Id +'_'+Campaign Id+'_' => Event Registration)
            Map<String, Event_Registration__c> contactToCampaignIdEventRegistrationMap = new Map<String, Event_Registration__c>();
            //Map of Account Id and campaign Id to Existing Event Registrations (Account Id +'_'+Campaign Id+'_' => Event Registration)
            Map<String, Event_Registration__c> accountToCampaignIdEventRegistrationMap = new Map<String, Event_Registration__c>();

            /*Use leadIdToCampaignIdEventRegistrationMap, contactToCampaignIdEventRegistrationMap, accountToCampaignIdEventRegistrationMap to validate whether
                lead or contact or account added as campaign member in campaign also added as event registration in respective event record
                based on Campaign configuration in Event
            */
            for(Event_Registration__c thisExistingEventRegistration : [SELECT Id,
                                                                                                                                    First_Name__c, 
                                                                                                                                    Last_Name__c,
                                                                                                                                    Event__c, 
                                                                                                                                    Event__r.Campaign__c, 
                                                                                                                                    Event__r.CM_ER_Auto_Sync__c,  
                                                                                                                                    Event__r.Event_Reg_New_Status__c,
                                                                                                                                    Event__r.Event_Reg_Invited_Status__c,
                                                                                                                                    Event__r.Event_Reg_Registered_Status__c,
                                                                                                                                    Event__r.Event_Reg_Did_Not_Attend_Status__c,
                                                                                                                                    Event__r.Event_Reg_Declined_Status__c,
                                                                                                                                    Event__r.Event_Reg_Checked_Out_Status__c,
                                                                                                                                    Event__r.Event_Reg_Checked_In_Status__c,
                                                                                                                                    Event__r.Event_Reg_Cancelled_Status__c,
                                                                                                                                    Event_Email__c, 
                                                                                                                                    Contact__c,
                                                                                                                                    Enquirer__c,
                                                                                                                                    Account_Name__c,
                                                                                                                                    Object_for_New_Attendees__c, 
                                                                                                                                    Record_Type_for_New_Attendees__c,
                                                                                                                                    Event_Registration_Status__c,
                                                                                                                                    Primary_Subject_Area_Interest__c
                                                                                                                                FROM Event_Registration__c 
                                                                                                                                WHERE Event__r.Campaign__c IN:campaignIds
                                                                                                                                AND Event__r.CM_ER_Auto_Sync__c =:ct_EventConstants.EVENT_CM_ER_AUTO_SYNC_YES]) {

                if(thisExistingEventRegistration.Enquirer__c != null){
                    leadIdToCampaignIdEventRegistrationMap.put(Id.valueOf(thisExistingEventRegistration.Enquirer__c)+'_'+Id.valueOf(thisExistingEventRegistration.Event__r.Campaign__c), thisExistingEventRegistration);
                }
                /*if(thisExistingEventRegistration.Contact__c != null){
                    contactToCampaignIdEventRegistrationMap.put(Id.valueOf(thisExistingEventRegistration.Contact__c)+'_'+Id.valueOf(thisExistingEventRegistration.Event__r.Campaign__c), thisExistingEventRegistration);
                }*/
                if(thisExistingEventRegistration.Account_Name__c != null){
                    accountToCampaignIdEventRegistrationMap.put(Id.valueOf(thisExistingEventRegistration.Account_Name__c)+'_'+Id.valueOf(thisExistingEventRegistration.Event__r.Campaign__c), thisExistingEventRegistration);
                }
            }

            for(Event__c thisEvent : [SELECT
                                                                    Id,
                                                                    Campaign__c, 
                                                                    CM_ER_Auto_Sync__c,  
                                                                    Event_Reg_New_Status__c,
                                                                    Event_Reg_Invited_Status__c,
                                                                    Event_Reg_Registered_Status__c,
                                                                    Event_Reg_Did_Not_Attend_Status__c,
                                                                    Event_Reg_Declined_Status__c,
                                                                    Event_Reg_Checked_Out_Status__c,
                                                                    Event_Reg_Checked_In_Status__c,
                                                                    Event_Reg_Cancelled_Status__c
                                                                FROM Event__c
                                                                WHERE Campaign__c IN: campaignIds
                                                                AND CM_ER_Auto_Sync__c =:ct_EventConstants.EVENT_CM_ER_AUTO_SYNC_YES]){
            
            if(!campaignToCampaignMemberMap.isEmpty()
                && campaignToCampaignMemberMap.containsKey(thisEvent.Campaign__c)){
                    for(CampaignMember thisCampaignMember : campaignToCampaignMemberMap.get(thisEvent.Campaign__c)){
                        //Validate whether the Lead has been already added as event registration in respective Event
                        if(thisCampaignMember.LeadId != null
                            && !leadIdToCampaignIdEventRegistrationMap.isEmpty()
                            && leadIdToCampaignIdEventRegistrationMap.containsKey(Id.valueOf(thisCampaignMember.LeadId)+'_'+Id.valueOf(thisCampaignMember.CampaignId))
                            && leadIdToCampaignIdEventRegistrationMap.get(Id.valueOf(thisCampaignMember.LeadId)+'_'+Id.valueOf(thisCampaignMember.CampaignId)).Event__c == thisEvent.Id){
                                hasExistingEventRegistration = true;
                                //Sync the Event Registration status from Campaign member based on Campaign Member / Event Registration Sync configuration in respective event
                                processEventRegistrationStatusFromCampaignMember(leadIdToCampaignIdEventRegistrationMap.get(Id.valueOf(thisCampaignMember.LeadId)+'_'+Id.valueOf(thisCampaignMember.CampaignId)).Event__r, leadIdToCampaignIdEventRegistrationMap.get(Id.valueOf(thisCampaignMember.LeadId)+'_'+Id.valueOf(thisCampaignMember.CampaignId)), thisCampaignMember);
                                eventRegistrationToUpsert.put(thisCampaignMember.Id, leadIdToCampaignIdEventRegistrationMap.get(Id.valueOf(thisCampaignMember.LeadId)+'_'+Id.valueOf(thisCampaignMember.CampaignId)));
                        }

                        //Validate whether the Contact has been already added as event registration in respective Event
                        /*else if(thisCampaignMember.ContactId != null
                            && !contactToCampaignIdEventRegistrationMap.isEmpty()
                            && contactToCampaignIdEventRegistrationMap.containsKey(Id.valueOf(thisCampaignMember.ContactId)+'_'+Id.valueOf(thisCampaignMember.CampaignId))
                            && contactToCampaignIdEventRegistrationMap.get(Id.valueOf(thisCampaignMember.ContactId)+'_'+Id.valueOf(thisCampaignMember.CampaignId)).Event__c == thisEvent.Id){
                                hasExistingEventRegistration = true;
                                //Sync the Event Registration status from Campaign member based on Campaign Member / Event Registration Sync configuration in respective event
                                processEventRegistrationStatusFromCampaignMember(contactToCampaignIdEventRegistrationMap.get(Id.valueOf(thisCampaignMember.ContactId)+'_'+Id.valueOf(thisCampaignMember.CampaignId)).Event__r, contactToCampaignIdEventRegistrationMap.get(Id.valueOf(thisCampaignMember.ContactId)+'_'+Id.valueOf(thisCampaignMember.CampaignId)), thisCampaignMember);
                                eventRegistrationToUpsert.put(thisCampaignMember.Id, contactToCampaignIdEventRegistrationMap.get(Id.valueOf(thisCampaignMember.ContactId)+'_'+Id.valueOf(thisCampaignMember.CampaignId)));
                        }*/

                        //Validate whether the Account has been already added as event registration in respective Event
                        else if(thisCampaignMember.Account__c != null
                            && !accountToCampaignIdEventRegistrationMap.isEmpty()
                            && accountToCampaignIdEventRegistrationMap.containsKey(Id.valueOf(thisCampaignMember.Account__c)+'_'+Id.valueOf(thisCampaignMember.CampaignId))
                            && accountToCampaignIdEventRegistrationMap.get(Id.valueOf(thisCampaignMember.Account__c)+'_'+Id.valueOf(thisCampaignMember.CampaignId)).Event__c == thisEvent.Id){
                                hasExistingEventRegistration = true;
                                //Sync the Event Registration status from Campaign member based on Campaign Member / Event Registration Sync configuration in respective event
                                processEventRegistrationStatusFromCampaignMember(accountToCampaignIdEventRegistrationMap.get(Id.valueOf(thisCampaignMember.Account__c)+'_'+Id.valueOf(thisCampaignMember.CampaignId)).Event__r, accountToCampaignIdEventRegistrationMap.get(Id.valueOf(thisCampaignMember.Account__c)+'_'+Id.valueOf(thisCampaignMember.campaignId)), thisCampaignMember);
                                eventRegistrationToUpsert.put(thisCampaignMember.Id, accountToCampaignIdEventRegistrationMap.get(Id.valueOf(thisCampaignMember.Account__c)+'_'+Id.valueOf(thisCampaignMember.CampaignId)));
                            }

                        if(hasExistingEventRegistration){
                            hasExistingEventRegistration = false;
                        }
                        else {
                            //If there is no Event registration with the Lead / Contact / Account added as Campaign member in respective Event then create new Event registration
                            Event_Registration__c thisNewEventRegistration = new Event_Registration__c();
                            thisNewEventRegistration.Event__c                       = thisEvent.Id;
                            thisNewEventRegistration.First_Name__c              = thisCampaignMember.FirstName;
                            thisNewEventRegistration.Last_Name__c               = thisCampaignMember.LastName;
                            thisNewEventRegistration.Event_Email__c         = thisCampaignMember.Email;
                            thisNewEventRegistration.Event_Mobile__c            = thisCampaignMember.MobilePhone;
                            thisNewEventRegistration.Registration_Type__c = ct_EventConstants.EVENT_REGISTRATION_TYPE_MY_SELF;
                            thisNewEventRegistration.RecordTypeId         = ct_EventConstants.EVENT_REGISTRATION_MASTER_EVENT_RECORD_TYPE_ID;

                            if(thisCampaignMember.LeadId != null){
                                thisNewEventRegistration.Enquirer__c = thisCampaignMember.LeadId;
                            }

                            /*if(thisCampaignMember.ContactId != null){
                                thisNewEventRegistration.Contact__c = thisCampaignMember.ContactId;
                            }*/

                            if(thisCampaignMember.Account__c != null){
                                thisNewEventRegistration.Account_Name__c = thisCampaignMember.Account__c;
                            }
                            //Sync the Event Registration status from Campaign member based on Campaign Member / Event Registration Sync configuration in respective event
                            processEventRegistrationStatusFromCampaignMember(thisEvent, thisNewEventRegistration, thisCampaignMember);
                            //eventRegistrationToUpsert.add(thisNewEventRegistration);
                            eventRegistrationToUpsert.put(thisCampaignMember.Id, thisNewEventRegistration);
                        }
                    }
                }
            }
            
            if(!eventRegistrationToUpsert.isEmpty()){
                //Upsert Event Registration records
                upsert eventRegistrationToUpsert.values();
                //Populate Event Registration Id on respective new campaign member record
                processEventRegistrationIdInCampaignMember(campaignMemberList, eventRegistrationToUpsert);
                //Update campaign member record after populating the event registration Id
                update campaignMemberList;
            }
        }
        catch(Exception e){
            ct_Logger.logMessage(e, 'Campaign Member - Event Registration');
            throw e;
        }
    }
    
    /**
    * @description Method to populate Event registration Id in campaign member record
    * @param campaignMemberList : Campaign member list for which event registration needs to be populated
    * @param eventRegistrationMap : Campaign Id to event registration map
    **/
    global static void processEventRegistrationIdInCampaignMember(List<CampaignMember> campaignMemberList, Map<Id, Event_Registration__c> eventRegistrationMap){
        for(CampaignMember thisCampaignMember : campaignMemberList){
            if(!eventRegistrationMap.isEmpty()
            && eventRegistrationMap.containsKey(thisCampaignMember.Id)){
                thisCampaignMember.Event_Registration__c = eventRegistrationMap.get(thisCampaignMember.Id).Id;
            }
        }
    }

    global static void syncEventRegistrationWithCampaignMember(List<CampaignMember> campaignMemberList, Set<Id> eventRegistrationIds){
        try{
            List<Event_Registration__c> eventRegistrationsToUpdate = new List<Event_Registration__c>();
            Map<Id, Event_Registration__c> eventRegistrationMap = new Map<Id, Event_Registration__c>(
                                                                [SELECT Id,
                                                                First_Name__c, 
                                                                Last_Name__c,
                                                                Event__c, 
                                                                Event__r.Campaign__c, 
                                                                Event__r.CM_ER_Auto_Sync__c,  
                                                                Event__r.Event_Reg_New_Status__c,
                                                                Event__r.Event_Reg_Invited_Status__c,
                                                                Event__r.Event_Reg_Registered_Status__c,
                                                                Event__r.Event_Reg_Did_Not_Attend_Status__c,
                                                                Event__r.Event_Reg_Declined_Status__c,
                                                                Event__r.Event_Reg_Checked_Out_Status__c,
                                                                Event__r.Event_Reg_Checked_In_Status__c,
                                                                Event__r.Event_Reg_Cancelled_Status__c,
                                                                Event_Email__c, 
                                                                Contact__c,
                                                                Enquirer__c,
                                                                Primary_Subject_Area_Interest__c,
                                                                Object_for_New_Attendees__c, 
                                                                Record_Type_for_New_Attendees__c,
                                                                Event_Registration_Status__c
                                                            FROM Event_Registration__c 
                                                            WHERE Id IN:eventRegistrationIds]);

            for(CampaignMember thisCampaignMember : campaignMemberList){
                if(!eventRegistrationMap.isEmpty()
                    && eventRegistrationMap.containsKey(thisCampaignMember.Event_Registration__c)){
                        processEventRegistrationStatusFromCampaignMember(eventRegistrationMap.get(thisCampaignMember.Event_Registration__c).Event__r, eventRegistrationMap.get(thisCampaignMember.Event_Registration__c), thisCampaignMember);
                        eventRegistrationsToUpdate.add(eventRegistrationMap.get(thisCampaignMember.Event_Registration__c));
                }
            }

            if(!eventRegistrationsToUpdate.isEmpty()){
                ct_Event_RegistrationTriggerHandler.turnOff();
                update eventRegistrationsToUpdate;
            }
        }
        catch(Exception e){
            ct_Logger.logMessage(e, 'Event Registration Status Sync From Campaign Member');
            throw e;
        }
    }

    global static void processEventRegistrationStatusFromCampaignMember(Event__c thisEvent, Event_Registration__c thisEventRegistration, CampaignMember thisCampaignMember){
        Map<String, String> eventRegistrationStatusMap = new Map<String,String>{
            ct_EventConstants.CAMPAIGN_MEMBER_STATUS_NEW            => thisEvent.Event_Reg_New_Status__c,                       
            ct_EventConstants.CAMPAIGN_MEMBER_STATUS_INVITED        => thisEvent.Event_Reg_Invited_Status__c,
            ct_EventConstants.CAMPAIGN_MEMBER_STATUS_REGISTERED     => thisEvent.Event_Reg_Registered_Status__c,
            ct_EventConstants.CAMPAIGN_MEMBER_STATUS_CHECKED_IN     => thisEvent.Event_Reg_Checked_In_Status__c,
            ct_EventConstants.CAMPAIGN_MEMBER_STATUS_CHECKED_OUT    => thisEvent.Event_Reg_Checked_Out_Status__c,
            ct_EventConstants.CAMPAIGN_MEMBER_STATUS_DID_NOT_ATTEND => thisEvent.Event_Reg_Did_Not_Attend_Status__c,
            ct_EventConstants.CAMPAIGN_MEMBER_STATUS_DECLINED       => thisEvent.Event_Reg_Declined_Status__c,
            ct_EventConstants.CAMPAIGN_MEMBER_STATUS_CANCELLED      => thisEvent.Event_Reg_Cancelled_Status__c};

            if(eventRegistrationStatusMap.containsKey(thisCampaignMember.Status)
                && eventRegistrationStatusMap.get(thisCampaignMember.Status) != null){
                    thisEventRegistration.Event_Registration_Status__c     = eventRegistrationStatusMap.get(thisCampaignMember.Status);
                    thisEventRegistration.Primary_Subject_Area_Interest__c = thisCampaignMember.Primary_Subject_Area_Interest__c;
        }
    }

    global static void processCampaignMemberStatusFromEventRegistrationStatus(Event_Registration__c thisEventRegistration, CampaignMember thisCampaignMember){
            
        Map<String, String> campaignMemberStatusMap = new Map<String,String>{
            ct_EventConstants.EVENT_REGISTRATION_NEW            => thisEventRegistration.Event__r.Event_Reg_New_Status__c,
            ct_EventConstants.EVENT_REGISTRATION_INVITED        => thisEventRegistration.Event__r.Event_Reg_Invited_Status__c,
            ct_EventConstants.EVENT_REGISTRATION_REGISTERED     => thisEventRegistration.Event__r.Event_Reg_Registered_Status__c,
            ct_EventConstants.EVENT_REGISTRATION_CHECKED_IN     => thisEventRegistration.Event__r.Event_Reg_Checked_In_Status__c,
            ct_EventConstants.EVENT_REGISTRATION_CHECKED_OUT    => thisEventRegistration.Event__r.Event_Reg_Checked_Out_Status__c,
            ct_EventConstants.EVENT_REGISTRATION_DID_NOT_ATTEND => thisEventRegistration.Event__r.Event_Reg_Did_Not_Attend_Status__c,
            ct_EventConstants.EVENT_REGISTRATION_DECLINED       => thisEventRegistration.Event__r.Event_Reg_Declined_Status__c,
            ct_EventConstants.EVENT_REGISTRATION_CANCELLED      => thisEventRegistration.Event__r.Event_Reg_Cancelled_Status__c};

            if(campaignMemberStatusMap.containsKey(thisEventRegistration.Event_Registration_Status__c)
                    && campaignMemberStatusMap.get(thisEventRegistration.Event_Registration_Status__c) != null){
                        thisCampaignMember.Status                           = campaignMemberStatusMap.get(thisEventRegistration.Event_Registration_Status__c);
                        thisCampaignMember.Primary_Subject_Area_Interest__c = thisEventRegistration.Primary_Subject_Area_Interest__c;
            }
        }

        @future
        global static void campaignMemberRollupCalculation(Set<Id> campaignIds){
            processCampaignMemberCountOnEvent(campaignIds);
        }
    
    global static void processCampaignMemberCountOnEvent(Set<Id> campaignIds){
        Set<Id> campaignEventIds = new Set<Id>();
        Map<Id, Event__c> mapOfCampaignEventsToUpdate = new Map<Id, Event__c>();
        Map<Id, Campaign> mapOfCampaign = new Map<Id, Campaign>();
        String campaignId;
        try{
            for(Campaign camp : [Select Id, Event__c From Campaign Where Id IN : campaignIds]){
                if(camp.Event__c != null){
                    campaignEventIds.add(camp.Event__c);
                    mapOfCampaign.put(camp.Id, camp);
                }
            }
            for(Event__c evt : [Select Id, Name, No_Campaign_Members__c From Event__c Where Id IN : campaignEventIds]){
                evt.No_Campaign_Members__c = 0;
                mapOfCampaignEventsToUpdate.put(evt.Id, evt);
            }
        
        for(AggregateResult thisAggregrateResult : [Select COUNT(Id) totalRecords, CampaignId FROM CampaignMember
                                                    WHERE CampaignId IN : campaignIds
                                                    GROUP BY CampaignId]){
            
           campaignId               = (Id)thisAggregrateResult.get('CampaignId');
           if(!mapOfCampaign.isEmpty() && mapOfCampaign.containsKey(campaignId)){
                mapOfCampaignEventsToUpdate.get(mapOfCampaign.get(campaignId).Event__c).put('No_Campaign_Members__c',(Integer)thisAggregrateResult.get('totalRecords'));                                          
           }                                             
         }
        
        if(!mapOfCampaignEventsToUpdate.isEmpty()){
            update mapOfCampaignEventsToUpdate.values();
        }
       }
       catch(Exception e){
            //Exception mechanism to log any exceptions occured during the dml operation
            ct_Logger.logMessage(e, 'Event - Campaign Member Custom Rollup field Calculation');
        }        
        }
        
        global static void cancelEventRegistration(Set<Id> eventRegistationIds){
            List<Event_Registration__c> eventRegistrationToUpdate = new List<Event_Registration__c>();
            try{
            for(Event_Registration__c thisEventRegistration : [SELECT Id, Event_Registration_Status__c
                                                                                                                    FROM Event_Registration__c
                                                                                                                    WHERE Id IN: eventRegistationIds]){
                thisEventRegistration.Event_Registration_Status__c = ct_EventConstants.EVENT_REGISTRATION_CANCELLED;                                                    
              eventRegistrationToUpdate.add(thisEventRegistration);                                                                                 
            }
            update eventRegistrationToUpdate;
        }
        catch(Exception e){
            //Exception mechanism to log any exceptions occured during the dml operation
            ct_Logger.logMessage(e, 'Event Registration Cancellation - Campaign member Removal');
        }
    }
}