force-app/main/default/objects/Campaign/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This associates a Campaign to an Event</description>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Event_Registration__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the Event Registration for the associated Campaign</description>
    <label>Event Registration</label>
    <referenceTo>Event_Registration__c</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Primary_Subject_Area_Interest__c.field-meta.xml
<CustomField>
    <fullName>Primary_Subject_Area_Interest__c</fullName>
    <description>The Primary Subject Area Interest of the Campaign Member</description>
    <label>Primary Subject Area Interest</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Course_Options</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Campaign__c.field-meta.xml
<CustomField>
    <fullName>Campaign__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>For Syncing Campaign Member / Event Registration</description>
    <inlineHelpText>For Syncing Campaign Member with Event Registration</inlineHelpText>
    <label>Campaign</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/CM_ER_Auto_Sync__c.field-meta.xml
<CustomField>
    <fullName>CM_ER_Auto_Sync__c</fullName>
    <description>Should Sync Campaign Member and Event Registration</description>
    <inlineHelpText>Should Sync Campaign Member and Event Registration</inlineHelpText>
    <label>CM / ER Auto Sync</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Reg_Cancelled_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Reg_Cancelled_Status__c</fullName>
    <description>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</description>
    <inlineHelpText>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</inlineHelpText>
    <label>Event Reg &apos;Cancelled&apos; Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Reg_Checked_In_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Reg_Checked_In_Status__c</fullName>
    <description>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</description>
    <inlineHelpText>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</inlineHelpText>
    <label>Event Reg ‘Attended/Checked In’ Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Reg_Checked_Out_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Reg_Checked_Out_Status__c</fullName>
    <description>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</description>
    <inlineHelpText>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</inlineHelpText>
    <label>Event Reg ‘Attended/Checked Out’ Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Reg_Declined_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Reg_Declined_Status__c</fullName>
    <description>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</description>
    <inlineHelpText>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</inlineHelpText>
    <label>Event Reg &apos;Declined&apos; Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Reg_Did_Not_Attend_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Reg_Did_Not_Attend_Status__c</fullName>
    <description>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</description>
    <inlineHelpText>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</inlineHelpText>
    <label>Event Reg &apos;Did Not Attend&apos; Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Reg_Invited_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Reg_Invited_Status__c</fullName>
    <description>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</description>
    <inlineHelpText>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</inlineHelpText>
    <label>Event Reg &apos;Invited&apos; Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Reg_New_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Reg_New_Status__c</fullName>
    <description>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</description>
    <inlineHelpText>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</inlineHelpText>
    <label>Event Reg &apos;New&apos; Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Reg_Registered_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Reg_Registered_Status__c</fullName>
    <description>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</description>
    <inlineHelpText>Please enter the Campaign Member Status (on the related Campaign) that you would like to map this Event Registration Status to. Please note that the text used must be identical</inlineHelpText>
    <label>Event Reg &apos;Registered&apos; Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Object_for_New_Attendees__c.field-meta.xml
<CustomField>
    <fullName>Object_for_New_Attendees__c</fullName>
    <label>Object for New Attendees</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Create New Person Accounts</fullName>
            </value>
            <value>
                <fullName>Create New Leads</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Record_Type_for_New_Attendees__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_for_New_Attendees__c</fullName>
    <label>Record Type for New Attendees</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Object_for_New_Attendees__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LED_Contact</fullName>
                <label>LED Contact</label>
            </value>
            <value>
                <fullName>PersonAccount</fullName>
            </value>
            <value>
                <fullName>Employer</fullName>
                <isActive>false</isActive>
                <label>Employer</label>
            </value>
            <value>
                <fullName>Influencer</fullName>
                <isActive>false</isActive>
                <label>Influencer</label>
            </value>
            <value>
                <fullName>Person Account</fullName>
                <isActive>false</isActive>
                <label>Person Account</label>
            </value>
            <value>
                <fullName>Student</fullName>
                <isActive>false</isActive>
                <label>Student</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <displayFormat>REG-{0000000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This allows an event registration to be associated to an Account</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Enquirer__c.field-meta.xml
<CustomField>
    <fullName>Enquirer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Enquirer that has registered for the Event</description>
    <label>Enquirer</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Event_Email__c.field-meta.xml
<CustomField>
    <fullName>Event_Email__c</fullName>
    <label>Event Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Object_for_New_Attendees__c.field-meta.xml
<CustomField>
    <fullName>Object_for_New_Attendees__c</fullName>
    <formula>IF( NOT( ISBLANK( TEXT( Event_Product__r.Object_for_New_Attendees__c ) ) ) ,  TEXT( Event_Product__r.Object_for_New_Attendees__c ) , TEXT( Event__r.Object_for_New_Attendees__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Object for New Attendees</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Primary_Subject_Area_Interest__c.field-meta.xml
<CustomField>
    <fullName>Primary_Subject_Area_Interest__c</fullName>
    <description>This field is used to store Primary Subject Area interest value form Session</description>
    <inlineHelpText>This field is automated through Web Registration process</inlineHelpText>
    <label>Primary Subject Area Interest</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Record_Type_for_New_Attendees__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_for_New_Attendees__c</fullName>
    <formula>IF( NOT( ISBLANK( TEXT( Event_Product__r.Record_Type_for_New_Attendees__c ) ) ) , TEXT( Event_Product__r.Record_Type_for_New_Attendees__c ), TEXT( Event__r.Record_Type_for_New_Attendees__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record Type for New Attendees</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Event_Email__c.field-meta.xml
<CustomField>
    <fullName>Event_Email__c</fullName>
    <description>This refers to the email address provided as part of an Event registration</description>
    <label>Event Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Web_Site_Submission__c/Web_Site_Submission__c.object-meta.xml
<CustomObject>
    <description>This is object is used to store values from website forms and distribute the record values to other respective objects.</description>
    <label>Web Site Submission</label>
    <nameField>
        <label>Web Site Submissions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Web Site Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Web_Site_Submission__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>The record values will be stored here in a JSON format</description>
    <label>Payload</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Course_Options.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accounting and Financial Management</fullName>
    </customValue>
    <customValue>
        <fullName>American Studies</fullName>
    </customValue>
    <customValue>
        <fullName>Architecture</fullName>
    </customValue>
    <customValue>
        <fullName>Art &amp; Design</fullName>
    </customValue>
    <customValue>
        <fullName>Biological Sciences</fullName>
    </customValue>
    <customValue>
        <fullName>Building Surveying, Property Development and Quantity Surveying</fullName>
    </customValue>
    <customValue>
        <fullName>Business and Management</fullName>
    </customValue>
    <customValue>
        <fullName>Childhood Studies</fullName>
    </customValue>
    <customValue>
        <fullName>Civil Engineering and Construction Engineering Management</fullName>
    </customValue>
    <customValue>
        <fullName>Computing</fullName>
    </customValue>
    <customValue>
        <fullName>Computing &amp; ICT</fullName>
    </customValue>
    <customValue>
        <fullName>Creative &amp; Digital Technologies</fullName>
    </customValue>
    <customValue>
        <fullName>Creative Writing</fullName>
    </customValue>
    <customValue>
        <fullName>Criminology</fullName>
    </customValue>
    <customValue>
        <fullName>Dental Hygiene, Therapy and Nursing</fullName>
    </customValue>
    <customValue>
        <fullName>Earth and Environmental Sciences</fullName>
    </customValue>
    <customValue>
        <fullName>Economics</fullName>
    </customValue>
    <customValue>
        <fullName>Energy &amp; Electronic Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering and Technology - Other</fullName>
    </customValue>
    <customValue>
        <fullName>English Language and Linguistics</fullName>
    </customValue>
    <customValue>
        <fullName>English Literature</fullName>
    </customValue>
    <customValue>
        <fullName>Film and Media</fullName>
    </customValue>
    <customValue>
        <fullName>Games &amp; Animation</fullName>
    </customValue>
    <customValue>
        <fullName>Geography</fullName>
    </customValue>
    <customValue>
        <fullName>Graphics, Design &amp; Art</fullName>
    </customValue>
    <customValue>
        <fullName>History</fullName>
    </customValue>
    <customValue>
        <fullName>Human Resources Management</fullName>
    </customValue>
    <customValue>
        <fullName>International Development</fullName>
    </customValue>
    <customValue>
        <fullName>International Relations and Politics</fullName>
    </customValue>
    <customValue>
        <fullName>Journalism</fullName>
    </customValue>
    <description>Provides a list of all available subject area options</description>
    <masterLabel>Subject Areas</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ct_CampaignMemberEventReg_Sync_Queueable.cls
/**
 * @description       : Queueable class for Creating Campaign member from Event Registration for Syncing and 
 * 						calculate and update the No of Campaign Member field in Event
 * @author            : Creation Admin
 * @last modified on  : 01-14-2021
 * @last modified by  : Creation Admin
 * Modifications Log 
 * Ver   Date         Author           Modification
 * 1.0   11-10-2020   Creation Admin   Initial Version
**/
global without sharing class ct_CampaignMemberEventReg_Sync_Queueable implements Queueable {
	private Set<String> eventRegistrationIds;
	private Set<String> contactIds;
	private Set<String> leadIds;
	private Set<String> accountIds;

	global ct_CampaignMemberEventReg_Sync_Queueable(Set<String> eventRegistrationIdSet, Set<String> contactIdSet, Set<String> leadIdsSet, Set<String> accountIdSet) {
		this.eventRegistrationIds = eventRegistrationIdSet;
		this.contactIds 					= contactIdSet;
		this.leadIds 						= leadIdsSet;
		this.accountIds 					= accountIdSet;
	}

	global void execute(QueueableContext context) {
		try{
			Map<Id, CampaignMember> eventRegistrationIdToCampaignPayloadMap = new Map<Id, CampaignMember>();
			for(Web_Site_Submission__c thisWebSiteSubmission : [SELECT Id,
																		Name,
																		Payload__c
																	FROM Web_Site_Submission__c
																	WHERE Name IN:eventRegistrationIds]){
				if(String.isNotBlank(thisWebSiteSubmission.Payload__c)){
					CampaignMember thisCampaignMemberPayload = (CampaignMember)JSON.deserialize(thisWebSiteSubmission.Payload__c, CampaignMember.class);
					eventRegistrationIdToCampaignPayloadMap.put(Id.valueOf(thisWebSiteSubmission.Name), thisCampaignMemberPayload);
				}					
			}
			//Fetch the Event Registrations
			List<Event_Registration__c> thisEventRegistrationList = [SELECT Id,
																			First_Name__c, 
																			Last_Name__c,
																			Event__c, 
																			Event__r.Campaign__c, 
																			Event__r.CM_ER_Auto_Sync__c,  
																			Event__r.Event_Reg_New_Status__c,
																			Event__r.Event_Reg_Invited_Status__c,
																			Event__r.Event_Reg_Registered_Status__c,
																			Event__r.Event_Reg_Did_Not_Attend_Status__c,
																			Event__r.Event_Reg_Declined_Status__c,
																			Event__r.Event_Reg_Checked_Out_Status__c,
																			Event__r.Event_Reg_Checked_In_Status__c,
																			Event__r.Event_Reg_Cancelled_Status__c,
																			Event_Email__c, 
																			Contact__c,
																			Enquirer__c,
																			Account_Name__c,
																			Object_for_New_Attendees__c, 
																			Record_Type_for_New_Attendees__c,
																			Primary_Subject_Area_Interest__c,
																			Event_Registration_Status__c
																	FROM Event_Registration__c 
																	WHERE Id IN:eventRegistrationIds];
			String uniqueKey;
			Map<String, CampaignMember> leadIdToCampaignMemberMap = new Map<String, CampaignMember>();
			//Map<String, CampaignMember> contactToCampaignMemberMap = new Map<String, CampaignMember>();
			Map<String, CampaignMember> accountToCampaignMemberMap = new Map<String, CampaignMember>();
		 	//Fetch the Campaign Member based on Lead and Contact Ids
			for(CampaignMember thisCampaignMember :[SELECT Id, 
																									LeadId, 
																									ContactId,
																									Account__c,
																									CampaignId,
																									Status
																							FROM CampaignMember
																							WHERE LeadId IN:LeadIds
																							OR ContactId IN:contactIds 
																							OR Account__c IN:accountIds]){
					if(thisCampaignMember.LeadId != null){
							leadIdToCampaignMemberMap.put(Id.valueOf(thisCampaignMember.LeadId)+'_'+Id.valueOf(thisCampaignMember.CampaignId), thisCampaignMember);
					}

					/*if(thisCampaignMember.ContactId != null){
							contactToCampaignMemberMap.put(Id.valueOf(thisCampaignMember.ContactId)+'_'+Id.valueOf(thisCampaignMember.CampaignId), thisCampaignMember);
					}*/
					
					if(thisCampaignMember.Account__c != null){
						accountToCampaignMemberMap.put(Id.valueOf(thisCampaignMember.Account__c)+'_'+Id.valueOf(thisCampaignMember.CampaignId), thisCampaignMember);
					}
			}

			List<CampaignMember> campaignMembersToInsert = new List<CampaignMember>();
			Set<Id> campaignIds =  new Set<Id>();
            Set<Id> eventRegistrationIds = new Set<Id>();
			for(Event_Registration__c thisEventRegistration : thisEventRegistrationList){
                if(thisEventRegistration.Event__r.CM_ER_Auto_Sync__c == ct_EventConstants.EVENT_CM_ER_AUTO_SYNC_YES
					&& (/*thisEventRegistration.Contact__c != null ||*/ thisEventRegistration.Enquirer__c != null || thisEventRegistration.Account_Name__c != null)
					&& thisEventRegistration.Event__r.Campaign__c != null){

						CampaignMember thisCampaignMember = new CampaignMember();
					
						if(!eventRegistrationIdToCampaignPayloadMap.isEmpty()
							&& eventRegistrationIdToCampaignPayloadMap.containsKey(Id.valueOf(thisEventRegistration.Id))){
								
							Map<String, Object> fieldsToValue = eventRegistrationIdToCampaignPayloadMap.get(Id.valueOf(thisEventRegistration.Id)).getPopulatedFieldsAsMap();
							for(String fieldAPIName : fieldsToValue.keyset()){
								thisCampaignMember.put(fieldAPIName, fieldsToValue.get(fieldAPIName));
							}
						}

						thisCampaignMember.Event_Registration__c = thisEventRegistration.Id;
						thisCampaignMember.CampaignId            = thisEventRegistration.Event__r.Campaign__c;
						campaignIds.add(thisEventRegistration.Event__r.Campaign__c);
						ct_Campaign_MemberTriggerHelper.processCampaignMemberStatusFromEventRegistrationStatus(thisEventRegistration, thisCampaignMember);
								
						/*if(thisEventRegistration.Contact__c != null){
							thisCampaignMember.ContactId = thisEventRegistration.Contact__c;
							uniqueKey = Id.valueOf(thisEventRegistration.Contact__c)+'_'+Id.valueOf(thisEventRegistration.Event__r.Campaign__c);

							if(contactToCampaignMemberMap.isEmpty()
								|| !contactToCampaignMemberMap.containsKey(uniqueKey)){
									campaignMembersToInsert.add(thisCampaignMember);
							}
						}*/
						if(thisEventRegistration.Enquirer__c != null){
							thisCampaignMember.LeadId = thisEventRegistration.Enquirer__c;
							uniqueKey = Id.valueOf(thisEventRegistration.Enquirer__c)+'_'+Id.valueOf(thisEventRegistration.Event__r.Campaign__c);

							if(leadIdToCampaignMemberMap.isEmpty()
								|| !leadIdToCampaignMemberMap.containsKey(uniqueKey)){
									campaignMembersToInsert.add(thisCampaignMember);
							}
						}
						else if(thisEventRegistration.Account_Name__c != null){
							thisCampaignMember.Account__c = thisEventRegistration.Account_Name__c;
							uniqueKey = Id.valueOf(thisEventRegistration.Account_Name__c)+'_'+Id.valueOf(thisEventRegistration.Event__r.Campaign__c);

							if(accountToCampaignMemberMap.isEmpty()
								|| !accountToCampaignMemberMap.containsKey(uniqueKey)){
									campaignMembersToInsert.add(thisCampaignMember);
							}
						}
			}
			
			if(!campaignMembersToInsert.isEmpty()){
				insert campaignMembersToInsert;
				// calculate event No of campaign member roll up field
				ct_Campaign_MemberTriggerHelper.processCampaignMemberCountOnEvent(campaignIds);
			}
		}
	}
		catch(Exception e){
			ct_Logger.logMessage(e, 'Event Registration Queueable- Campaign Member Sync');
			throw e;
		}
	}
}