force-app/main/default/objects/Campaign/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This associates a Campaign to an Event</description>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Campaigns</relationshipLabel>
    <relationshipName>Campaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Allow_Duplicate_Event_Registrations__c.field-meta.xml
<CustomField>
    <fullName>Allow_Duplicate_Event_Registrations__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allow the user to allow Duplicate Event Registration for this Event</description>
    <inlineHelpText>Allow the user to allow Duplicate Event Registration for this Event</inlineHelpText>
    <label>Allow Duplicate Event Registrations</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_End_Date__c</fullName>
    <label>Event End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Start_Date__c</fullName>
    <label>Event Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Web_Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Web_Event_Name__c</fullName>
    <inlineHelpText>Please enter the display name that you wish to show people booking via the Event Registration page</inlineHelpText>
    <label>Web Event Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Order__c/Event_Order__c.object-meta.xml
<CustomObject>
    <label>Event Order</label>
    <nameField>
        <displayFormat>O - {00000000}</displayFormat>
        <label>Event Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Order__c/fields/Cancellation_Description__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Description__c</fullName>
    <label>Cancellation Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Event no longer relevant</fullName>
            </value>
            <value>
                <fullName>Cannot make the date</fullName>
            </value>
            <value>
                <fullName>Too far to travel</fullName>
            </value>
            <value>
                <fullName>Do not want to say</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Date Conflict</fullName>
                <isActive>false</isActive>
                <label>Date Conflict</label>
            </value>
            <value>
                <fullName>Event Not Relevant</fullName>
                <isActive>false</isActive>
                <label>Event Not Relevant</label>
            </value>
            <value>
                <fullName>Not Provided</fullName>
                <isActive>false</isActive>
                <label>Not Provided</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Event Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Ticket_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/QR_Code__c.field-meta.xml
<CustomField>
    <fullName>QR_Code__c</fullName>
    <label>QR Code</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Event_Product__c/Event_Product__c.object-meta.xml
<CustomObject>
    <label>Event Product</label>
    <nameField>
        <label>Event Product	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Product__c/fields/Allow_Primary_Session__c.field-meta.xml
<CustomField>
    <fullName>Allow_Primary_Session__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to identify whether to allow the user to attach the Primary Session when creating Event Registrations through the form.</description>
    <inlineHelpText>Please select to allow the user to add primary sessions while registering.</inlineHelpText>
    <label>Allow Primary Session Registration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Product__c/fields/Enable_Session_Registrations__c.field-meta.xml
<CustomField>
    <fullName>Enable_Session_Registrations__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enable Session Registrations after Event order Booking is successfull</description>
    <inlineHelpText>Enable Session Registrations</inlineHelpText>
    <label>Enable Session Registrations</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Product__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Product__c/fields/Is_Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Is_Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to identify whether the &apos;Allow Primary Session&apos; should be a mandatory field in the event registration form</description>
    <inlineHelpText>Please check if you want &apos;Allow Primary Session&apos; to be a mandatory field in the event registration form.</inlineHelpText>
    <label>Is Mandatory?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <displayFormat>REG-{0000000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/fields/Cancellation_Description__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Description__c</fullName>
    <description>This field is used to describe the reason for cancellation of ticket from web form</description>
    <inlineHelpText>Please give a description for cancelling this registration</inlineHelpText>
    <label>Cancellation Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <description>This field is used to determine the ticket cancellation reason from the web form</description>
    <inlineHelpText>Please choose the appropriate reason for the cancellation of this registration</inlineHelpText>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Provided</fullName>
            </value>
            <value>
                <fullName>Event no longer relevant</fullName>
            </value>
            <value>
                <fullName>Cannot make the date</fullName>
            </value>
            <value>
                <fullName>Too far to travel</fullName>
            </value>
            <value>
                <fullName>Do not want to say</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Date Conflict</fullName>
                <isActive>false</isActive>
                <label>Date Conflict</label>
            </value>
            <value>
                <fullName>Event Not Relevant</fullName>
                <isActive>false</isActive>
                <label>Event Not Relevant</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Event_Email__c.field-meta.xml
<CustomField>
    <fullName>Event_Email__c</fullName>
    <label>Event Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Event_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Event_Mobile__c</fullName>
    <description>This field is used to store event attendee mobile number</description>
    <inlineHelpText>This field will be populated using ticket management web form</inlineHelpText>
    <label>Event Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Event_Order__c.field-meta.xml
<CustomField>
    <fullName>Event_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Order</label>
    <referenceTo>Event_Order__c</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Event_Product__c.field-meta.xml
<CustomField>
    <fullName>Event_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Product</label>
    <referenceTo>Event_Product__c</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Event_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration_Status__c</fullName>
    <description>Event Registration Status</description>
    <inlineHelpText>Event Registration Status</inlineHelpText>
    <label>Event Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Attended / Checked In</fullName>
            </value>
            <value>
                <fullName>Attended / Checked Out</fullName>
            </value>
            <value>
                <fullName>Did Not Attend</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/QR_Code__c.field-meta.xml
<CustomField>
    <fullName>QR_Code__c</fullName>
    <description>Event Registration QR Code</description>
    <inlineHelpText>Event Registration QR Code</inlineHelpText>
    <label>QR Code</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Registration_Type__c</fullName>
    <label>Registration Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Complementary - Speaker</fullName>
            </value>
            <value>
                <fullName>Complementary - Vendor</fullName>
            </value>
            <value>
                <fullName>Complementary - Prospect</fullName>
            </value>
            <value>
                <fullName>Complementary - Media</fullName>
            </value>
            <value>
                <fullName>Myself</fullName>
            </value>
            <value>
                <fullName>Someone Else</fullName>
            </value>
            <value>
                <fullName>Unknown Guest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Web_Site_Submission__c/Web_Site_Submission__c.object-meta.xml
<CustomObject>
    <description>This is object is used to store values from website forms and distribute the record values to other respective objects.</description>
    <label>Web Site Submission</label>
    <nameField>
        <label>Web Site Submissions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Web Site Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Web_Site_Submission__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>This field is used to store Email address given in the Web Form when it  is submitted.</description>
    <inlineHelpText>This field is auto populated when this Web Site Submission record is created.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/ct_TicketManagementController.cls
/**
 * @description       : 
 * @author            : Creation Admin
 * @group             : 
 * @last modified on  : 02-04-2021
 * @last modified by  : Creation Admin
 * Modifications Log 
 * Ver   Date         Author           Modification
 * 1.0   08-18-2020   Creation Admin   Initial Version
 * Controller class Ticket Management Form
**/
global without sharing class ct_TicketManagementController {
    
  /**
  * @description - Used to return the Event reg records  
  * @param String eventRegistrationId - Event Registration Record Id
  * @return TicketWrapper - return the TicketWrapper class
  **/
  @AuraEnabled
  global static TicketWrapper getEventRegistration(String eventRegistrationId){
    // Query the Event Registration Record based on Id
    return new TicketWrapper([SELECT Id, Name, Event__c, QR_Code__c, Event__r.Web_Event_Name__c,Event__r.Allow_Duplicate_Event_Registrations__c, Event__r.Event_Start_Date__c, Event__r.Event_End_Date__c, Event_Registration_Status__c, Event_Order__r.Name, Event_Mobile__c, 
                    Event_Product__r.Name,Event_Product__r.Allow_Primary_Session__c,Event_Product__r.Is_Mandatory__c, Registration_Type__c, First_Name__c, Last_Name__c, Event_Email__c, Event_Product__r.Enable_Session_Registrations__c,
                    Cancellation_Reason__c, Cancellation_Description__c
                    FROM Event_Registration__c WHERE Id =: eventRegistrationId LIMIT 1]);
  }

  /**
  * @description - Method to update the Event Registration record
\  * @param String jsonData - Ticket Management Data
  * @param String campaignData - Campaign member data
  * @param Boolean isCancelling - indicate the order is cancelled or not
  * @return String - return success message 
  **/
  @AuraEnabled
  global static String updateEventRegistration(String jsonData, String campaignData, Boolean isCancelling){
    try {

    Event_Registration__c thisEventRegistration = new Event_Registration__c();
    TicketWrapper thisTicketWrapper = (TicketWrapper)JSON.deserialize(jsonData,TicketWrapper.class);
    thisEventRegistration = thisTicketWrapper.eventRegistration;
    System.debug('thisEventRegistration>>>>'+thisEventRegistration);
    if(String.isNotBlank(thisEventRegistration.Registration_Type__c) && thisEventRegistration.Registration_Type__c == ct_EventConstants.EVENT_REGISTRATION_TYPE_UNKNOWN_GUEST){
      thisEventRegistration.Registration_Type__c = ct_EventConstants.EVENT_REGISTRATION_TYPE_SOMEONE_ELSE;
    }
    if(isCancelling){
      thisEventRegistration.Event_Registration_Status__c = 'Cancelled';
      System.debug('thisEventRegistration.Event_Registration_Status__c>>>>'+thisEventRegistration.Event_Registration_Status__c);
  
    }
    if(campaignData != null){
      Web_Site_Submission__c thisSubmission = getWebSiteSubmission(campaignData, thisEventRegistration);
      upsert thisSubmission; 
    }
    
      update thisEventRegistration;
      System.debug('thisEventRegistration>>>>'+thisEventRegistration);
    } catch (Exception ex) {
      ct_Logger.logMessage(ex, 'Event Registration');
      throw new AuraHandledException('Error '+ ex.getMessage() + ex.getLineNUmber());
    }
    
    return 'success';
  }

  /**
  * @description - method to get the exisiting Web site submission record
  * @param String campaignData - Campaign member data
  * @param Event_Registration__c thisRegistration - event registration record
  * @return Web_Site_Submission__c 
  **/
  global static Web_Site_Submission__c getWebSiteSubmission(String campaignData, Event_Registration__c thisRegistration){
    List<Web_Site_Submission__c> thisSubmission = new List<Web_Site_Submission__c>();
    thisSubmission = [SELECT Id, Name, Source__c, Email__c, Payload__c FROM Web_Site_Submission__c WHERE Name =: thisRegistration.Id LIMIT 1];
    if(!thisSubmission.isEmpty()){
      thisSubmission[0].Payload__c = campaignData;
    }
    else{
      Web_Site_Submission__c thisnewSubmission = new Web_Site_Submission__c();
      thisnewSubmission.Name                   = String.valueOf(Id.valueOf(thisRegistration.Id)).substring(0, 15);
      thisnewSubmission.Source__c				      = ct_EventConstants.WEB_SUBMISSION_SOURCE_EVENT;
      thisnewSubmission.Email__c               = thisRegistration.Event_Email__c;
      thisnewSubmission.Payload__c             = campaignData;
      thisSubmission.add(thisnewSubmission);
    }
    return thisSubmission[0];
  }
  // Wrapper class for sending event registration records
  global class TicketWrapper{
    @AuraEnabled 
    global Event_Registration__c eventRegistration { get;set; }
    //global List<String> primarySessionIds;
    global TicketWrapper(Event_Registration__c thisEventReg){
      this.eventRegistration = thisEventReg;
      //this.primarySessionIds = new List<String>();
    }
  }
}