force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <displayFormat>REG-{0000000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/fields/QR_Code__c.field-meta.xml
<CustomField>
    <fullName>QR_Code__c</fullName>
    <description>Event Registration QR Code</description>
    <inlineHelpText>Event Registration QR Code</inlineHelpText>
    <label>QR Code</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/Session_Registration__c.object-meta.xml
<CustomObject>
    <label>Session Registration</label>
    <nameField>
        <displayFormat>SAR - {00000}</displayFormat>
        <label>Session Registration Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Registration__c/fields/Event_Registration__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Registration</label>
    <referenceTo>Event_Registration__c</referenceTo>
    <relationshipName>Session_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/fields/QR_Code__c.field-meta.xml
<CustomField>
    <fullName>QR_Code__c</fullName>
    <description>Session Registration QR Code</description>
    <inlineHelpText>Session Registration QR Code</inlineHelpText>
    <label>QR Code</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/ct_SessionRegistrationTriggerHelper.cls
/**
 * @description       : Helper class for Session Registration TDTM trigger Handler
 * @author            : Creation Admin
 * @group             : 
 * @last modified on  : 12-07-2020
 * @last modified by  : Creation Admin
 * Modifications Log 
 * Ver   Date         Author           Modification
 * 1.0   12-07-2020   Creation Admin   Initial Version
**/
global without sharing class ct_SessionRegistrationTriggerHelper {
  
    /**
    * @description Method to get Event registration record
    * @param eventRegistrationIds Event registration record IDS
    * @return Map<Id, Event_Registration__c> 
    **/
    global static Map<Id, Event_Registration__c> getEventRegistrationMap(Set<Id> eventRegistrationIds){
        Map<Id, Event_Registration__c> eventRegistrationMap = new Map<Id, Event_Registration__c>([SELECT Id, 
                                                                                                        Name, 
                                                                                                        QR_Code__c 
                                                                                                    FROM Event_Registration__c 
                                                                                                    WHERE Id =: eventRegistrationIds]);
        return eventRegistrationMap;
    }

    /**
    * @description Method to update the QR code from event registration
    * @param thisSessionRegistration Session registration
    * @param eventRegistration Event registration from which QR need to populated from
    **/
    global static void populateQRCodeFromEventRegistration(Session_Registration__c thisSessionRegistration, Event_Registration__c eventRegistration){
        if(eventRegistration != null){
            thisSessionRegistration.QR_Code__c = eventRegistration.QR_Code__c;
        }
    }
}