force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <displayFormat>REG-{0000000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/fields/QR_Code__c.field-meta.xml
<CustomField>
    <fullName>QR_Code__c</fullName>
    <description>Event Registration QR Code</description>
    <inlineHelpText>Event Registration QR Code</inlineHelpText>
    <label>QR Code</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/Session_Registration__c.object-meta.xml
<CustomObject>
    <label>Session Registration</label>
    <nameField>
        <displayFormat>SAR - {00000}</displayFormat>
        <label>Session Registration Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Registration__c/fields/Event_Registration__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Registration</label>
    <referenceTo>Event_Registration__c</referenceTo>
    <relationshipName>Session_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/fields/QR_Code__c.field-meta.xml
<CustomField>
    <fullName>QR_Code__c</fullName>
    <description>Session Registration QR Code</description>
    <inlineHelpText>Session Registration QR Code</inlineHelpText>
    <label>QR Code</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/ct_SessionRegistrationHandler.cls
/**
 * @description       : Trigger Handler for Session Registration
 * @author            : Creation Admin
**/
global without sharing class ct_SessionRegistrationHandler /*extends hed.TDTM_Runnable*/{
	// global override hed.TDTM_Runnable.DmlWrapper run(List<SObject> newlist, List<SObject> oldlist,
    // hed.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult){
        
		// System.debug('>>>>>>>>>>>>>>>>>>>>>>>>>>>CT SESSION REGISTRATION TDTM TRIGGER HANDLER<<<<<<<<<<<<<<<<<<<<<<<<<<<');

		// hed.TDTM_Runnable.dmlWrapper dmlWrapper = new hed.TDTM_Runnable.DmlWrapper();

        
        // if (triggerAction == hed.TDTM_Runnable.Action.BeforeInsert)
        global static void handleBeforeInsert(List<Session_Registration__c>newlist){

            Set<Id> eventRegistrationIds = new Set<Id>();
            Map<Id, Event_Registration__c> eventRegistrationMap = new Map<Id, Event_Registration__c>();

            System.debug('>>>>>>>>>>>>>>>>>>>>>>>>>>>SESSION REGISTRATION BEFORE INSERT TRIGGER<<<<<<<<<<<<<<<<<<<<<<<<<<<');
            for (Session_Registration__c thisSessionRegistration : (list<Session_Registration__c>)newlist){
                if(thisSessionRegistration.Event_Registration__c != null){
                    eventRegistrationIds.add(thisSessionRegistration.Event_Registration__c);
                }
            }

            if(!eventRegistrationIds.isEmpty()){
                eventRegistrationMap = ct_SessionRegistrationTriggerHelper.getEventRegistrationMap(eventRegistrationIds);
            }

            for (Session_Registration__c thisSessionRegistration : (list<Session_Registration__c>)newlist){
                if(thisSessionRegistration.Event_Registration__c != null
                    && thisSessionRegistration.QR_Code__c == null
                    && !eventRegistrationMap.isEmpty()
                    && eventRegistrationMap.containsKey(thisSessionRegistration.Event_Registration__c)){
                    ct_SessionRegistrationTriggerHelper.populateQRCodeFromEventRegistration(thisSessionRegistration, eventRegistrationMap.get(thisSessionRegistration.Event_Registration__c));
                }
            }
        }
        // return dmlWrapper;                                            
    // }
}