force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Track__c.field-meta.xml
<CustomField>
    <fullName>Track__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Track</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Track__c.Event__c</field>
            <operation>equals</operation>
            <valueField>$Source.Event__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Track__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Track__c/Track__c.object-meta.xml
<CustomObject>
    <label>Track</label>
    <nameField>
        <label>Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ct_SessionTriggerHandler.cls
/**
 * @description       : Trigger Handler for Session Trigger
 * @author            : Creation Admin
**/
global without sharing class ct_SessionTriggerHandler {
	// global override hed.TDTM_Runnable.DmlWrapper run(List<SObject> newlist, List<SObject> oldlist,
    // hed.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult){
        
	// 	System.debug('>>>>>>>>>>>>>>>>>>>>>>>>>>>CT SESSION TDTM TRIGGER HANDLER<<<<<<<<<<<<<<<<<<<<<<<<<<<');

	// 	hed.TDTM_Runnable.dmlWrapper dmlWrapper = new hed.TDTM_Runnable.DmlWrapper();

        global static Set<Id> setOfTrackIdsToUpdate = new Set<Id>();
        
        // if (triggerAction == hed.TDTM_Runnable.Action.BeforeInsert){

        global static void handleBeforeInsert(List<Session__c> newlist){
            ct_SessionTriggerHandlerHelper.updateSession(newlist);      
        }
        
        // if (triggerAction == hed.TDTM_Runnable.Action.AfterInsert){

        global static void handleAfterInsert(List<Session__c> newlist){
            System.debug('>>>>>>>>>>>>>>>>>>>>>>>>>>>SESSION AFTER INSERT TRIGGER<<<<<<<<<<<<<<<<<<<<<<<<<<<');
            for (Session__c thisSession : newlist){
                if(thisSession.Track__c != null){
                    setOfTrackIdsToUpdate.add(thisSession.Track__c);
                }
            }
            updateSessionCountOnTrack(setOfTrackIdsToUpdate);
        }

        // if (triggerAction == hed.TDTM_Runnable.Action.BeforeUpdate){

        global static void handleBeforeUpdate(List<Session__c> newlist){
            ct_SessionTriggerHandlerHelper.updateSession(newlist);
        }
        
        // if (triggerAction == hed.TDTM_Runnable.Action.AfterUpdate){

        global static void handleAfterUpdate(Map<Id, Session__c> triggerOldMap, Map<Id, Session__c> triggerNewMap){
            // System.debug('>>>>>>>>>>>>>>>>>>>>>>>>>>>SESSION AFTER UPDATE TRIGGER<<<<<<<<<<<<<<<<<<<<<<<<<<<');
            // Map<Id, Session__c> triggerOldMap = new Map<Id, Session__c>((list<Session__c>)oldlist);
            // Map<Id, Session__c> triggerNewMap = new Map<Id, Session__c>((list<Session__c>)newlist);

            for (Session__c thisSession : triggerNewMap.values()){
                if(thisSession.Track__c != triggerOldMap.get(thisSession.Id).Track__c){
                    if(thisSession.Track__c != null){
                        setOfTrackIdsToUpdate.add(thisSession.Track__c);
                    }
                    if(triggerOldMap.get(thisSession.Id).Track__c != null){
                        setOfTrackIdsToUpdate.add(triggerOldMap.get(thisSession.Id).Track__c);
                    }
                }
            }
            updateSessionCountOnTrack(setOfTrackIdsToUpdate);
        }

        // if (triggerAction == hed.TDTM_Runnable.Action.BeforeDelete) {

        global static void handleBeforeDelete(List<Session__c> oldlist){
            System.debug('>>>>>>>>>>>>>>>>>>>>>>>>>>>SESSION BEFORE DELETE TRIGGER<<<<<<<<<<<<<<<<<<<<<<<<<<<');
            for (Session__c thisSession : (oldlist)){
                if(thisSession.Track__c != null){
                    setOfTrackIdsToUpdate.add(thisSession.Track__c);
                }
            }
            
            updateSessionCountOnTrack(setOfTrackIdsToUpdate);
        }

        global static void updateSessionCountOnTrack(Set<Id> setOfTrackIdsToUpdate){
        if(!setOfTrackIdsToUpdate.isEmpty() && !System.isFuture() && !System.isBatch()){
            ct_SessionTriggerHandlerHelper.updateSessionCountOnTrack(setOfTrackIdsToUpdate);
        }

    }
}