force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Enable_Waiting_List_on_Closed__c.field-meta.xml
<CustomField>
    <fullName>Enable_Waiting_List_on_Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Waiting List on Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Final_Booking_Date__c.field-meta.xml
<CustomField>
    <fullName>Final_Booking_Date__c</fullName>
    <description>This field is used to determine the final booking date for this registration</description>
    <inlineHelpText>Please choose a valid date</inlineHelpText>
    <label>Final Booking Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Registration_Closed__c.field-meta.xml
<CustomField>
    <fullName>Registration_Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to determine whether the registration is closed or not</description>
    <inlineHelpText>Please check if you want to close this registration</inlineHelpText>
    <label>Registration Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_End_Date__c</fullName>
    <description>This field is used to record the session end date</description>
    <inlineHelpText>Please choose an appropriate end date for this session</inlineHelpText>
    <label>Session End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Track__c.field-meta.xml
<CustomField>
    <fullName>Track__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Track</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Track__c.Event__c</field>
            <operation>equals</operation>
            <valueField>$Source.Event__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Track__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Waiting_List_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Waiting_List_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Waiting List Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Track__c/Track__c.object-meta.xml
<CustomObject>
    <label>Track</label>
    <nameField>
        <label>Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/fields/Number_of_Related_Sessions__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Related_Sessions__c</fullName>
    <description>This is a system generated field</description>
    <inlineHelpText>This is a system generated field</inlineHelpText>
    <label>Number of Related Sessions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ct_SessionTriggerHandlerHelper.cls
/**
 * @description       : 
 * @author            : Creation Admin
 * @group             : 
 * @last modified on  : 02-04-2021
 * @last modified by  : Creation Admin
 * Modifications Log 
 * Ver   Date         Author           Modification
 * 1.0   10-14-2020   Creation Admin   Initial Version
 * Helper class for Session Trigger Handler
**/
global without sharing class ct_SessionTriggerHandlerHelper {

	/**
	* @description - Used to update the Number of related sessions under the Track
	* @param Set<Id> setOfTrackIds - Track record Ids
	**/
	@future
	global static void updateSessionCountOnTrack(Set<Id> setOfTrackIds){
		Map<Id, AggregateResult> thisAggResultMap = new Map<Id, AggregateResult>([SELECT Track__c Id, COUNT(Id) thisCount FROM Session__c WHERE Track__c IN :setOfTrackIds GROUP BY Track__c]);
		Map<Id, Track__c> trackMapToUpdate = new Map<Id, Track__c>([SELECT Id, Number_of_Related_Sessions__c FROM Track__c WHERE Id =:setOfTrackIds]);
		try{
			if(!trackMapToUpdate.isEmpty()){
				for(Track__c thisTrack : trackMapToUpdate.values()){
					thisTrack.Number_of_Related_Sessions__c = 0;
					if( !thisAggResultMap.isEmpty()
						&& thisAggResultMap.containsKey(thisTrack.Id)){
						thisTrack.Number_of_Related_Sessions__c = (Integer)thisAggResultMap.get(thisTrack.Id).get('thisCount');
					}
				}
				update trackMapToUpdate.values();
			}
		}
		catch(Exception e){
			//Exception mechanism to log any exceptions occured during the dml operation
			ct_Logger.logMessage(e, 'Update Number of Session field on Track');
			throw new AuraHandledException('Error '+ e.getMessage());    
		}
	}
	/**
	* @description used to update the Session record with Booking date
	* @param list<Session__c> sessionList 
	**/
	global static void updateSession(list<Session__c> sessionList){
			for(Session__c thisSession : sessionList){
		if(!thisSession.Waiting_List_Enabled__c
								&& thisSession.Registration_Closed__c && thisSession.Enable_Waiting_List_on_Closed__c && thisSession.Final_Booking_Date__c>System.today()){
									thisSession.Waiting_List_Enabled__c = true;
		}
		if(thisSession.Final_Booking_Date__c == null && thisSession.Session_End_Date__c != null){
			thisSession.Final_Booking_Date__c = thisSession.Session_End_Date__c;
		}
			}
	}
}