force-app/main/default/objects/CampaignMember/fields/Event_Registration__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the Event Registration for the associated Campaign</description>
    <label>Event Registration</label>
    <referenceTo>Event_Registration__c</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Business_Area__c.field-meta.xml
<CustomField>
    <fullName>Business_Area__c</fullName>
    <label>Business Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MBA</fullName>
            </value>
            <value>
                <fullName>Executive Degrees</fullName>
            </value>
            <value>
                <fullName>Executive Diplomas</fullName>
            </value>
            <value>
                <fullName>On-Campus Open Programmes</fullName>
            </value>
            <value>
                <fullName>Open Online Programmes</fullName>
            </value>
            <value>
                <fullName>Custom Programmes</fullName>
            </value>
            <value>
                <fullName>Student Marketing</fullName>
            </value>
            <value>
                <fullName>Student Services</fullName>
            </value>
            <value>
                <fullName>Alumni &amp; Advancement</fullName>
            </value>
            <value>
                <fullName>Business Services</fullName>
            </value>
            <value>
                <fullName>Marketing &amp; Communications</fullName>
                <isActive>false</isActive>
                <label>Marketing &amp; Communications</label>
            </value>
            <value>
                <fullName>Marketing (RAO)</fullName>
                <isActive>false</isActive>
                <label>Marketing (RAO)</label>
            </value>
            <value>
                <fullName>Marketing (Student Recruitment)</fullName>
                <isActive>false</isActive>
                <label>Marketing (Student Recruitment)</label>
            </value>
            <value>
                <fullName>R&amp;I / B2B</fullName>
                <isActive>false</isActive>
                <label>R&amp;I / B2B</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/CM_ER_Auto_Sync__c.field-meta.xml
<CustomField>
    <fullName>CM_ER_Auto_Sync__c</fullName>
    <description>Should Sync Campaign Member and Event Registration</description>
    <inlineHelpText>Should Sync Campaign Member and Event Registration</inlineHelpText>
    <label>CM / ER Auto Sync</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Status__c</fullName>
    <label>Event Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Pre-Event</fullName>
            </value>
            <value>
                <fullName>Check In / Management</fullName>
            </value>
            <value>
                <fullName>Post Event</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Business_Area__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Open Day</fullName>
            </value>
            <value>
                <fullName>Virtual Helpdesk</fullName>
            </value>
            <value>
                <fullName>In Conversation With</fullName>
            </value>
            <value>
                <fullName>Applicant Experience Day</fullName>
            </value>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>Partner Event</fullName>
            </value>
            <value>
                <fullName>Graduation Event</fullName>
            </value>
            <value>
                <fullName>PG Student Event</fullName>
            </value>
            <value>
                <fullName>Alumni Networking</fullName>
            </value>
            <value>
                <fullName>Alumni Dinner</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Post_Event_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Post_Event_Approval_Status__c</fullName>
    <description>Post Event Approval status</description>
    <inlineHelpText>Post Event Approval status</inlineHelpText>
    <label>Post Event Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted for Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approval Required</fullName>
                <isActive>false</isActive>
                <label>Approval Required</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Post_Web_Order_Action__c.field-meta.xml
<CustomField>
    <fullName>Post_Web_Order_Action__c</fullName>
    <label>Post Web Order Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Order Confirmation Screen</fullName>
                <default>true</default>
                <label>Order Confirmation Screen</label>
            </value>
            <value>
                <fullName>Redirect to URL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/recordTypes/Complex_Events.recordType-meta.xml
<RecordType>
    <fullName>Complex_Events</fullName>
    <active>true</active>
    <label>Complex Events</label>
</RecordType>

force-app/main/default/objects/Event__c/recordTypes/Simple_Events.recordType-meta.xml
<RecordType>
    <fullName>Simple_Events</fullName>
    <active>true</active>
    <label>Simple Events</label>
</RecordType>

force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <displayFormat>REG-{0000000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/fields/Cancellation_Reason__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Reason__c</fullName>
    <description>This field is used to determine the ticket cancellation reason from the web form</description>
    <inlineHelpText>Please choose the appropriate reason for the cancellation of this registration</inlineHelpText>
    <label>Cancellation Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Provided</fullName>
            </value>
            <value>
                <fullName>Event no longer relevant</fullName>
            </value>
            <value>
                <fullName>Cannot make the date</fullName>
            </value>
            <value>
                <fullName>Too far to travel</fullName>
            </value>
            <value>
                <fullName>Do not want to say</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Date Conflict</fullName>
                <isActive>false</isActive>
                <label>Date Conflict</label>
            </value>
            <value>
                <fullName>Event Not Relevant</fullName>
                <isActive>false</isActive>
                <label>Event Not Relevant</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/recordTypes/Master_Event_Registration.recordType-meta.xml
<RecordType>
    <fullName>Master_Event_Registration</fullName>
    <active>true</active>
    <description>This record type for the Master Events</description>
    <label>Master Event Registration</label>
</RecordType>

force-app/main/default/classes/ct_EventConstants.cls
/**
* @description       : Class which stores the global constants which are used for Events 
* @author            : Creation Admin
* @last modified on  : 02-04-2021
* @last modified by  : Creation Admin
* Modifications Log 
* Ver   Date         Author           Modification
* 1.0   09-25-2020   Creation Admin   Initial Version
**/
global without sharing class ct_EventConstants {
    //Event Question Set
    global static final String EVENT_QUESTION_SET_STATUS_ACTIVE = 'Active';
    
    //EVENT QUESTION 
    global static final String QUESTION_DATA_TYPE_TEXT                    = 'Text';
    global static final String QUESTION_DATA_TYPE_CURRENCY                = 'Currency';
    global static final String QUESTION_DATA_TYPE_LONG_TEXT               = 'Long Text Area';
    global static final String QUESTION_DATA_TYPE_PICKLIST                = 'Picklist';
    global static final String QUESTION_DATA_TYPE_RICH_TEXT               = 'Rich Text Area';
    global static final String QUESTION_DATA_TYPE_TEXT_AREA               = 'Text Area';
    global static final String QUESTION_DATA_TYPE_TEXT_DEPENDENT_PICKLIST = 'Dependent Picklist';
    
    global static final String QUESTION_OBJECT_TYPE_CAMPAIGN_MEMBER    = 'CampaignMember';
    global static final String QUESTION_OBJECT_TYPE_EVENT_REGISTRATION = 'Event_Registration__c';
    global static final String WEB_SUBMISSION_SOURCE_EVENT             = 'Event';
    
    //Event
    global static final String EVENT_PUBLISHING_WEBSITE_AND_REGISTRATION_PAGE = 'Event Website & Registration Page';
    global static final String EVENT_PUBLISHING_REGISTRATION_PAGE             = 'Event Registration Page Only';
    global static final String NO_EVENT_PUBLISH                               = 'No Event Registration Page';
    
    // Event Post_Web_Order_Action__c
    global static final String EVENT_POST_WEB_ORDER_ACTION_CONFIRMATION_SCREEN = 'Order Confirmation Screen';
    
    // Event Business_Area__c
    global static final String EVENT_BUSINESS_AREA_STUDENT_RECRUITMENT = 'Marketing (Student Recruitment)';
    
    //Event Event_Type__c
    global static final String EVENT_TYPE_OPEN_DAY = 'Open Day';
    //Event CM_ER_Auto_Sync__c  
    global static final String EVENT_CM_ER_AUTO_SYNC_YES = 'Yes';
    global static final String EVENT_CM_ER_AUTO_SYNC_NO = 'NO';
    
    
    //Event Post_Event_Approval_Status__c
    global static final String EVENT_POST_EVENT_APPROVAL_STATUS = 'Approval Required';
    
    
    //Event Event_Status__c
    global static final String EVENT_STATUS_PLANNING = 'Planning';
    global static final String EVENT_STATUS_POST_EVENT = 'Post Event';
    global static final String EVENT_STATUS_NEW = 'New';
    global static final String EVENT_STATUS_CHECK_IN_MANAGEMENT = 'Check In / Management';
    
    //Event Product 
    
    //Event Product  Event_Product_Type__c
    global static final String EVENT_PRODUCT_TYPE_EVENT_TICKET = 'Event Ticket';
    
    
    
    //Event Order
    global static final String ORDER_SOURCE_INTERNAL_ORDER = 'Internal Order';
    global static final String ORDER_SOURCE_WEB_ORDER      = 'Web Order';
    global static final String ORDER_STATUS_ACTIVE         = 'Active';
    global static final String CREATE_NEW_LEADS             = 'Create New Leads';
    global static final String CREATE_NEW_CONTACTS          = 'Create New Contacts';
    global static final String CREATE_NEW_PERSON_ACCOUNTS   = 'Create New Person Accounts';
    
    
    //Event Registration

    global static final String SIMPLE_EVENT_RECORD_TYPE_DEVELOPER_NAME = 'Simple_Events';
    global static final Id SIMPLE_EVENT_RECORD_TYPE_ID           = ct_Util.getRecordTypeIdByDevName('Event__c', SIMPLE_EVENT_RECORD_TYPE_DEVELOPER_NAME);

    global static final String COMPLEX_EVENT_RECORD_TYPE_DEVELOPER_NAME = 'Complex_Events';
    global static final Id COMPLEX_EVENT_RECORD_TYPE_ID           = ct_Util.getRecordTypeIdByDevName('Event__c', COMPLEX_EVENT_RECORD_TYPE_DEVELOPER_NAME);

    global static final String MASTER_EVENT_REGISTRATION_RECORD_TYPE_DEVELOPER_NAME = 'Master_Event_Registration';
    global static final Id EVENT_REGISTRATION_MASTER_EVENT_RECORD_TYPE_ID           = ct_Util.getRecordTypeIdByDevName('Event_Registration__c', MASTER_EVENT_REGISTRATION_RECORD_TYPE_DEVELOPER_NAME);
    global static final String EVENT_REGISTRATION_CHECKED_IN                        = 'Attended / Checked In';
    global static final String EVENT_REGISTRATION_CHECKED_OUT                       = 'Attended / Checked Out';
    global static final String EVENT_REGISTRATION_REGISTERED                        = 'Registered';
    global static final String EVENT_REGISTRATION_ATTENDING                         = 'Attending';
    global static final String EVENT_REGISTRATION_CANCELLED                         = 'Cancelled';
    global static final String EVENT_REGISTRATION_NEW                               = 'New';
    global static final String EVENT_REGISTRATION_INVITED                           = 'Invited';
    global static final String EVENT_REGISTRATION_DECLINED                          = 'Declined';
    global static final String EVENT_REGISTRATION_DID_NOT_ATTEND                    = 'Did Not Attend';
    
    global static final String EVENT_REGISTRATION_SOURCE_INTERNAL_ORDER  = 'Internal Order';
    global static final String EVENT_REGISTRATION_SOURCE_WEB_ORDER       = 'Web Order';
    global static final String EVENT_REGISTRATION_SOURCE_MANUAL_CREATION = 'Manual Creation';
    global static final String EVENT_REGISTRATION_TYPE_GUEST             = 'Guest';
    global static final String EVENT_REGISTRATION_TYPE_NAMED_ATTENDEE    = 'Named Attendee';
    global static final String EVENT_REGISTRATION_TYPE_MY_SELF           = 'Myself';
    global static final String EVENT_REGISTRATION_TYPE_SOMEONE_ELSE      = 'Someone Else';
    global static final String EVENT_REGISTRATION_TYPE_UNKNOWN_GUEST     = 'Unknown Guest';
    
    //Event Order
    global static final String EVENT_ORDER_CANCELLED     = 'Cancelled';
    global static final String EVENT_ORDER_ACTIVE        = 'Active';
    global static final String EVENT_ORDER_WAITING_LIST  = 'Waiting List';
        
    //Event Order Cancellation_Reason__c
    global static final String EVENT_CANCEL_REASON_DATE_CONFLICT  = 'Date Conflict';
        
    //Session Registration
    global static final String SESSION_REGISTRATION_CANCELLED      = 'Cancelled';
    global static final String SESSION_REGISTRATION_REGISTERED     = 'Registered';
    global static final String SESSION_REGISTRATION_DID_NOT_ATTEND = 'Did Not Attend';
    global static final String SESSION_REGISTRATION_CHECKED_IN     = 'Attended / Checked In';
    global static final String SESSION_REGISTRATION_CHECKED_OUT    = 'Attended / Checked Out';
    
    //Event Check In Manager Constants
    global static final String EVENT_CHECK_IN_STATUS_REGISTERED     = 'REGISTERED';
    global static final String EVENT_CHECK_IN_STATUS_CHECKED_IN     = 'CHECKED_IN';
    global static final String EVENT_CHECK_IN_STATUS_CHECKED_OUT    = 'CHECKED_OUT';
    global static final String EVENT_CHECK_IN_STATUS_DID_NOT_ATTEND = 'DID_NOT_ATTEND';
    
    //Custom Label
    global static final String CHECK_IN_MANAGER_URL = System.Label.Check_In_Manager_URL;
    global static final String SITE_BASE_URL = System.Label.Site_Base_URL;
    
    //Base URL
    global static final String BASE_URL = URL.getOrgDomainUrl().toExternalForm();

    //Discount Code
    global static final String DISCOUNT_TYPE_PERCENTAGE = 'Discount Code %';
    global static final String DISCOUNT_TYPE_AMOUNT = 'Discount Code Amount';
    
    //CampaignMember Status
    global static final String CAMPAIGN_MEMBER_STATUS_CHECKED_IN     = 'Attended / Checked In';
    global static final String CAMPAIGN_MEMBER_STATUS_CHECKED_OUT    = 'Attended / Checked Out';
    global static final String CAMPAIGN_MEMBER_STATUS_REGISTERED     = 'Registered';
    global static final String CAMPAIGN_MEMBER_STATUS_ATTENDING      = 'Attending';
    global static final String CAMPAIGN_MEMBER_STATUS_CANCELLED      = 'Cancelled';
    global static final String CAMPAIGN_MEMBER_STATUS_NEW            = 'New';
    global static final String CAMPAIGN_MEMBER_STATUS_INVITED        = 'Invited';
    global static final String CAMPAIGN_MEMBER_STATUS_DECLINED       = 'Declined';
    global static final String CAMPAIGN_MEMBER_STATUS_DID_NOT_ATTEND = 'Did Not Attend';
    
    //Event Setting Metadata
    global static final String EVENT_SUCCESS_MESSAGE_EVENT_SETTING = 'Event_Success_Message';
    
    //Event Ticket registration Contact And Enquire Consent functionality
    
    global static final String CONSENT_VALUE_YES = 'Yes';
    global static final String CONSENT_VALUE_NO = 'No';
    
    
    global static final String CONSENT_GIVEN_YES = 'Yes';
    global static final String CONSENT_GIVEN_NO = 'No';
    
    
    global static final String STUDENT_RECRUITMENT_AND_RAO_CONSENT_STATEMENT = 'Student Recruitment & RAO';
    global static final String R_AND_I_B2B_CONSENT_STATEMENT                 = 'R&I / B2B';
    global static final String ALUMNI_AND_ADVANCEMENT_CONSENT_STATEMENT      = 'Alumni & Advancement';
    
    global static final String LATEST_CONSENT_CHANGE_SOURCE_EVENT      = 'Event';
    
    //Event Manager Refund Alert EmAIL Template
    global static final string EVENT_MANAGER_REFUND_TEMPLATE = 'Event_Manager_Refund_Template';
    
    //Event Manager Refund Metadata Record
    global static final string EVENT_MANAGER_REFUND_RECORD_DEVELOPER_NAME = 'Disable_Event_Manager_Refund';
    
    //Event Order Status
    global static final string EVENT_ORDER_STATUS_CANCELLED = 'Cancelled';
    
    //Event Org Wide Address
    global static final string EVENT_FROM_ADDRESS_NAME = 'Open Days';
    
    //B2B Public Group Constant
    global static final String B2B_PUBLIC_GROUP_NAME = 'UoP B2B Users';
}