force-app/main/default/objects/CampaignMember/fields/Event_Registration__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the Event Registration for the associated Campaign</description>
    <label>Event Registration</label>
    <referenceTo>Event_Registration__c</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Product__c/Event_Product__c.object-meta.xml
<CustomObject>
    <label>Event Product</label>
    <nameField>
        <label>Event Product	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Product__c/fields/Event_Question_Set__c.field-meta.xml
<CustomField>
    <fullName>Event_Question_Set__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is used to relate the question set for this event product</description>
    <inlineHelpText>Please choose an appropriate question set for this event product</inlineHelpText>
    <label>Event Question Set</label>
    <referenceTo>Event_Question_Set__c</referenceTo>
    <relationshipLabel>Event Products</relationshipLabel>
    <relationshipName>Event_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Product__c/fields/Is_Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Is_Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to identify whether the &apos;Allow Primary Session&apos; should be a mandatory field in the event registration form</description>
    <inlineHelpText>Please check if you want &apos;Allow Primary Session&apos; to be a mandatory field in the event registration form.</inlineHelpText>
    <label>Is Mandatory?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Question_Set__c/Event_Question_Set__c.object-meta.xml
<CustomObject>
    <label>Event Question Set</label>
    <nameField>
        <displayFormat>EQS-{0000}</displayFormat>
        <label>Question Set Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Question Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <displayFormat>REG-{0000000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/fields/Event_Product__c.field-meta.xml
<CustomField>
    <fullName>Event_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Product</label>
    <referenceTo>Event_Product__c</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Questions__c/Questions__c.object-meta.xml
<CustomObject>
    <label>Questions</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Questions__c/fields/Answer_Options__c.field-meta.xml
<CustomField>
    <fullName>Answer_Options__c</fullName>
    <description>This field is used to display answers as options if the data type is selected as Picklist</description>
    <inlineHelpText>Please enter each option in a new line when you choose either &quot;Picklist&quot; or &quot;Picklist with Radio Options&quot; as data type</inlineHelpText>
    <label>Answer Options</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Questions__c/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <description>This field is used to determine the data type for the answer entered in the web form</description>
    <inlineHelpText>Please choose the appropriate value based on the question value entered</inlineHelpText>
    <label>Data Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Text</fullName>
                <default>true</default>
                <label>Text Field (Max 255 Single Line)</label>
            </value>
            <value>
                <fullName>Text Area</fullName>
                <label>Text Area (Max 255 Multi Line)</label>
            </value>
            <value>
                <fullName>Long Text Area</fullName>
                <label>Long Text Area (Max 32,768)</label>
            </value>
            <value>
                <fullName>Rich Text Area</fullName>
                <label>Rich Text Area (Max 32,768)</label>
            </value>
            <value>
                <fullName>Number</fullName>
                <label>Number Field</label>
            </value>
            <value>
                <fullName>Currency</fullName>
                <label>Currency Field</label>
            </value>
            <value>
                <fullName>Date</fullName>
                <label>Date Field</label>
            </value>
            <value>
                <fullName>Phone</fullName>
                <label>Phone Field</label>
            </value>
            <value>
                <fullName>Picklist</fullName>
                <label>Picklist Field</label>
            </value>
            <value>
                <fullName>Picklist with Radio Options</fullName>
                <label>Picklist Field with Radio Options</label>
            </value>
            <value>
                <fullName>Dependent Picklist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Questions__c/fields/Default_Text__c.field-meta.xml
<CustomField>
    <fullName>Default_Text__c</fullName>
    <description>This field is used to populate the default answer for the Question in the webform.</description>
    <inlineHelpText>Please enter the default answer if you want to automatically default this answer in the web form. For Date use (YYYY-MM-DD) format.</inlineHelpText>
    <label>Default Answer</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Questions__c/fields/Dependent_Answer_is_Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Dependent_Answer_is_Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that the dependent answer is mandatory or not</description>
    <label>Dependent Answer is Mandatory?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Questions__c/fields/Dependent_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Dependent_Field_API_Name__c</fullName>
    <description>Used to store the API name of the Dependent picklist field</description>
    <inlineHelpText>Used to store the API name of the Dependent picklist field</inlineHelpText>
    <label>Dependent Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Questions__c/fields/Dependent_Field_Question__c.field-meta.xml
<CustomField>
    <fullName>Dependent_Field_Question__c</fullName>
    <description>Used to store the question of the dependent picklist field</description>
    <label>Dependent Field Question</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Questions__c/fields/Dependent_Question_Setup__c.field-meta.xml
<CustomField>
    <fullName>Dependent_Question_Setup__c</fullName>
    <description>Used to store the Dependent picklist values with respect to the controlling field value</description>
    <inlineHelpText>WARNING: This field must be configured by your Salesforce Administrator. Please contact LED team for more details</inlineHelpText>
    <label>Dependent Question Setup</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Questions__c/fields/Even_Registration_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Even_Registration_Field_API_Name__c</fullName>
    <description>This field is used to identify API Name of the field in Event Registration used map the answer given through the web form</description>
    <inlineHelpText>Please choose a appropriate field API from Event Registration object for this question</inlineHelpText>
    <label>Field API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Questions__c/fields/Event_Question_Set__c.field-meta.xml
<CustomField>
    <fullName>Event_Question_Set__c</fullName>
    <description>This field is to relate question record to Event Question Set record</description>
    <inlineHelpText>Please choose appropriate Event Question Set for this record</inlineHelpText>
    <label>Event Question Set</label>
    <referenceTo>Event_Question_Set__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Questions__c/fields/Hide_Question__c.field-meta.xml
<CustomField>
    <fullName>Hide_Question__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to hide questions from the webform.</description>
    <inlineHelpText>Please check if this Question needs to be hidden from the webform, any value entered in the &apos;Default Text&apos; field will be stored in the respective Event Registration/Campaign Member field.</inlineHelpText>
    <label>Hide Question</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Questions__c/fields/Is_Mandatory__c.field-meta.xml
<CustomField>
    <fullName>Is_Mandatory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is to determine whether the question should be a mandatory</description>
    <inlineHelpText>Please check if the question needs to be mandatory in the web form</inlineHelpText>
    <label>Is Mandatory?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Questions__c/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <description>When entering the values as
Picklist Value Label = Object Label
Picklist Value API Name = Object API Name</description>
    <label>Object</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Event_Registration__c</fullName>
                <label>Event Registration</label>
            </value>
            <value>
                <fullName>CampaignMember</fullName>
                <label>Campaign Member</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Questions__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>This field holds the question that needs to displayed in the web forms</description>
    <inlineHelpText>Please enter a appropriate question for related Event Question Set</inlineHelpText>
    <label>Question</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Questions__c/fields/Question_Order__c.field-meta.xml
<CustomField>
    <fullName>Question_Order__c</fullName>
    <description>This field is used to define the order of respective question displayed in the web forms</description>
    <inlineHelpText>Please enter a question order for this question</inlineHelpText>
    <label>Question Order</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Questions__c/fields/Show_Only_Text__c.field-meta.xml
<CustomField>
    <fullName>Show_Only_Text__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field used just to show a block of text instead of a Question in the webform</description>
    <inlineHelpText>Please check this if you just want to show text entered in the &apos;Default Text&apos; field</inlineHelpText>
    <label>Show Only Text</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Questions__c/fields/Text_To_Display__c.field-meta.xml
<CustomField>
    <fullName>Text_To_Display__c</fullName>
    <description>This field is used to show the content entered in the field as read only text in the web form.</description>
    <inlineHelpText>This field is used to show the content entered in the field as read only text in the web form.</inlineHelpText>
    <label>Text To Display</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/ct_EventQuestionsFormController.cls
/**
 * @description       : Contruct the wrapper to show the Event product related question sets in Event Registration UI
 * @author            : Creation Admin
 * @last modified on  : 01-20-2021
 * @last modified by  : Creation Admin
 * Modifications Log 
 * Ver   Date         Author           Modification
 * 1.0   08-20-2020   Creation Admin   Initial Version
**/
global without sharing class ct_EventQuestionsFormController {
  
  /**
  * @description 
  * @param String recordId - Event registration record or Event product record Id
  * @param String ticketName - Name of the ticket from web form
  * @return List<QuestionWrapper> 
  **/
  @AuraEnabled
  global static List<QuestionWrapper> getQuestionsForEventProduct(String recordId, String ticketName){
    //Variables to store and return the Question records
    String eventProductId;
    List<QuestionWrapper> questionWrapperList = new List<QuestionWrapper>();
    Event_Registration__c thisEventRegistration = new Event_Registration__c();
    List<CampaignMember> thisCampaignMemberList = new List<CampaignMember>();
    Map<String, String> eventRegFieldToValueMap = new  Map<String, String>();
    Map<String, String> campaignFieldToValueMap = new  Map<String, String>();

    Map<String, Integer> eventRegFieldLengthMap = new Map<String, Integer>();
    Map<String, Integer> campaignMemberFieldLengthMap = new Map<String, Integer>();
    // Sobject Type for Event Registration
    SObjectType sobType = Event_Registration__c.SObjectType;
    // Get all the fields related to the Event Registration
    List<String> fields = new List<String>(sobType.getDescribe().fields.getMap().keySet());
    populateFieldLengthMap(sobType, eventRegFieldLengthMap);
    // Sobject Type for Campaign member
    SObjectType campaignMemberSobjectType = CampaignMember.SObjectType;
    // Get all the fields related to the Capaign member
    List<String> campaignMemberfields = new List<String>(campaignMemberSobjectType.getDescribe().fields.getMap().keySet());
    populateFieldLengthMap(campaignMemberSobjectType, campaignMemberFieldLengthMap);

    //Query the related campaign member record related to the Event Registration Id
    String campaignMemberQueryString = 'SELECT '+String.join(campaignMemberfields, ',')+' FROM  CampaignMember WHERE Event_Registration__c =: recordId LIMIT 1';
    campaignMemberQueryString = campaignMemberQueryString.replace('RecordTypeId,', '');
    thisCampaignMemberList = Database.query(campaignMemberQueryString);

    //Query the related Event Registration record with respect to Id
    if(String.valueOf(Id.valueOf(recordId).getsobjecttype()) == 'Event_Registration__c'){
      String queryString = 'SELECT '+String.join(fields, ',')+' FROM  Event_Registration__c WHERE Id =: recordId LIMIT 1';
      thisEventRegistration = Database.query(queryString);

      for(String field : fields) {
        Object value = thisEventRegistration.get(field);
        if (value != null) eventRegFieldToValueMap.put(field, String.valueOf(value));   
      }
      for(String field : campaignMemberfields) {
        if(!thisCampaignMemberList.isEmpty() && thisCampaignMemberList[0] != null){
          Object campaignMemberValue = thisCampaignMemberList[0].get(field);
          if (campaignMemberValue != null) {
            campaignFieldToValueMap.put(field, String.valueOf(campaignMemberValue));
          }
        }
      }
      eventProductId = thisEventRegistration.Event_Product__c;
    }
    else{
      eventProductId = recordId;
    }
    // Query the related question records with respect to the Event product Id
    for(Questions__c thisQuestion : [SELECT Id, Name, Data_Type__c, Even_Registration_Field_API_Name__c, Event_Question_Set__c, Hide_Question__c,
                                            Is_Mandatory__c, Question__c, Answer_Options__c, Object__c, Default_Text__c, Show_Only_Text__c, Text_To_Display__c,
                                            Dependent_Field_API_Name__c, Dependent_Field_Question__c, Dependent_Question_Setup__c, Dependent_Answer_is_Mandatory__c
                                            FROM Questions__c
                                            WHERE Event_Question_Set__c IN (SELECT Event_Question_Set__c FROM Event_Product__c WHERE Id =:eventProductId)
                                            ORDER BY Question_Order__c ASC]){
      thisQuestion.Question__c = thisQuestion.Question__c.replaceAll('<p><br></p>', '');
      thisQuestion.Question__c = thisQuestion.Question__c.trim();
      //Construct and add the question wrapper records to the list
      questionWrapperList.add(constructQuestionWrapper(thisQuestion, eventProductId, campaignFieldToValueMap, eventRegFieldToValueMap, ticketName, eventRegFieldLengthMap, campaignMemberFieldLengthMap));
    }
    return questionWrapperList;
  }

  /**
  * @description - Method to construct the picklist value options
  * @param String answerString - picklist values
  * @param String regex - regular expression to split
  * @return List<PicklistEntryWrapper> 
  **/
  private static List<PicklistEntryWrapper> getAnswerOptions(String answerString, String regex){
    List<PicklistEntryWrapper> thisPickListWrapperList        = new List<PicklistEntryWrapper>();
    //Loop through the picklist entries to construct picklist options
    if(answerString != null){
      //Split the picklist values with respect to the regex
      for(String thisOption : answerString.split(regex)){
        thisPickListWrapperList.add(new PicklistEntryWrapper(thisOption.trim(), thisOption.trim()));
      }
    }
    return thisPickListWrapperList;
  }

  /**
  * @description - Method to construct the field length and maximum digits per field
  * @param SObjectType thisSobjectType 
  * @param Map<String Integer> fieldLengthMap 
  **/
  private static void populateFieldLengthMap(SObjectType thisSobjectType, Map<String, Integer> fieldLengthMap){
    Schema.DescribeSObjectResult objectDescribe = thisSobjectType.getDescribe();

    List<String> fields = new List<String>(objectDescribe.fields.getMap().keySet());

    for(String field : fields) {
      Schema.DescribeFieldResult thisFieldDescribe = objectDescribe.Fields.getMap().get(field).getDescribe();
      if(thisFieldDescribe.getType() == Schema.DisplayType.STRING){
        fieldLengthMap.put(field, thisFieldDescribe.getLength());
      }
      if(thisFieldDescribe.getType() == Schema.DisplayType.INTEGER){
        fieldLengthMap.put(field, thisFieldDescribe.getDigits());
      }
    }
  }
  
  /**
  * @description 
  * @param Questions__c thisQuesionRecord  - Question record
  * @param Id eventProductId - Event product record Id
  * @param Map<String String> campaignFieldToValueMap 
  * @param Map<String String> eventRegFieldToValueMap 
  * @param String ticketName 
  * @param Map<String Integer> eventRegFieldLengthMap 
  * @param Map<String Integer> campaignMemberFieldLengthMap 
  * @return QuestionWrapper 
  **/
  private static QuestionWrapper constructQuestionWrapper(Questions__c thisQuesionRecord, Id eventProductId, Map<String,String> campaignFieldToValueMap, Map<String,String> eventRegFieldToValueMap, String ticketName, Map<String, Integer> eventRegFieldLengthMap, Map<String, Integer> campaignMemberFieldLengthMap){
    QuestionWrapper thisWrapper;
    //To store the dependent picklist type question
    Map<String, DependentPicklistWrapper> dependentPicklistValuesMap = new Map<String, DependentPicklistWrapper>();
    if( thisQuesionRecord.Data_Type__c == ct_EventConstants.QUESTION_DATA_TYPE_TEXT_DEPENDENT_PICKLIST
    && thisQuesionRecord.Dependent_Question_Setup__c != null){
      // logic to construct the Dependent picklist wrapper record
      for(String thisKey: thisQuesionRecord.Dependent_Question_Setup__c.split('\n')){
        String fieldName;
        String objectName;
        String picklistKey;
        String value = null;
        List<PicklistEntryWrapper> thisOptions = new List<PicklistEntryWrapper>();
        if(String.isNotBlank(thisKey)){
          if(thisKey.contains('Field=')){
            fieldName = thisKey.substringAfter('Field=').trim();
          }
          if(thisKey.contains('Object=')){
            objectName = thisKey.substringBetween('Object=','Field=');
            picklistKey = thisKey.substringBefore('Object=');
          }
          if(picklistKey != null){
            thisOptions = getAnswerOptions(picklistKey.split('=')[1].trim(), ';');
            if(campaignFieldToValueMap.containsKey(fieldName.toLowercase())){
              value = campaignFieldToValueMap.get(fieldName.toLowercase());
            }
            else if(eventRegFieldToValueMap.containsKey(fieldName.toLowercase())){
              value = eventRegFieldToValueMap.get(fieldName.toLowercase());
            }
            dependentPicklistValuesMap.put(picklistKey.split('=')[0].trim(), new DependentPicklistWrapper(objectName.trim(), fieldName.trim(), thisOptions, value));
          }
        } 
      }
      if(thisQuesionRecord.Object__c == 'Event_Registration__c'){
        thisWrapper = new QuestionWrapper(thisQuesionRecord, eventProductId, getAnswerOptions(thisQuesionRecord.Answer_Options__c, '\r\n'), eventRegFieldToValueMap, ticketName, dependentPicklistValuesMap, eventRegFieldLengthMap);
      }
      else if(thisQuesionRecord.Object__c == 'CampaignMember'){
        thisWrapper = new QuestionWrapper(thisQuesionRecord, eventProductId, getAnswerOptions(thisQuesionRecord.Answer_Options__c, '\r\n'), campaignFieldToValueMap, ticketName, dependentPicklistValuesMap, campaignMemberFieldLengthMap);

      }
    }
    else if(thisQuesionRecord.Object__c != null
    && thisQuesionRecord.Object__c =='CampaignMember'){
      thisWrapper = new QuestionWrapper(thisQuesionRecord, eventProductId, getAnswerOptions(thisQuesionRecord.Answer_Options__c, '\r\n'), campaignFieldToValueMap, ticketName, dependentPicklistValuesMap, campaignMemberFieldLengthMap);
    }         
    else{
      thisWrapper = new QuestionWrapper(thisQuesionRecord, eventProductId, getAnswerOptions(thisQuesionRecord.Answer_Options__c, '\r\n'), eventRegFieldToValueMap, ticketName, dependentPicklistValuesMap, eventRegFieldLengthMap);
    }
    return thisWrapper;
  }
  // Question Wrapper class
  global class QuestionWrapper{
    @AuraEnabled
    global Questions__c thisQuestion { get; set; }
    @AuraEnabled
    global String eventProductId { get; set; }
    @AuraEnabled
    global Boolean hasInput { get;set; }
    @AuraEnabled
    global Boolean hasNumber { get;set; } 
    @AuraEnabled
    global Boolean hasPhone { get;set; } 
    @AuraEnabled
    global Boolean hasCurrency { get;set; }
    @AuraEnabled
    global Boolean hasTextArea { get;set; }
    @AuraEnabled
    global Boolean hasTextAreaLong { get;set; }
    @AuraEnabled
    global Boolean hasRichTextArea { get;set; }
    @AuraEnabled
    global Boolean hasPicklist { get;set; }
    @AuraEnabled
    global Boolean hasDate { get;set; }
    @AuraEnabled
    global Boolean hasRadioOptions { get;set; }
    @AuraEnabled
    global String eventRegRecordValue { get;set; }
    @AuraEnabled
    global String radioOptionName { get;set; }
    @AuraEnabled
    global Integer maxLength { get;set; }
    @AuraEnabled
    global String defaultAnswer { get;set; }
    @AuraEnabled
    global List<PicklistEntryWrapper> picklistFields {get;set;}
    @AuraEnabled
    global Boolean hasDependent { get;set; }
    @AuraEnabled
    global Map<String, DependentPicklistWrapper> dependentPicklistFields {get;set;}
    //Constructor for the Question Wrapper class passing the question record and construct the Queation wrapper record
    global QuestionWrapper(Questions__c questionRecord, Id eventProductId, List<PicklistEntryWrapper> answerOptions, Map<String, String> valueMap, String ticketName, Map<String, DependentPicklistWrapper> dependentPicklistValuesMap, Map<String,Integer> fieldLengthMap){
      this.thisQuestion = questionRecord;
      
      this.eventProductId = eventProductId;
      if(String.isNotBlank(ticketName)){
        this.radioOptionName = questionRecord.Name+ticketName;
      }
      else{
        this.radioOptionName = questionRecord.Name+'Ticket';
      }
      
      String value = '';
      if(String.isNotBlank(questionRecord.Even_Registration_Field_API_Name__c)
      && valueMap.containsKey(questionRecord.Even_Registration_Field_API_Name__c.toLowercase())){
        value = valueMap.get(questionRecord.Even_Registration_Field_API_Name__c.toLowercase());
        if(value.contains('00:00:00')){
          value = value.remove('00:00:00').normalizeSpace();
        }
      }
      this.defaultAnswer =  String.isNotBlank(questionRecord.Default_Text__c) ? questionRecord.Default_Text__c.trim() : questionRecord.Default_Text__c;
      this.eventRegRecordValue = String.isNotBlank(value) ? value : this.defaultAnswer;

      if(questionRecord.Data_Type__c == 'Rich Text Area'){
        this.hasRichTextArea = true;
      }
      else if(questionRecord.Data_Type__c == 'Text Area'){
        this.hasTextArea = true;
      }
      else if(questionRecord.Data_Type__c == 'Long Text Area'){
        this.hasTextAreaLong = true;
      }
      else if(questionRecord.Data_Type__c == 'Picklist'){
        this.hasPicklist = true;
      }
      else if(questionRecord.Data_Type__c == 'Picklist with Radio Options'){
        this.hasRadioOptions = true;
      } 
      else if(questionRecord.Data_Type__c == 'Currency'){
        this.hasCurrency = true;
      }
      else if(questionRecord.Data_Type__c == 'Number'){
        this.hasNumber = true;
      }
      else if(questionRecord.Data_Type__c == 'Phone'){
        this.hasPhone = true;
      }
      else if(questionRecord.Data_Type__c == 'Dependent Picklist'){
        this.hasDependent = true;
      }
      else if(questionRecord.Data_Type__c == 'Date'){
        this.hasDate = true;
      }
      else{
        this.hasInput = true;
      }
      this.picklistFields = answerOptions;
      this.dependentPicklistFields = dependentPicklistValuesMap;

      if(fieldLengthMap != null 
        && !fieldLengthMap.isEmpty()
        && String.isNotBlank(questionRecord.Even_Registration_Field_API_Name__c)
        && fieldLengthMap.containsKey(questionRecord.Even_Registration_Field_API_Name__c.toLowercase())){
          this.maxLength = fieldLengthMap.get(questionRecord.Even_Registration_Field_API_Name__c.toLowercase());
        }
    }
  }

  /**
    * Wrapper that contains Donation Object wrapper and Picklist Values
  */
  global class PicklistEntryWrapper{
    //get set string to store lable of picklist entry
    @AuraEnabled
    global String label                  {get;set;}
    //get set string to store value of picklist entry
    @AuraEnabled
    global string value                  {get;set;}
    
    global PicklistEntryWrapper(String entryLabel,String entryValue){
      this.label    = entryLabel;
      this.value    = entryValue;
    }
  }
  /**
    * Wrapper that contains Donation Object wrapper and Picklist Values
  */
  global class DependentPicklistWrapper{
    //get set string to store lable of picklist entry
    @AuraEnabled
    global String objectName                 {get;set;}
    //get set string to store value of picklist entry
    @AuraEnabled
    global string fieldAPIName                  {get;set;}
    @AuraEnabled
    global List<PicklistEntryWrapper> picklistOptions   {get;set;}
    @AuraEnabled
    global String eventRegRecordValue { get;set; }
    
    global DependentPicklistWrapper(String objectAPIName,String fieldname, List<PicklistEntryWrapper> options, String value){
      this.objectName       = objectAPIName;
      this.fieldAPIName     = Fieldname;
      this.picklistOptions  = options;
      this.eventRegRecordValue = value;
    }
  }
}