force-app/main/default/objects/CampaignMember/fields/Event_Registration__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to the Event Registration for the associated Campaign</description>
    <label>Event Registration</label>
    <referenceTo>Event_Registration__c</referenceTo>
    <relationshipLabel>Campaign Members</relationshipLabel>
    <relationshipName>Campaign_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CampaignMember/fields/Primary_Subject_Area_Interest__c.field-meta.xml
<CustomField>
    <fullName>Primary_Subject_Area_Interest__c</fullName>
    <description>The Primary Subject Area Interest of the Campaign Member</description>
    <label>Primary Subject Area Interest</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Course_Options</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <displayFormat>REG-{0000000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/fields/Primary_Subject_Area_Interest__c.field-meta.xml
<CustomField>
    <fullName>Primary_Subject_Area_Interest__c</fullName>
    <description>This field is used to store Primary Subject Area interest value form Session</description>
    <inlineHelpText>This field is automated through Web Registration process</inlineHelpText>
    <label>Primary Subject Area Interest</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Course_Options.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Accounting and Financial Management</fullName>
    </customValue>
    <customValue>
        <fullName>American Studies</fullName>
    </customValue>
    <customValue>
        <fullName>Architecture</fullName>
    </customValue>
    <customValue>
        <fullName>Art &amp; Design</fullName>
    </customValue>
    <customValue>
        <fullName>Biological Sciences</fullName>
    </customValue>
    <customValue>
        <fullName>Building Surveying, Property Development and Quantity Surveying</fullName>
    </customValue>
    <customValue>
        <fullName>Business and Management</fullName>
    </customValue>
    <customValue>
        <fullName>Childhood Studies</fullName>
    </customValue>
    <customValue>
        <fullName>Civil Engineering and Construction Engineering Management</fullName>
    </customValue>
    <customValue>
        <fullName>Computing</fullName>
    </customValue>
    <customValue>
        <fullName>Computing &amp; ICT</fullName>
    </customValue>
    <customValue>
        <fullName>Creative &amp; Digital Technologies</fullName>
    </customValue>
    <customValue>
        <fullName>Creative Writing</fullName>
    </customValue>
    <customValue>
        <fullName>Criminology</fullName>
    </customValue>
    <customValue>
        <fullName>Dental Hygiene, Therapy and Nursing</fullName>
    </customValue>
    <customValue>
        <fullName>Earth and Environmental Sciences</fullName>
    </customValue>
    <customValue>
        <fullName>Economics</fullName>
    </customValue>
    <customValue>
        <fullName>Energy &amp; Electronic Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering and Technology - Other</fullName>
    </customValue>
    <customValue>
        <fullName>English Language and Linguistics</fullName>
    </customValue>
    <customValue>
        <fullName>English Literature</fullName>
    </customValue>
    <customValue>
        <fullName>Film and Media</fullName>
    </customValue>
    <customValue>
        <fullName>Games &amp; Animation</fullName>
    </customValue>
    <customValue>
        <fullName>Geography</fullName>
    </customValue>
    <customValue>
        <fullName>Graphics, Design &amp; Art</fullName>
    </customValue>
    <customValue>
        <fullName>History</fullName>
    </customValue>
    <customValue>
        <fullName>Human Resources Management</fullName>
    </customValue>
    <customValue>
        <fullName>International Development</fullName>
    </customValue>
    <customValue>
        <fullName>International Relations and Politics</fullName>
    </customValue>
    <customValue>
        <fullName>Journalism</fullName>
    </customValue>
    <description>Provides a list of all available subject area options</description>
    <masterLabel>Subject Areas</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ct_CampaignMemberTriggerHandler.cls
/**
 * @description       : Create an Event Registrations once campaign member added into the If the campaign synced with the event
 * @author            : Creation Admin
**/
global without sharing class ct_CampaignMemberTriggerHandler /*extends hed.TDTM_Runnable*/ {

    /*******************************************************************************************************
    * @description Turns class off.
    * @return void
    ********************************************************************************************************/
    global static void turnOff() {
        ct_ProcessControl.turnOffRecursionFlag(ct_ProcessControl.registeredTrigger.ct_CampaignMemberTriggerHandler_After_Insert);
        ct_ProcessControl.turnOffRecursionFlag(ct_ProcessControl.registeredTrigger.ct_CampaignMemberTriggerHandler_After_Update);
    }
    
    /*******************************************************************************************************
    * @description Turns class on.
    * @return void
    ********************************************************************************************************/
    global static void turnOn() {
        ct_ProcessControl.resetRecursionFlag(ct_ProcessControl.registeredTrigger.ct_CampaignMemberTriggerHandler_After_Insert);
        ct_ProcessControl.resetRecursionFlag(ct_ProcessControl.registeredTrigger.ct_CampaignMemberTriggerHandler_After_Update);
    }
    

    // global override hed.TDTM_Runnable.DmlWrapper run(List<SObject> newlist, List<SObject> oldlist,
    // hed.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult) {

    // System.debug('>>>>>>>>>>>>>>>>>>>>>>>>>>>CT CAMPAIGN MEMBER TDTM TRIGGER<<<<<<<<<<<<<<<<<<<<<<<<<<<');

    // hed.TDTM_Runnable.dmlWrapper dmlWrapper = new hed.TDTM_Runnable.DmlWrapper();
    
    //Set of Campaign Id for creating Event Registration

    global static void HandleAfterInsert(list<CampaignMember> newlist){
      System.debug('>>>>>>>>>>>>>>>>>>>>>>>>>>>CAMPAIGN MEMBER AFTER INSERT TRIGGER<<<<<<<<<<<<<<<<<<<<<<<<<<<');
      Set<Id> campaignIds                         = new Set<Id>();
      Set<Id> campaignMemberIds                   = new Set<Id>();
      Map<Id, Set<Id>> leadIdToCampaignIdMap      = new Map<Id, Set<Id>>();
      Map<Id, Set<Id>> contactToCampaignIdMap     = new Map<Id, Set<Id>>();
      Map<Id, Set<Id>> accountToCampaignIdMap     = new Map<Id, Set<Id>>();

      //Loop to get The required Ids 
      for(CampaignMember thisCampaignMember : (list<CampaignMember>)newlist){
        campaignIds.add(thisCampaignMember.CampaignId);
        campaignMemberIds.add(thisCampaignMember.Id);

        if(thisCampaignMember.LeadId != null){
          if(leadIdToCampaignIdMap.isEmpty() 
            || !leadIdToCampaignIdMap.containsKey(thisCampaignMember.LeadId)){
              leadIdToCampaignIdMap.put(thisCampaignMember.LeadId, new Set<Id>());
          }
          leadIdToCampaignIdMap.get(thisCampaignMember.LeadId).add(thisCampaignMember.CampaignId);
        }

        /*if(thisCampaignMember.ContactId != null){
          if(contactToCampaignIdMap.isEmpty() 
            || !contactToCampaignIdMap.containsKey(thisCampaignMember.ContactId)){
              contactToCampaignIdMap.put(thisCampaignMember.ContactId, new Set<Id>());
          }
          contactToCampaignIdMap.get(thisCampaignMember.ContactId).add(thisCampaignMember.CampaignId);
        }*/

        if(thisCampaignMember.Account__c != null){
          if(accountToCampaignIdMap.isEmpty() 
            || !accountToCampaignIdMap.containsKey(thisCampaignMember.Account__c)){
              accountToCampaignIdMap.put(thisCampaignMember.Account__c, new Set<Id>());
          }
          accountToCampaignIdMap.get(thisCampaignMember.Account__c).add(thisCampaignMember.CampaignId);
        }
          
      }
      //Set the recursion flag for ct_CampaignMemberTriggerHandler_TDTM Trigger handler After Insert using ct_ProcessControl which
      //is based in TDTM_ProcessControl frame work of EDA package
      ct_ProcessControl.setRecursionFlag(ct_ProcessControl.registeredTrigger.ct_CampaignMemberTriggerHandler_After_Insert, true);

      if(!campaignIds.isEmpty() && !System.isBatch() && !System.isFuture() && !System.isQueueable()){
        ct_Campaign_MemberTriggerHelper.createEventRegistration(campaignIds, campaignMemberIds, leadIdToCampaignIdMap, contactToCampaignIdMap, accountToCampaignIdMap);
        ct_Campaign_MemberTriggerHelper.campaignMemberRollupCalculation(campaignIds);
      }
    }
    
    global static void HandleAfterUpdate(list<CampaignMember> newlist, list<CampaignMember> oldlist){
        System.debug('>>>>>>>>>>>>>>>>>>>>>>>>>>>CAMPAIGN MEMBER AFTER UPDATE TRIGGER<<<<<<<<<<<<<<<<<<<<<<<<<<<');
    Map<Id, CampaignMember> triggerOldMap = new Map<Id, CampaignMember>((list<CampaignMember>)oldlist);
    Map<Id, CampaignMember> triggerNewMap = new Map<Id, CampaignMember>((list<CampaignMember>)newlist);
    Set<Id> campaignIds                  = new Set<Id>();
    Set<Id> eventRegistrationIdsToSync   = new Set<Id>();       
    List<CampaignMember> campaignMembersToSync   = new List<CampaignMember>();

    
        //Loop to get The required Ids 
        for(CampaignMember thisCampaignMember : (list<CampaignMember>)newlist){
           campaignIds.add(thisCampaignMember.CampaignId);
            
          if(thisCampaignMember.Event_Registration__c != null 
            && (thisCampaignMember.Status != triggerOldMap.get(thisCampaignMember.Id).Status
            || thisCampaignMember.Primary_Subject_Area_Interest__c != triggerOldMap.get(thisCampaignMember.Id).Primary_Subject_Area_Interest__c)){
              eventRegistrationIdsToSync.add(thisCampaignMember.Event_Registration__c);
              campaignMembersToSync.add(thisCampaignMember);
          }
        }
		 //Set the recursion flag for ct_CampaignMemberTriggerHandler_TDTM Trigger handler After Insert using ct_ProcessControl which
      	//is based in TDTM_ProcessControl frame work of EDA package
        ct_ProcessControl.setRecursionFlag(ct_ProcessControl.registeredTrigger.ct_CampaignMemberTriggerHandler_After_Update, true);

        if(!eventRegistrationIdsToSync.isEmpty()){
          ct_Campaign_MemberTriggerHelper.syncEventRegistrationWithCampaignMember(campaignMembersToSync, eventRegistrationIdsToSync);
        }
         if(!campaignIds.isEmpty() && !System.isFuture() && !System.isBatch()){
              ct_Campaign_MemberTriggerHelper.campaignMemberRollupCalculation(campaignIds);  
            } 
      }
      
  global static void HandleAfterDelete(list<CampaignMember> oldlist){{
        Set<Id> campaignIds                         = new Set<Id>();
        Set<Id> eventRegistrationIdsToCancel        = new Set<Id>();
        
    List<CampaignMember> campaignMembersToSync          = new List<CampaignMember>();
            for(CampaignMember thisCampaignMember : (list<CampaignMember>)oldlist){
                campaignIds.add(thisCampaignMember.CampaignId);  
                if(thisCampaignMember.Event_Registration__c != null){
                  eventRegistrationIdsToCancel.add(thisCampaignMember.Event_Registration__c);
                }
            } 
            if(!campaignIds.isEmpty() && !System.isFuture() && !System.isBatch()){
              ct_Campaign_MemberTriggerHelper.campaignMemberRollupCalculation(campaignIds);  
            }
            if(!eventRegistrationIdsToCancel.isEmpty() && !System.isFuture() && !System.isBatch()){
              ct_Campaign_MemberTriggerHelper.cancelEventRegistration(eventRegistrationIdsToCancel);  
            }
        }  
  //   return dmlWrapper;
  // }
}
}