force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <defaultValue>TIMEVALUE(&quot;12:00:00.000&quot;)</defaultValue>
    <description>The time the event is due to finish</description>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <defaultValue>TIMEVALUE(&quot;12:00:00.000&quot;)</defaultValue>
    <description>The time the event is due to start</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <displayFormat>REG-{0000000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Event_Email__c.field-meta.xml
<CustomField>
    <fullName>Event_Email__c</fullName>
    <label>Event Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Event_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Event_Mobile__c</fullName>
    <description>This field is used to store event attendee mobile number</description>
    <inlineHelpText>This field will be populated using ticket management web form</inlineHelpText>
    <label>Event Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Event_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration_Status__c</fullName>
    <description>Event Registration Status</description>
    <inlineHelpText>Event Registration Status</inlineHelpText>
    <label>Event Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Attended / Checked In</fullName>
            </value>
            <value>
                <fullName>Attended / Checked Out</fullName>
            </value>
            <value>
                <fullName>Did Not Attend</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/QR_Code__c.field-meta.xml
<CustomField>
    <fullName>QR_Code__c</fullName>
    <description>Event Registration QR Code</description>
    <inlineHelpText>Event Registration QR Code</inlineHelpText>
    <label>QR Code</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Registration_Type__c</fullName>
    <label>Registration Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Complementary - Speaker</fullName>
            </value>
            <value>
                <fullName>Complementary - Vendor</fullName>
            </value>
            <value>
                <fullName>Complementary - Prospect</fullName>
            </value>
            <value>
                <fullName>Complementary - Media</fullName>
            </value>
            <value>
                <fullName>Myself</fullName>
            </value>
            <value>
                <fullName>Someone Else</fullName>
            </value>
            <value>
                <fullName>Unknown Guest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Primary Session the individual is interested in attending</description>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QR_Scanner_User_Configuration__c/QR_Scanner_User_Configuration__c.object-meta.xml
<CustomObject>
    <label>QR Scanner User Configuration</label>
    <nameField>
        <label>QR Scanner User Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QR Scanner User Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QR_Scanner_User_Configuration__c/fields/Configured_Sessions__c.field-meta.xml
<CustomField>
    <fullName>Configured_Sessions__c</fullName>
    <description>Configured Sessions for respective Selected Event</description>
    <inlineHelpText>Configured Sessions</inlineHelpText>
    <label>Configured Sessions</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/QR_Scanner_User_Configuration__c/fields/Current_Session__c.field-meta.xml
<CustomField>
    <fullName>Current_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Current Session in which the user is allocated for Check In Management</description>
    <inlineHelpText>Current Session in which the user is allocated for Check In Management</inlineHelpText>
    <label>Current Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>QR Scanner User Configurations</relationshipLabel>
    <relationshipName>QR_Scanner_User_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QR_Scanner_User_Configuration__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Event in which the user is assigned for Check In Management</description>
    <inlineHelpText>Event in which the user is assigned for Check In Management</inlineHelpText>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>QR Scanner User Configurations</relationshipLabel>
    <relationshipName>QR_Scanner_User_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QR_Scanner_User_Configuration__c/fields/Is_Main_Entrance__c.field-meta.xml
<CustomField>
    <fullName>Is_Main_Entrance__c</fullName>
    <defaultValue>false</defaultValue>
    <description>To denote that the user scanning QR is assigned at main entrance</description>
    <inlineHelpText>To denote that the user scanning QR is assigned at main entrance</inlineHelpText>
    <label>Is Main Entrance</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QR_Scanner_User_Configuration__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User who is using QR Scanner for Check in management</description>
    <inlineHelpText>User who is using QR Scanner for Check in management</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>QR_Scanner_User_Configurations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description>The end time of a session</description>
    <label>Session End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>This associates a Session to an Event</description>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_End_Date__c</fullName>
    <description>This field is used to record the session end date</description>
    <inlineHelpText>Please choose an appropriate end date for this session</inlineHelpText>
    <label>Session End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_Start_Date__c</fullName>
    <description>Session Start Date</description>
    <inlineHelpText>Session Start Date</inlineHelpText>
    <label>Session Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>The start time of a session</description>
    <label>Session Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/Session_Registration__c.object-meta.xml
<CustomObject>
    <label>Session Registration</label>
    <nameField>
        <displayFormat>SAR - {00000}</displayFormat>
        <label>Session Registration Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Registration__c/fields/Event_Registration__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Registration</label>
    <referenceTo>Event_Registration__c</referenceTo>
    <relationshipName>Session_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <formula>Event_Registration__r.First_Name__c</formula>
    <label>First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <formula>Event_Registration__r.Last_Name__c</formula>
    <label>Last Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/fields/QR_Code__c.field-meta.xml
<CustomField>
    <fullName>QR_Code__c</fullName>
    <description>Session Registration QR Code</description>
    <inlineHelpText>Session Registration QR Code</inlineHelpText>
    <label>QR Code</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/fields/Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Registration_Type__c</fullName>
    <formula>TEXT(Event_Registration__r.Registration_Type__c)</formula>
    <label>Registration Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipName>Session_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/fields/Session_Walk_In__c.field-meta.xml
<CustomField>
    <fullName>Session_Walk_In__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox to indicate that the session was registered during Event Walk In</description>
    <inlineHelpText>Checkbox to indicate that the session was registered during Event Walk In</inlineHelpText>
    <label>Session Walk In</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting List</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Attended / Checked In</fullName>
            </value>
            <value>
                <fullName>Attended / Checked Out</fullName>
            </value>
            <value>
                <fullName>Did Not Attend</fullName>
                <color>#A845DC</color>
                <label>Did Not Attend</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <color>#E27001</color>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Attending</fullName>
                <isActive>false</isActive>
                <label>Attending</label>
            </value>
            <value>
                <fullName>Checked In</fullName>
                <isActive>false</isActive>
                <label>Checked In</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ct_CheckInManagerQRCodeScannerController.cls
/**
 * @description       : Check In Manager QRCode Scanner LWC Controller
 * @author            : Creation Admin
 * @group             : 
 * @last modified on  : 01-21-2021
 * @last modified by  : Creation Admin
 * Modifications Log 
 * Ver   Date         Author           Modification
 * 1.0   09-14-2020   Creation Admin   Initial Version
**/
global without sharing class ct_CheckInManagerQRCodeScannerController {
	
	/**
	* @description Method to get Event and Session configurations wrapper for check in Manager component
	* @param selectedEventId Event Id
	* @param currentSessionId Current location of configured by check in user
	* @param configuredSession Configured session by check in user
	* @return EventSessionDetailsWrapperInitialWrapper 
	**/
	@AuraEnabled
	global static EventSessionDetailsWrapperInitialWrapper getEventSessionDetailsWrapper(String selectedEventId, String currentSessionId, String configuredSession){
		try {
			Boolean isSelectedVar;
			List<String> configuredSessionIds = new List<String>();
			if(!String.isEmpty(configuredSession)){configuredSessionIds = configuredSession.split(',');}

			EventSessionDetailsWrapperInitialWrapper thisConfigWrapper = new EventSessionDetailsWrapperInitialWrapper();
			ct_CheckInManagerController.initialWrapper thisCheckInInitialWrapper = ct_CheckInManagerController.getInitialWrapper();

			List<EventSessionDetailsWrapper> thisEventOptions = new List<EventSessionDetailsWrapper>();
			for(ct_CheckInManagerController.PicklistEntryWrapper thiseventWrapper : thisCheckInInitialWrapper.eventOptions){
				isSelectedVar = (!String.isEmpty(selectedEventId) && thiseventWrapper.value == selectedEventId) ?  true : false;
				thisEventOptions.add(new EventSessionDetailsWrapper(thiseventWrapper.label, thiseventWrapper.value, isSelectedVar));
			}
			thisConfigWrapper.eventOptions = thisEventOptions;

			Map<String, List<EventSessionDetailsWrapper>>  thisSessionOptions = new Map<String, List<EventSessionDetailsWrapper>> ();

			for(String thisSessionOptionKey : thisCheckInInitialWrapper.sessionOptions.keySet()){

				thisSessionOptions.put(thisSessionOptionKey, new List<EventSessionDetailsWrapper>());

				for(ct_CheckInManagerController.PicklistEntryWrapper thisSessionWrapper : thisCheckInInitialWrapper.sessionOptions.get(thisSessionOptionKey)){
					EventSessionDetailsWrapper thisSessionOption = new EventSessionDetailsWrapper();
					thisSessionOption.label  										 = thisSessionWrapper.label;
					thisSessionOption.value  										 = thisSessionWrapper.value;
					thisSessionOption.isSelected								 = (!configuredSessionIds.isEmpty() && configuredSession.contains(thisSessionWrapper.value)) ?  true : false;
					thisSessionOption.isCurrentSession   				 = (!String.isEmpty(currentSessionId) && thisSessionWrapper.value == currentSessionId) ?  true : false;
					thisSessionOptions.get(thisSessionOptionKey).add(thisSessionOption);
				}
			}

			thisConfigWrapper.sessionOptions = thisSessionOptions;
			return thisConfigWrapper;
		} 
		catch(Exception e){
			//Exception mechanism to log any exceptions occured during the dml operation
			ct_Logger.logMessage(e, 'Event QR Scanner Desktop get User Configuration');
			throw new AuraHandledException('Error '+ e.getMessage());
		}	
	}

	/**
	* @description Method to get Event and Session configurations wrapper for check in Manager component
	* @param selectedEventId Event Id
	* @param currentSessionId Current location of configured by check in user
	* @param configuredSession Configured session by check in user
	* @return EventSessionDetailsWrapperInitialWrapper 
	**/
	@AuraEnabled
	global static EventSessionDetailsWrapperInitialWrapper getQRCodeScannerInitialWrapper(String selectedEventId, String currentSessionId, String configuredSession){
		try {
			Boolean isSelectedVar;
			List<String> configuredSessionIds = new List<String>();
			if(!String.isEmpty(configuredSession)){configuredSessionIds = configuredSession.split(',');}

			EventSessionDetailsWrapperInitialWrapper thisConfigWrapper = new EventSessionDetailsWrapperInitialWrapper();
			ct_CheckInManagerController.initialWrapper thisCheckInInitialWrapper = ct_CheckInManagerController.getInitialWrapper();

			List<EventSessionDetailsWrapper> thisEventOptions = new List<EventSessionDetailsWrapper>();
			for(ct_CheckInManagerController.PicklistEntryWrapper thiseventWrapper : thisCheckInInitialWrapper.eventOptions){
				isSelectedVar = (!String.isEmpty(selectedEventId) && thiseventWrapper.value == selectedEventId) ?  true : false;
				thisEventOptions.add(new EventSessionDetailsWrapper(thiseventWrapper.label, thiseventWrapper.value, isSelectedVar));
			}
			thisConfigWrapper.eventOptions = thisEventOptions;

			Map<String, List<EventSessionDetailsWrapper>>  thisSessionOptions = new Map<String, List<EventSessionDetailsWrapper>> ();

			for(String thisSessionOptionKey : thisCheckInInitialWrapper.sessionOptions.keySet()){

				thisSessionOptions.put(thisSessionOptionKey, new List<EventSessionDetailsWrapper>());

				for(ct_CheckInManagerController.PicklistEntryWrapper thisSessionWrapper : thisCheckInInitialWrapper.sessionOptions.get(thisSessionOptionKey)){
					EventSessionDetailsWrapper thisSessionOption = new EventSessionDetailsWrapper();
					thisSessionOption.label  										 = thisSessionWrapper.label;
					thisSessionOption.value  										 = thisSessionWrapper.value;
					thisSessionOption.isSelected								 = (!configuredSessionIds.isEmpty() && configuredSession.contains(thisSessionWrapper.value)) ?  true : false;
					thisSessionOption.isCurrentSession   				 = (!String.isEmpty(currentSessionId) && thisSessionWrapper.value == currentSessionId) ?  true : false;
					thisSessionOptions.get(thisSessionOptionKey).add(thisSessionOption);
				}
			}

			thisConfigWrapper.sessionOptions = thisSessionOptions;
			return thisConfigWrapper;
		} 
		catch(Exception e){
			//Exception mechanism to log any exceptions occured during the dml operation
			ct_Logger.logMessage(e, 'Event QR Scanner Get Event Session Options');
			throw new AuraHandledException('Error '+ e.getMessage());
		}	
	}

	/**
	* @description Method to get Event, Sessions details for Check In Manager / QR code scanner from user configurations for that user
	* @return InitialWrapper 
	**/
  @AuraEnabled
	global static InitialWrapper getInitialWrapper(){
		try {
			String timesStamp;
			InitialWrapper thisInitialWrapper = new InitialWrapper();
			//Get user configuration record based on current user
			List<QR_Scanner_User_Configuration__c> thisUserConfiguration = [SELECT Id, Name, User__c, Is_Main_Entrance__c, Configured_Sessions__c, Event__c, 
																																			Current_Session__c, Event__r.Name, Current_Session__r.Name,
																																			Current_Session__r.Start_Time__c,
																																			Current_Session__r.End_Time__c, 
																																			Current_Session__r.Session_End_Date__c,
																																			Current_Session__r.Session_Start_Date__c
																																			FROM QR_Scanner_User_Configuration__c
																																			WHERE User__c =: UserInfo.getUserId()
																																			LIMIT 1];

			thisInitialWrapper.hasExistingConfiguration = !thisUserConfiguration.isEmpty() ? true : false;
			//if has existing configuration, process the Initial Wrapper
			if(thisInitialWrapper.hasExistingConfiguration){
				thisInitialWrapper.userConfigRecordId         = thisUserConfiguration[0].Id;
				thisInitialWrapper.configuredEventId          = thisUserConfiguration[0].Event__c;
				thisInitialWrapper.currentSession 						= thisUserConfiguration[0].Current_Session__c;
				thisInitialWrapper.configuredEventName				= thisUserConfiguration[0].Event__r.Name;
				thisInitialWrapper.isMainEntrance							= thisUserConfiguration[0].Is_Main_Entrance__c;
				//Update the Session label with its Time for displaying in LWC Component
				if(thisUserConfiguration[0].Current_Session__r.Session_Start_Date__c != null && thisUserConfiguration[0].Current_Session__r.Start_Time__c != null){
					timesStamp = ' ('+DateTime.newInstance(thisUserConfiguration[0].Current_Session__r.Session_Start_Date__c, thisUserConfiguration[0].Current_Session__r.Start_Time__c).format('HH:mm');
					if(thisUserConfiguration[0].Current_Session__r.Session_End_Date__c != null && thisUserConfiguration[0].Current_Session__r.End_Time__c != null){
						timesStamp = timesStamp + +' - ' + DateTime.newInstance(thisUserConfiguration[0].Current_Session__r.Session_End_Date__c, thisUserConfiguration[0].Current_Session__r.End_Time__c).format('HH:mm') + ' )';
					}
					else {
						timesStamp = timesStamp + ' )';
					}
				}

				thisInitialWrapper.configuredSessionName = thisUserConfiguration[0].Current_Session__r.Name + timesStamp;
				if(!String.isEmpty(thisUserConfiguration[0].Configured_Sessions__c)){
					thisInitialWrapper.configuredSessions 			= thisUserConfiguration[0].Configured_Sessions__c.split(',');
				}
			}
			return thisInitialWrapper;
		} catch(Exception e){
			//Exception mechanism to log any exceptions occured during the dml operation
			ct_Logger.logMessage(e, 'Event QR Scanner Desktop get User Configuration');
			throw new AuraHandledException('Error '+ e.getMessage());
		}	
  }

	/**
	* @description Method to update the check in manager user configuration if changed by the user
	* @param userConfiguration 
	**/
  @AuraEnabled
	global static void updateSessionId(String userConfiguration){
		try{
			QR_Scanner_User_Configuration__c thisUserConfig = (QR_Scanner_User_Configuration__c)JSON.deserialize(userConfiguration, QR_Scanner_User_Configuration__c.class);
			thisUserConfig.Name = thisUserConfig.Name +' - '+ UserInfo.getName();
			upsert thisUserConfig;
		}
		catch(Exception e){
			//Exception mechanism to log any exceptions occured during the dml operation
			ct_Logger.logMessage(e, 'Event Registration Session Configuration Update');
			throw new AuraHandledException('Error '+ e.getMessage());
		}	
  }

	/**
	* @description Method to update the Event registration / Session registration status from Check in manager
	* @param eventRegistrationId Event registration record Id
	* @param sessionId Session record ID
	* @param isMainEntrance Boolean to denote whether to update the Event registration or session registration
	* @return QRScannedResultWrapper 
	**/
  @AuraEnabled
	global static QRScannedResultWrapper updateEventRegistartionStatus(String eventRegistrationId, String sessionId, Boolean isMainEntrance){
		List<sObject> sobjectListToUpdate = new List<sObject>();
		QRScannedResultWrapper thisQRScannedResultWrapper = new QRScannedResultWrapper();
		Map<String, String> eventRegistartionStatusToUdpate = new Map<String, String>{
																													ct_EventConstants.EVENT_REGISTRATION_REGISTERED => ct_EventConstants.EVENT_REGISTRATION_CHECKED_IN};

		Map<String, String> sessionRegistartionStatusToUdpate = new Map<String, String>{
																														ct_EventConstants.SESSION_REGISTRATION_REGISTERED => ct_EventConstants.SESSION_REGISTRATION_CHECKED_IN};
	try{
		List<Event_Registration__c> thisEventRegistration = [SELECT Id, Name, Event_Registration_Status__c, Event__c, Registration_Type__c, First_Name__c,
																												Last_Name__c, Event_Email__c,Event_Mobile__c, QR_Code__c
																												FROM Event_Registration__c
																												WHERE Id =:eventRegistrationId LIMIT 1];

		List<Session_Registration__c> thisSessionRegistration = [SELECT Id, Name, Status__c, First_Name__c, Last_Name__c, Event_Registration__c, Registration_Type__c
																															FROM Session_Registration__c
																															WHERE Event_Registration__c =:eventRegistrationId 
																															AND Session__c = :sessionId LIMIT 1];

		//If is Main Entrance update Event registration
		if(isMainEntrance){
			if(thisEventRegistration.isEmpty()){
				thisQRScannedResultWrapper.isCustomError = true;
				thisQRScannedResultWrapper.customErrorMessage = 'ERROR : No Event Registration Found';
			}
			else{
				thisQRScannedResultWrapper.eventRegistration = thisEventRegistration[0];
				//If Registration type is Unknown guest, then process the wrapper result to get the registration details
				if(thisEventRegistration[0].Registration_Type__c == ct_EventConstants.EVENT_REGISTRATION_TYPE_GUEST
				&& (thisEventRegistration[0].First_Name__c == null || thisEventRegistration[0].Last_Name__c == null || thisEventRegistration[0].Event_Email__c == null)){
					thisQRScannedResultWrapper.recordIdToRedirect 	= thisEventRegistration[0].Id;
					thisQRScannedResultWrapper.recordActionName 		=  'edit';
					thisQRScannedResultWrapper.customSuccessMessage = 'Event Registration Status Updated Successfully';
				}
				else{
					thisQRScannedResultWrapper.recordIdToRedirect 	= thisEventRegistration[0].Id;
					thisQRScannedResultWrapper.recordActionName 		=  'view';
					thisQRScannedResultWrapper.customSuccessMessage = 'Event Registration Status Updated Successfully';
				}

				if(thisEventRegistration[0].Event_Registration_Status__c != null
						&& !eventRegistartionStatusToUdpate.isEmpty()
						&& eventRegistartionStatusToUdpate.containsKey(thisEventRegistration[0].Event_Registration_Status__c)){
							thisEventRegistration[0].Event_Registration_Status__c = eventRegistartionStatusToUdpate.get(thisEventRegistration[0].Event_Registration_Status__c);
							sobjectListToUpdate.add(thisEventRegistration[0]);
				}
				else if(thisEventRegistration[0].Event_Registration_Status__c == ct_EventConstants.EVENT_REGISTRATION_CHECKED_IN){
					thisQRScannedResultWrapper.isCustomError = true;
					//If already check In throw error message
					thisQRScannedResultWrapper.customErrorMessage = 'ERROR : Event Registration already set to Checked / In';
				}
			}
		}
		else{
			if(!thisEventRegistration.isEmpty()
				&& thisEventRegistration[0].Event_Registration_Status__c != null
				&& thisEventRegistration[0].Event_Registration_Status__c != ct_EventConstants.EVENT_REGISTRATION_CHECKED_IN){
					thisEventRegistration[0].Event_Registration_Status__c = ct_EventConstants.EVENT_REGISTRATION_CHECKED_IN;
					sobjectListToUpdate.add(thisEventRegistration[0]);
			}
			
			thisQRScannedResultWrapper.eventRegistration = thisEventRegistration[0];
			if(thisSessionRegistration.isEmpty()
				&& !thisEventRegistration.isEmpty()){

				thisQRScannedResultWrapper.recordIdToRedirect 	= createSessionRegistration(sessionId, thisEventRegistration[0]);
				thisQRScannedResultWrapper.recordActionName 		=  'view';
				thisQRScannedResultWrapper.customSuccessMessage = 'Session Registration Created Successfully';
				
				List<Session_Registration__c> thisNewSessionRegistration = [SELECT Id, Name, Status__c, First_Name__c, Last_Name__c, Event_Registration__c, Registration_Type__c
																																	FROM Session_Registration__c
																																	WHERE Id = :thisQRScannedResultWrapper.recordIdToRedirect LIMIT 1];
				if(thisNewSessionRegistration != null && !thisNewSessionRegistration.isEmpty())		{
					thisQRScannedResultWrapper.sessionRegistration = thisNewSessionRegistration[0];
				}										
			}
			else{
				thisQRScannedResultWrapper.recordIdToRedirect 	= thisSessionRegistration[0].Id;
				thisQRScannedResultWrapper.recordActionName 		=  'view';
				thisQRScannedResultWrapper.customSuccessMessage = 'Session Registration Status Updated Successfully';

				if(thisSessionRegistration[0].Status__c != null
					&& !sessionRegistartionStatusToUdpate.isEmpty()
					&& sessionRegistartionStatusToUdpate.containsKey(thisSessionRegistration[0].Status__c)){
						thisSessionRegistration[0].Status__c = sessionRegistartionStatusToUdpate.get(thisSessionRegistration[0].Status__c);
						thisQRScannedResultWrapper.sessionRegistration = thisSessionRegistration[0];
						sobjectListToUpdate.add(thisSessionRegistration[0]);
				}
				else if(thisSessionRegistration[0].Status__c == ct_EventConstants.SESSION_REGISTRATION_CHECKED_IN){
					thisQRScannedResultWrapper.isCustomError = true;
					thisQRScannedResultWrapper.sessionRegistration = thisSessionRegistration[0];
					thisQRScannedResultWrapper.customErrorMessage = 'ERROR : Session Registration already set to Checked / In';
				}
			}
		}
			update sobjectListToUpdate;
			return thisQRScannedResultWrapper;
		}
		catch(Exception e){
			//Exception mechanism to log any exceptions occured during the dml operation
			ct_Logger.logMessage(e, 'Event Registration Check In / Check Out');
			throw new AuraHandledException('Error '+ e.getMessage());
		}
	}


	/**
	* @description If the user enters the Unregistered Session then create new Session registration
	* @param sessionId Session record Id
	* @param thisEventReg Event Registration Id
	* @return String 
	**/
	global static String createSessionRegistration(String sessionId, Event_Registration__c thisEventReg){
		Session_Registration__c thisWalkInSessionReg 	= new Session_Registration__c();
		thisWalkInSessionReg.Event_Registration__c		= thisEventReg.Id;
		thisWalkInSessionReg.QR_Code__c								= thisEventReg.QR_Code__c;
		thisWalkInSessionReg.Session__c								= sessionId;
		//Update the Session walk in true, since the user entered the session without registering by them
		thisWalkInSessionReg.Session_Walk_In__c				= true;
		thisWalkInSessionReg.Status__c								= ct_EventConstants.SESSION_REGISTRATION_CHECKED_IN;
		insert thisWalkInSessionReg;
		return thisWalkInSessionReg.Id;
	}

	/**
	* @description Method to update the event registration record details if it is the registration type was Unknown guest and have provide the details
	* @param thisEventReg Event registration Details in JSON string
	* @return Event_Registration__c 
	**/
	@AuraEnabled
	global static Event_Registration__c updateEventResgistration(String thisEventReg){
		try{
			Event_Registration__c thisEventRegistration = (Event_Registration__c)JSON.deserialize(thisEventReg, Event_Registration__c.class);
			thisEventRegistration.Registration_Type__c = ct_EventConstants.EVENT_REGISTRATION_TYPE_SOMEONE_ELSE;
			update thisEventRegistration;
			return thisEventRegistration;
		}
			catch(Exception e){
			//Exception mechanism to log any exceptions occured during the dml operation
			ct_Logger.logMessage(e, 'Event Registration Update as Named Attendee');
			throw new AuraHandledException('Error '+ e.getMessage());
		}
	}

	/**
	* @description Method to get event and session record 
	* @param eventId Event record Id	
	* @param sessionId Session record Id
	* @return RecordWrapper 
	**/
	@AuraEnabled
	global static RecordWrapper  getEventRecord(String eventId, String sessionId){
		Event__c thisEvent = [SELECT Id, Name FROM Event__c WHERE Id =: eventId LIMIT 1];
		Session__c thisSession = new Session__c();
		if(String.isNotBlank(sessionId)){
			thisSession = [SELECT Id, Name FROM Session__c WHERE Id =: sessionId LIMIT 1];
		}
		RecordWrapper thisRecordWrapper = new RecordWrapper();
		thisRecordWrapper.eventRecord = thisEvent;
		thisRecordWrapper.sessionRecord = thisSession;
		return thisRecordWrapper;
	}

	//Wrapper class for storing Event / Session record 
	global class RecordWrapper{
		@AuraEnabled
		global Event__c eventRecord {get;set;}
    @AuraEnabled
		global Session__c sessionRecord {get;set;}
		RecordWrapper(){
			eventRecord 	= new Event__c();
			sessionRecord = new Session__c();
		}
	}

	//Initial wrapper for Check in Manager
	global class InitialWrapper{
		@AuraEnabled
		global Boolean hasExistingConfiguration {get;set;}
    @AuraEnabled
		global String currentSession {get;set;}
		@AuraEnabled
		global List<String> configuredSessions {get;set;}
		@AuraEnabled
		global Id userConfigRecordId {get;set;}
		@AuraEnabled
		global Id configuredEventId {get;set;}
		@AuraEnabled
		global String configuredEventName {get;set;}
		@AuraEnabled
		global String configuredSessionName {get;set;}
		@AuraEnabled
		global Boolean isMainEntrance {get;set;}
		InitialWrapper(){
			hasExistingConfiguration = false;
			configuredSessions = new List<String>();
		}
	}

	//Wrapper class for storing  Event and Session configuration 
	global class EventSessionDetailsWrapperInitialWrapper{
		@AuraEnabled
		global List<EventSessionDetailsWrapper> eventOptions                	{get;set;}
		@AuraEnabled
		global Map<String, List<EventSessionDetailsWrapper>> sessionOptions		{get;set;}
	}

	//Wrapper class returned after QR scan is done
	global class QRScannedResultWrapper{
		@AuraEnabled
		global String recordIdToRedirect		               	{get;set;}
		@AuraEnabled
		global String recordActionName		                	{get;set;}
		@AuraEnabled
		global String customErrorMessage     	             	{get;set;}
		@AuraEnabled
		global String customSuccessMessage     	           	{get;set;}
		@AuraEnabled
		global Boolean isCustomError        		           	{get;set;}
		@AuraEnabled
		global Event_Registration__c eventRegistration      {get;set;}
		@AuraEnabled
		global Session_Registration__c sessionRegistration  {get;set;}
	}

	/**
	* Wrapper that contains Picklist Values
	*/
  global class EventSessionDetailsWrapper{
    @AuraEnabled
    global String label                  {get;set;}
    @AuraEnabled
		global string value                  {get;set;}
		@AuraEnabled
		global Boolean isSelected             {get;set;}
		@AuraEnabled
    global Boolean isCurrentSession       {get;set;}
		
		global EventSessionDetailsWrapper(){
      
		}
    global EventSessionDetailsWrapper(String entryLabel, String entryValue, Boolean isSelect){
      this.label    	= entryLabel;
			this.value   	 	= entryValue;
			this.isSelected = isSelect;
		}
	}
}