force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <defaultValue>TIMEVALUE(&quot;12:00:00.000&quot;)</defaultValue>
    <description>The time the event is due to finish</description>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Description__c.field-meta.xml
<CustomField>
    <fullName>Event_Description__c</fullName>
    <inlineHelpText>255 characters are allowed on this field.</inlineHelpText>
    <label>Event Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_End_Date__c</fullName>
    <label>Event End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Start_Date__c</fullName>
    <label>Event Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Social_App_Visibility__c.field-meta.xml
<CustomField>
    <fullName>Social_App_Visibility__c</fullName>
    <label>Social App Visibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Visible</fullName>
            </value>
            <value>
                <fullName>Invisible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <defaultValue>TIMEVALUE(&quot;12:00:00.000&quot;)</defaultValue>
    <description>The time the event is due to start</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Success_Message__c.field-meta.xml
<CustomField>
    <fullName>Success_Message__c</fullName>
    <description>Success message shown in event booking confirmation</description>
    <inlineHelpText>Event Booking confirmation Message</inlineHelpText>
    <label>Success Message</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Visible_Social_App__c.field-meta.xml
<CustomField>
    <fullName>Visible_Social_App__c</fullName>
    <label>Visible Social App</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Social_App_Visibility__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Linkedin</fullName>
            </value>
            <value>
                <fullName>Twitter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Web_Event_Location__c.field-meta.xml
<CustomField>
    <fullName>Web_Event_Location__c</fullName>
    <inlineHelpText>Please enter the display location that you wish to show people booking via the Event Registration Page e.g. Launch ED Campus, Virtual Event, Halpern House etc.</inlineHelpText>
    <label>Web Event Location(s)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Web_Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Web_Event_Name__c</fullName>
    <inlineHelpText>Please enter the display name that you wish to show people booking via the Event Registration page</inlineHelpText>
    <label>Web Event Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Web_Event_Pricing__c.field-meta.xml
<CustomField>
    <fullName>Web_Event_Pricing__c</fullName>
    <inlineHelpText>Please select an option to show to users whether this event is entirely free to attend, a paid event or has a mix of free and paid tickets</inlineHelpText>
    <label>Web Event Pricing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Free Event</fullName>
            </value>
            <value>
                <fullName>Paid Event</fullName>
            </value>
            <value>
                <fullName>Free &amp; Paid Tickets</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Order__c/Event_Order__c.object-meta.xml
<CustomObject>
    <label>Event Order</label>
    <nameField>
        <displayFormat>O - {00000000}</displayFormat>
        <label>Event Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Order__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Ticket_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/QR_Code__c.field-meta.xml
<CustomField>
    <fullName>QR_Code__c</fullName>
    <label>QR Code</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/QR_Code_URL__c.field-meta.xml
<CustomField>
    <fullName>QR_Code_URL__c</fullName>
    <label>QR Code URL</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Event_Product__c/Event_Product__c.object-meta.xml
<CustomObject>
    <label>Event Product</label>
    <nameField>
        <label>Event Product	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Product__c/fields/Enable_Session_Registrations__c.field-meta.xml
<CustomField>
    <fullName>Enable_Session_Registrations__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enable Session Registrations after Event order Booking is successfull</description>
    <inlineHelpText>Enable Session Registrations</inlineHelpText>
    <label>Enable Session Registrations</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Product__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Product__c/fields/Event_Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Event_Product_Description__c</fullName>
    <description>This is the information about the Event Product which will be shown up on Event Web Page.</description>
    <inlineHelpText>Please provide a description of this event product. The value entered will be visible to people via the web event registration process.</inlineHelpText>
    <label>Event Product Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <displayFormat>REG-{0000000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Event_Order__c.field-meta.xml
<CustomField>
    <fullName>Event_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Order</label>
    <referenceTo>Event_Order__c</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Event_Product__c.field-meta.xml
<CustomField>
    <fullName>Event_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Product</label>
    <referenceTo>Event_Product__c</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Formula Field For combining First name and Last Name to be used in SOQL Query</description>
    <formula>First_Name__c + &quot; &quot; +  Last_Name__c</formula>
    <inlineHelpText>Event Registration Name</inlineHelpText>
    <label>Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/QR_Code__c.field-meta.xml
<CustomField>
    <fullName>QR_Code__c</fullName>
    <description>Event Registration QR Code</description>
    <inlineHelpText>Event Registration QR Code</inlineHelpText>
    <label>QR Code</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/QR_Code_URL__c.field-meta.xml
<CustomField>
    <fullName>QR_Code_URL__c</fullName>
    <description>Field to store QR Code Data which is rendered as QR Code</description>
    <inlineHelpText>Field to store QR Code Data which is rendered as QR Code</inlineHelpText>
    <label>QR Code URL</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Registration_Type__c</fullName>
    <label>Registration Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Complementary - Speaker</fullName>
            </value>
            <value>
                <fullName>Complementary - Vendor</fullName>
            </value>
            <value>
                <fullName>Complementary - Prospect</fullName>
            </value>
            <value>
                <fullName>Complementary - Media</fullName>
            </value>
            <value>
                <fullName>Myself</fullName>
            </value>
            <value>
                <fullName>Someone Else</fullName>
            </value>
            <value>
                <fullName>Unknown Guest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ct_EventBookingConfirmationController.cls
/**
 * @description       : Using this class to fetch Event and Event Registration records to show in the Order Confirmation page
 * @author            : Creation Admin
 * @last modified on  : 15-09-2021
 * @last modified by  : Rajeshkumar
 * Modifications Log 
 * Ver   Date         Author           Modification
 * 1.0   10-27-2020   Creation Admin   Initial Version
**/
global without sharing class ct_EventBookingConfirmationController {

	@AuraEnabled
	global static String getRecordTypeDevNameById(String recordTypeId) {
		return [Select DeveloperName From RecordType Where Id =: recordTypeId limit 1].DeveloperName;
	}

	
	@AuraEnabled
  global static initialWrapper getInitialWrapper(String eventOrderId, String asperatoId){	
		try{
			if(!String.isEmpty(asperatoId)){
				Event_Order__c thisEventOrder = [SELECT Id /*, Asperato_Payment__c*/ FROM Event_Order__c /*WHERE Asperato_Payment__c =:asperatoId*/];
				eventOrderId = thisEventOrder.Id;
			}
			initialWrapper thisInitialWrapper 										= new initialWrapper();
			if(!String.isEmpty(eventOrderId)){
					thisInitialWrapper.eventRegistrations									= getEventRegistrationRecords(eventOrderId);
				thisInitialWrapper.isSessionRegistrationAvailable			= false;
				if(!thisInitialWrapper.eventRegistrations.isEmpty() && thisInitialWrapper.eventRegistrations.size() > 0){
					system.debug('thisInitialWrapper.eventRegistrations[0].Event__c>>>'+thisInitialWrapper.eventRegistrations[0].Id);
					system.debug('thisInitialWrapper.eventRegistrations[0].Event__c>>>'+thisInitialWrapper.eventRegistrations[0].Event__c);
					thisInitialWrapper.eventRecord										= getEventRecord(thisInitialWrapper.eventRegistrations[0].Event__c);
					system.debug('thisInitialWrapper.eventRecord>>>'+thisInitialWrapper.eventRecord);
					thisInitialWrapper.isSessionRegistrationAvailable = getSessionRegistrationEnabledProduct(thisInitialWrapper.eventRegistrations[0].Event__c, eventOrderId);
				}
			}
			
			return thisInitialWrapper;
		}
		catch(Exception e){
			//Exception mechanism to log any exceptions occured during the dml operation
			ct_Logger.logMessage(e, 'Event Booking Confirmation Get Initial Wrapper');
			throw new AuraHandledException('Error '+ e.getMessage());    
		}
	}

	@AuraEnabled
  global static Boolean getSessionRegistrationEnabledProduct(String eventId, String eventOrderId){	
		List<Event_Registration__c> sessionRegEnabledRegistrations = new List<Event_Registration__c>();
		
			sessionRegEnabledRegistrations =[SELECT Id, Event__c, Event_Order__c, Event_Product__c, Event_Product__r.Enable_Session_Registrations__c
																				FROM Event_Registration__c
																				WHERE Event__c =:eventId
																				AND Event_Order__c=:eventOrderId
																				AND Event_Product__r.Enable_Session_Registrations__c = true];

		return (!sessionRegEnabledRegistrations.isEmpty() && sessionRegEnabledRegistrations.size() > 0 ) ? true : false;
	}


	@AuraEnabled
  global static Event__c getEventRecord(String eventId){	
		return [Select Id, Name, Success_Message__c, Event_Description__c,Social_App_Visibility__c,Visible_Social_App__c,Web_Event_Name__c, Web_Event_Location__c, Event_Start_Date__c,Event_End_Date__c, 
                                        FORMAT(Start_Time__c), FORMAT(End_Time__c), Web_Event_Pricing__c, RecordTypeId from Event__c where Id=: eventId];
	}

	@AuraEnabled
  global static List<Event_Registration__c> getEventRegistrationRecords(String eventOrderId){	
		try{
			List<Event_Registration__c> eventRegistrationList = new List<Event_Registration__c>();
			system.debug('eventOrderId>>>>>>>>>>>>>?>'+eventOrderId);
			eventRegistrationList = [SELECT 
																Id, 
																Name,
																Registration_Type__c, 
																Name__c, 
																QR_Code__c,
																Event__c, 
																Event_Product__c,
																Event_Product__r.Event_Product_Description__c,
																Event_Product__r.Enable_Session_Registrations__c,
																Event_Product__r.Name,
																First_Name__c, Last_Name__c, 
																Event_Order__c,
																QR_Code_URL__c,
																Event_Order__r.Name 
															FROM Event_Registration__c 
															WHERE Name != null
															AND Event_Order__c =: eventOrderId
															ORDER BY Name];
			
			return eventRegistrationList;
		}
		catch(Exception e){
			//Exception mechanism to log any exceptions occured during the dml operation
			ct_Logger.logMessage(e, 'Event Booking Confirmation Get tickets');
			throw new AuraHandledException('Error '+ e.getMessage());    
		}
	}
	
	global class initialWrapper{
		@AuraEnabled
		global List<Event_Registration__c> eventRegistrations                	{get;set;}
		@AuraEnabled
		global Boolean isSessionRegistrationAvailable               				 	{get;set;}
		@AuraEnabled
		global Event__c eventRecord                                  				 	{get;set;}
		
	}
}