force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <defaultValue>TIMEVALUE(&quot;12:00:00.000&quot;)</defaultValue>
    <description>The time the event is due to finish</description>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <defaultValue>TIMEVALUE(&quot;12:00:00.000&quot;)</defaultValue>
    <description>The time the event is due to start</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Venue__c.field-meta.xml
<CustomField>
    <fullName>Venue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Venue</label>
    <referenceTo>Venue__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <displayFormat>REG-{0000000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/QR_Code__c.field-meta.xml
<CustomField>
    <fullName>QR_Code__c</fullName>
    <description>Event Registration QR Code</description>
    <inlineHelpText>Event Registration QR Code</inlineHelpText>
    <label>QR Code</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Primary Session the individual is interested in attending</description>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Venue__c.field-meta.xml
<CustomField>
    <fullName>Venue__c</fullName>
    <label>Venue</label>
    <referenceTo>Venue__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Capacity_Session_Full__c.field-meta.xml
<CustomField>
    <fullName>Capacity_Session_Full__c</fullName>
    <formula>Registered_Session__c / Maximum_Registration_Session__c</formula>
    <label>Capacity Full</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Enable_Waiting_List_on_Closed__c.field-meta.xml
<CustomField>
    <fullName>Enable_Waiting_List_on_Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Waiting List on Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description>The end time of a session</description>
    <label>Session End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>This associates a Session to an Event</description>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Final_Booking_Date__c.field-meta.xml
<CustomField>
    <fullName>Final_Booking_Date__c</fullName>
    <description>This field is used to determine the final booking date for this registration</description>
    <inlineHelpText>Please choose a valid date</inlineHelpText>
    <label>Final Booking Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Registration_Closed__c.field-meta.xml
<CustomField>
    <fullName>Registration_Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to determine whether the registration is closed or not</description>
    <inlineHelpText>Please check if you want to close this registration</inlineHelpText>
    <label>Registration Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Abstract__c.field-meta.xml
<CustomField>
    <fullName>Session_Abstract__c</fullName>
    <inlineHelpText>This description is shown to prospective attendees on the Session Registration UI</inlineHelpText>
    <label>Session Description</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Display_Name__c.field-meta.xml
<CustomField>
    <fullName>Session_Display_Name__c</fullName>
    <description>This field is used to store the Session Display</description>
    <inlineHelpText>The Session Display name is shown to prospective attendees via Session Registration UI &amp; also on the dynamic session picklist</inlineHelpText>
    <label>Session Display Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_Start_Date__c</fullName>
    <description>Session Start Date</description>
    <inlineHelpText>Session Start Date</inlineHelpText>
    <label>Session Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>The start time of a session</description>
    <label>Session Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Track__c.field-meta.xml
<CustomField>
    <fullName>Track__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Track</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Track__c.Event__c</field>
            <operation>equals</operation>
            <valueField>$Source.Event__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Track__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Venue__c.field-meta.xml
<CustomField>
    <fullName>Venue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Venue</label>
    <referenceTo>Venue__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Waiting_List_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Waiting_List_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Waiting List Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/Session_Registration__c.object-meta.xml
<CustomObject>
    <label>Session Registration</label>
    <nameField>
        <displayFormat>SAR - {00000}</displayFormat>
        <label>Session Registration Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Registration__c/fields/Event_Registration__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Registration</label>
    <referenceTo>Event_Registration__c</referenceTo>
    <relationshipName>Session_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/fields/QR_Code__c.field-meta.xml
<CustomField>
    <fullName>QR_Code__c</fullName>
    <description>Session Registration QR Code</description>
    <inlineHelpText>Session Registration QR Code</inlineHelpText>
    <label>QR Code</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipName>Session_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting List</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Attended / Checked In</fullName>
            </value>
            <value>
                <fullName>Attended / Checked Out</fullName>
            </value>
            <value>
                <fullName>Did Not Attend</fullName>
                <color>#A845DC</color>
                <label>Did Not Attend</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <color>#E27001</color>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Attending</fullName>
                <isActive>false</isActive>
                <label>Attending</label>
            </value>
            <value>
                <fullName>Checked In</fullName>
                <isActive>false</isActive>
                <label>Checked In</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Track__c/Track__c.object-meta.xml
<CustomObject>
    <label>Track</label>
    <nameField>
        <label>Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Tracks</relationshipLabel>
    <relationshipName>Tracks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Venue__c/Venue__c.object-meta.xml
<CustomObject>
    <label>Venue</label>
    <nameField>
        <label>Venue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Venues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ct_SessionRegistrationController.cls
/**
 * @description       : Use this controller to show Sessions data in the Session Registration UI
 * @author            : Creation Admin
 * @last modified on  : 01-13-2021
 * @last modified by  : Creation Admin
 * Modifications Log 
 * Ver   Date         Author           Modification
 * 1.0   08-11-2020   Creation Admin   Initial Version
**/
global without sharing class ct_SessionRegistrationController {
    global static PageData data;

    @auraEnabled
    global static PageData getSessions(String recordId, String bySessionName){

        Map<Id, Session_Registration__c> mapSessionToRegStatus = new Map<Id, Session_Registration__c>();

        for(Session_Registration__c thisSessionReg : [SELECT Id, Status__c, Session__c FROM Session_Registration__c WHERE Event_Registration__c =:recordId]){
            mapSessionToRegStatus.put(thisSessionReg.Session__c, thisSessionReg);
        }

        // get event registration record first
        Event_Registration__c evtReg = [Select Id, Event__c From Event_Registration__c Where Id=: recordId];
        
        // init target data structure
        data = new PageData();
        data.eventId = evtReg.Event__c;
        data.listTracks = [SELECT Id, Name, Event__c FROM Track__c WHERE Event__c =: evtReg.Event__c];
        Id parentEventId = evtReg.Event__c;
        data.lstSessions = new List<SessionWrapper>();

        String queryString = 'Select Id, Session_Display_Name__c,Session_Abstract__c,Name, Session_Start_Date__c,Final_Booking_Date__c,Waiting_List_Enabled__c,Enable_Waiting_List_on_Closed__c,Registration_Closed__c, Room__c, Room__r.Name, Venue__c, Venue__r.Name, Start_Time__c, Track__c, End_Time__c,Event__c, Capacity_Session_Full__c From Session__c WHERE Id !=null';

        if(String.isNotBlank(recordId)){
          queryString = queryString + ' AND  Event__c =:parentEventId';
        }
        if(String.isNotBlank(bySessionName)){
          String bySessName =  '%'+bySessionName+'%';
          queryString = queryString + ' AND Session_Display_Name__c LIKE :bySessName';
        }
       
        queryString = queryString + ' ORDER BY Session_Start_Date__c, Start_Time__c ASC NULLS LAST';
        for(Session__c session : Database.query(queryString)) {
            
            Boolean registrationStatus = false;
            Id sessionRegId = null;
            Boolean isWaitingListEnabled = false;
            String sessionRegistrationStatus;
            Boolean isOnWaitingList = false;
            if(mapSessionToRegStatus.containsKey(session.Id)){
              registrationStatus = mapSessionToRegStatus.get(session.Id).Status__c == 'Registered' ? true : false;
              sessionRegId = mapSessionToRegStatus.get(session.Id).Id;
              isWaitingListEnabled = session.Waiting_List_Enabled__c;
              isOnWaitingList = mapSessionToRegStatus.get(session.Id).Status__c == 'Waiting List' && session.Waiting_List_Enabled__c ? true : false;
            }
            data.lstSessions.add(new SessionWrapper(session, false, registrationStatus, sessionRegId,isWaitingListEnabled, isOnWaitingList ));			
        }
       
        return data;
    }

    @AuraEnabled
    global static String createSessionReg(String jsonData, String evtRegId,  Boolean isRegistering, Boolean isWaitingListEnabled){
      Session_Registration__c sessionReg = new Session_Registration__c();
      SessionWrapper sessionwrpr;
     try{
        Event_Registration__c thisEvent = getEventRegistration(Id.valueOf(evtRegId));
          sessionwrpr = (SessionWrapper)JSON.deserialize(jsonData, SessionWrapper.class);              
          sessionReg.Id = sessionwrpr.sessionRegId;
          sessionReg.Event_Registration__c = evtRegId;
          sessionReg.QR_Code__c = thisEvent.QR_Code__c;
          
         if(String.isBlank(sessionwrpr.sessionRegId)){
             sessionReg.Session__c = sessionwrpr.session.Id;
         }
         if(isRegistering && !isWaitingListEnabled){
             sessionReg.Status__c = 'Registered';
         }else if(isRegistering && isWaitingListEnabled){
             sessionReg.Status__c = 'Waiting List';
         }else{
             sessionReg.Status__c = 'Cancelled';
         }
         
        upsert sessionReg;
        }   
        catch(exception ex){
            return ex.getMessage();
        }
        return String.valueOf(isRegistering)+'-'+sessionwrpr.session.Track__c;
    }

    global static Event_Registration__c getEventRegistration(Id eventRegistrationId){
      return [SELECT Id, Name, QR_Code__c FROM Event_Registration__c WHERE Id =: eventRegistrationId];
    }

    global class PageData {
        @auraEnabled global List<SessionWrapper> lstSessions {get; set;} 
        @auraEnabled global List<Track__c> listTracks {get;set;}
        @auraEnabled global String eventId {get; set;}
    }
    
    global class SessionWrapper {
        @auraEnabled global Session__c session {get; set;} 
        @auraEnabled global boolean selected {get; set;}
        @auraEnabled global boolean isRegistered {get; set;}
        @auraEnabled global boolean isSessionEnded {get; set;}
        @auraEnabled global String sessionDuration {get;set;}
        @auraEnabled global String sessionStartTime {get;set;}
        @auraEnabled global String sessionStartDate {get;set;}
        @auraEnabled global Id sessionRegId {get;set;}
        @auraEnabled global boolean isWaitingListEnabled {get;set;}
        @auraEnabled global boolean isOnWaitingList {get;set;}

        global SessionWrapper(Session__c session, boolean selected, Boolean registered, Id sessionRegId, boolean isWaitingListEnabled, boolean isOnWaitingList) {
            this.session = session;
            this.selected = selected;
            this.isRegistered = registered;
            this.sessionRegId = sessionRegId;
            this.isOnWaitingList = isOnWaitingList; 
            if(session != null && session.Start_Time__c != null && session.End_Time__c != null){
              Integer startMinutes = (session.Start_Time__c.hour() * 60)+session.Start_Time__c.minute();
              Integer endMinutes = (session.End_Time__c.hour() * 60)+session.End_Time__c.minute();
              this.sessionDuration = (endMinutes - startMinutes)+' min';
              this.sessionStartTime = convertTimeFormat(session.Start_Time__c);  
            }
            sessionStartDate = session.Session_Start_Date__c != null ? String.valueOf(session.Session_Start_Date__c) : null;            
            this.isSessionEnded = session.Registration_Closed__c == true && session.Waiting_List_Enabled__c == false ? true : false;
            this.isWaitingListEnabled = !this.isRegistered && !this.isOnWaitingList && session.Registration_Closed__c == true && session.Enable_Waiting_List_on_Closed__c == true && session.Capacity_Session_Full__c == 100 && session.Waiting_List_Enabled__c ? true : false;       
        }
    }
    //description: Convering time from 24 hours to 12 hours format
    global static String convertTimeFormat(Time startTime){
        Integer hours= startTime.hour();
        Integer minutes= startTime.minute();
        String AMORPM = hours >= 12 ? 'pm': 'am';
        if(hours >12){
           hours = math.mod(hours, 12); 
        }
        String thisMinutes = minutes>=10 ? String.valueOf(minutes):'0'+minutes;
        return hours + '.' + thisMinutes + AMORPM;
    }
}