force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <defaultValue>TIMEVALUE(&quot;12:00:00.000&quot;)</defaultValue>
    <description>The time the event is due to finish</description>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Description__c.field-meta.xml
<CustomField>
    <fullName>Event_Description__c</fullName>
    <inlineHelpText>255 characters are allowed on this field.</inlineHelpText>
    <label>Event Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_End_Date__c</fullName>
    <label>Event End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Start_Date__c</fullName>
    <label>Event Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <defaultValue>TIMEVALUE(&quot;12:00:00.000&quot;)</defaultValue>
    <description>The time the event is due to start</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <description>This field is used to store the global timezone to be used in the AddToCalender functionality</description>
    <inlineHelpText>Please choose the appropriate time zone for this event.</inlineHelpText>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Africa/Algiers</fullName>
            </value>
            <value>
                <fullName>Africa/Cairo</fullName>
            </value>
            <value>
                <fullName>Africa/Johannesburg</fullName>
            </value>
            <value>
                <fullName>Africa/Nairobi</fullName>
            </value>
            <value>
                <fullName>America/Anchorage</fullName>
            </value>
            <value>
                <fullName>America/Argentina/Buenos_Aires</fullName>
            </value>
            <value>
                <fullName>America/Bogota</fullName>
            </value>
            <value>
                <fullName>America/Caracas</fullName>
            </value>
            <value>
                <fullName>America/Chicago</fullName>
            </value>
            <value>
                <fullName>America/Denver</fullName>
            </value>
            <value>
                <fullName>America/El_Salvador</fullName>
            </value>
            <value>
                <fullName>America/Halifax</fullName>
            </value>
            <value>
                <fullName>America/Indiana/Indianapolis</fullName>
            </value>
            <value>
                <fullName>America/Lima</fullName>
            </value>
            <value>
                <fullName>America/Los_Angeles</fullName>
            </value>
            <value>
                <fullName>America/Mexico_City</fullName>
            </value>
            <value>
                <fullName>America/New_York</fullName>
            </value>
            <value>
                <fullName>America/Panama</fullName>
            </value>
            <value>
                <fullName>America/Phoenix</fullName>
            </value>
            <value>
                <fullName>America/Puerto_Rico</fullName>
            </value>
            <value>
                <fullName>America/Santiago</fullName>
            </value>
            <value>
                <fullName>America/Sao_Paulo</fullName>
            </value>
            <value>
                <fullName>America/St_Johns</fullName>
            </value>
            <value>
                <fullName>America/Tijuana</fullName>
            </value>
            <value>
                <fullName>Asia/Baghdad</fullName>
            </value>
            <value>
                <fullName>Asia/Bangkok</fullName>
            </value>
            <value>
                <fullName>Asia/Colombo</fullName>
            </value>
            <value>
                <fullName>Asia/Dhaka</fullName>
            </value>
            <value>
                <fullName>Asia/Dubai</fullName>
            </value>
            <value>
                <fullName>Asia/Ho_Chi_Minh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Venue_Country__c.field-meta.xml
<CustomField>
    <fullName>Venue_Country__c</fullName>
    <formula>Venue__r.Country__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Venue Country</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Venue_State__c.field-meta.xml
<CustomField>
    <fullName>Venue_State__c</fullName>
    <formula>Venue__r.State__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Venue State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Venue_Street_Address_1__c.field-meta.xml
<CustomField>
    <fullName>Venue_Street_Address_1__c</fullName>
    <formula>Venue__r.Street_Address_1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Venue Street Address #1</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Venue_Street_Address_2__c.field-meta.xml
<CustomField>
    <fullName>Venue_Street_Address_2__c</fullName>
    <formula>Venue__r.Street_Address_2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Venue Street Address #2</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description>The end time of a session</description>
    <label>Session End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>This associates a Session to an Event</description>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_End_Date__c</fullName>
    <description>This field is used to record the session end date</description>
    <inlineHelpText>Please choose an appropriate end date for this session</inlineHelpText>
    <label>Session End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_Start_Date__c</fullName>
    <description>Session Start Date</description>
    <inlineHelpText>Session Start Date</inlineHelpText>
    <label>Session Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>The start time of a session</description>
    <label>Session Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Venue_City__c.field-meta.xml
<CustomField>
    <fullName>Venue_City__c</fullName>
    <formula>Venue__r.City__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Venue City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Venue_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Venue_Postal_Code__c</fullName>
    <formula>Venue__r.Postal_Code_Zip__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Venue Postal Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Venue_Street_Address_1__c.field-meta.xml
<CustomField>
    <fullName>Venue_Street_Address_1__c</fullName>
    <formula>Venue__r.Street_Address_1__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Venue Street Address 1</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Venue_Street_Address_2__c.field-meta.xml
<CustomField>
    <fullName>Venue_Street_Address_2__c</fullName>
    <formula>Venue__r.Street_Address_2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Venue Street Address 2</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CT_AddToCalendarController.cls
/**
 * @description       : Using to this controller class for Add the Event / Session in the user Calendar
 * @author            : Creation Admin
 * @last modified on  : 02-02-2021
 * @last modified by  : Creation Admin
 * Modifications Log 
 * Ver   Date         Author           Modification
 * 1.0   09-08-2020   Creation Admin   Initial Version
 * 2.0   2/2/2021     Creation Admin   updated the class to populate location with Street, City, state, country and Address 2
**/
global without sharing class CT_AddToCalendarController {
      /*
		* Description: Method to show the AddToCalendar functionality in the record if the record supports calendar functionality
	* */
    @AuraEnabled(cacheable=true)
    global static CT_Calendar getCalendar(String recordId) {
        if (String.isBlank(recordId)) {
            throw new CT_CalendarException('Add To Calendar - recordId is missing');
        }
        return getCalendarById(Id.valueOf(recordId));
    }    
    
    @TestVisible
    private static CT_Calendar getCalendarById(Id recordId) {
        CT_Calendar calendar;
        switch on recordId.getSobjectType().newSObject() {
            when Event__c event {
                event = fetchEventById(recordId);
                calendar = new CT_Calendar(event);
            } when Session__c session {
                session = fetchSessionById(recordId);
                calendar = new CT_Calendar(session);
            } when else {
                throw new CT_CalendarException('Add To Calendar - This object is not supported');
            }
        }
        return calendar;
    }
    /*
		* Description: Method to fetch the Event record details to add this as event in calendar
	* */
    @TestVisible
    private static Event__c fetchEventById(Id id) {
        return [SELECT Id, Name, Event_Description__c, Venue_City__c, Time_Zone__c,
        Event_Start_Date__c, Start_Time__c, Event_End_Date__c, End_Time__c,
        Venue_Street_Address_1__c, Venue_Street_Address_2__c , Venue_State__c,Venue_Postal_Code__c,Venue_Country__c
        FROM Event__c WHERE Id =: id];
    } 
     /*
		* Description: Method to fetch the Session record details to add this as event in calendar
	* */
    @TestVisible
    private static Session__c fetchSessionById(Id id) {
        return [SELECT Id, Name, Event__r.Event_Description__c, Event__r.Venue_City__c,
        Session_Start_Date__c, Session_End_Date__c, Start_Time__c, End_Time__c, Event__r.Time_Zone__c , Venue_City__c,Venue_Street_Address_1__c, Venue_Street_Address_2__c , Venue_State__c,Venue_Postal_Code__c,Venue_Country__c                
        FROM Session__c WHERE Id =: id];
    }

    global class CT_CalendarException extends Exception{}
    
    global class CT_Calendar {
        @AuraEnabled global String subject;
        @AuraEnabled global Datetime startDateTime;
        @AuraEnabled global Datetime endDateTime;
        @AuraEnabled global String description;
        @AuraEnabled global String location;
        @AuraEnabled global String timeZone;
        @AuraEnabled global String eventDuration;
        
        global CT_Calendar(Event__c event) {
           
            this.subject = event.Name;   
            if(event.Event_Start_Date__c != null && event.Start_Time__c != null){
                this.startDateTime = Datetime.newInstanceGMT(event.Event_Start_Date__c, event.Start_Time__c);
            }
            if(event.Event_End_Date__c != null && event.End_Time__c != null){
                this.endDateTime = Datetime.newInstanceGMT(event.Event_End_Date__c, event.End_Time__c);
            }
            this.timeZone = event.Time_Zone__c;
            this.description = event.Event_Description__c;
            // populate the location with Street, City, state, country and Address 2
            this.location ='';
            if(!String.isBlank(event.Venue_Street_Address_1__c)){this.location = this.location + event.Venue_Street_Address_1__c +',';}
            if(!String.isBlank(event.Venue_Street_Address_2__c)){this.location = this.location + event.Venue_Street_Address_2__c +',';}
            if(!String.isBlank(event.Venue_City__c)){this.location = this.location + event.Venue_City__c +',';}
            if(!String.isBlank(event.Venue_State__c)){this.location = this.location + event.Venue_State__c +',';}
            if(!String.isBlank(event.Venue_Postal_Code__c)){this.location = this.location + event.Venue_Postal_Code__c +',';}
            if(!String.isBlank(event.Venue_Country__c)){this.location = this.location + event.Venue_Country__c +',';}
            this.location = this.location.removeEnd(',');            
            this.eventDuration = getEventDuration(event.Start_Time__c, event.End_Time__c);
        }
         /*
		* Description: Method to assign the Event record details to the calendar
		* */
        global CT_Calendar(Session__c session) {
            this.subject = session.Name;
            if(session.Session_Start_Date__c != null && session.Start_Time__c != null){
              this.startDateTime = Datetime.newInstance(session.Session_Start_Date__c, session.Start_Time__c);
            }
            if(session.Session_Start_Date__c != null && session.End_Time__c != null){
              this.endDateTime = Datetime.newInstance(session.Session_Start_Date__c, session.End_Time__c);
            }
            this.timeZone = session.Event__r.Time_Zone__c;
            this.description = session.Event__r.Event_Description__c;
            this.location ='';
            if(!String.isBlank(session.Venue_Street_Address_1__c)){this.location = this.location + session.Venue_Street_Address_1__c +',';}
            if(!String.isBlank(session.Venue_Street_Address_2__c)){this.location = this.location + session.Venue_Street_Address_2__c +',';}
            if(!String.isBlank(session.Venue_City__c)){this.location = this.location + session.Venue_City__c +',';}
            if(!String.isBlank(session.Venue_State__c)){this.location = this.location + session.Venue_State__c +',';}
            if(!String.isBlank(session.Venue_Postal_Code__c)){this.location = this.location + session.Venue_Postal_Code__c +',';}
            if(!String.isBlank(session.Venue_Country__c)){this.location = this.location + session.Venue_Country__c +',';}
            this.location = this.location.removeEnd(',');
            this.eventDuration = getEventDuration(session.Start_Time__c, session.End_Time__c);
        }
		 /*
		* Description: Method to calulate the duration of the event /session
		* */
        global String getEventDuration(Time startTime, Time endTime){
          String totalDuration = '0000';
          if(startTime != null && endTime != null){
            String eventHours = String.valueOf(Math.abs(startTime.hour() - endTime.hour()));
            String totalHours = eventHours.length() == 1 ? '0'+eventHours : eventHours;
            String eventMinutes = String.valueOf(Math.abs(startTime.minute() - endTime.minute()));
            String totalMinutes = eventMinutes.length() == 1 ? '0'+eventMinutes : eventMinutes;
            totalDuration = totalHours+totalMinutes;
          }

          return totalDuration;
        }
    }
}