force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Event_Manager__c.field-meta.xml
<CustomField>
    <fullName>Event_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Manager_Refund_Notification_Email__c.field-meta.xml
<CustomField>
    <fullName>Event_Manager_Refund_Notification_Email__c</fullName>
    <description>This is controlling the event manager refund notification email process</description>
    <inlineHelpText>Please select &apos;On&apos; for event manager refund notification email receive</inlineHelpText>
    <label>Event Manager Refund Notification Email</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Email_Settings</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Order__c/Event_Order__c.object-meta.xml
<CustomObject>
    <label>Event Order</label>
    <nameField>
        <displayFormat>O - {00000000}</displayFormat>
        <label>Event Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Order__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Event Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Ticket_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/Event_Manager_Refund_Warning__c.field-meta.xml
<CustomField>
    <fullName>Event_Manager_Refund_Warning__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to determine whether an Event Manager Refund Warning needs to be sent</description>
    <inlineHelpText>This field is automated</inlineHelpText>
    <label>Event Manager Refund Warning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Payment</fullName>
            </value>
            <value>
                <fullName>Waiting List</fullName>
            </value>
            <value>
                <fullName>Waiting List Invitation</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/Paid_Order__c.field-meta.xml
<CustomField>
    <fullName>Paid_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Paid Order</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Email_Settings.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>On</fullName>
        <default>true</default>
        <label>On</label>
    </customValue>
    <customValue>
        <fullName>Off</fullName>
    </customValue>
    <description>Email process controlling based on On/Off</description>
    <masterLabel>Email Settings</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ct_Event_OrderTriggerHandler.cls
/**
 * @description       : EVENT ORDER Trigger Handler
 * @author            : Creation Admin
**/
global without sharing class ct_Event_OrderTriggerHandler  {

    // global override hed.TDTM_Runnable.DmlWrapper run(List<SObject> newlist, List<SObject> oldlist,
    // hed.TDTM_Runnable.Action triggerAction, Schema.DescribeSObjectResult objResult) {

    // System.debug('>>>>>>>>>>>>>>>>>>>>>>>>>>>CT EVENT ORDER TDTM TRIGGER HANDLER<<<<<<<<<<<<<<<<<<<<<<<<<<<');

    // hed.TDTM_Runnable.dmlWrapper dmlWrapper = new hed.TDTM_Runnable.DmlWrapper();

	  global static List<String> eventDetailsDataList = new List<String>();
    global static Set<Id> setIds = new Set<Id>();
    global static Set<Id> eventIds = new Set<Id>();

        // if (triggerAction == hed.TDTM_Runnable.Action.AfterInsert){
          //Loop to get The required Ids 
        
    global static void handleAfterInsert(list<Event_Order__c> newlist){
      for(Event_Order__c thisEventOrder : newlist){
        if(thisEventOrder.Order_Status__c == ct_EventConstants.EVENT_ORDER_WAITING_LIST){
          Map<String,String> orderMap = new Map<String,String>();
          orderMap.put('recId', thisEventOrder.Id);
          orderMap.put('firstName', thisEventOrder.First_Name__c);
          orderMap.put('lastName', thisEventOrder.Last_Name__c);
          orderMap.put('email', thisEventOrder.Email__c);
          
          String jsonStr = JSON.serialize(orderMap);
          System.debug('jsonStr'+jsonStr);
          eventDetailsDataList.add(jsonStr); 
        }
        if(thisEventOrder.Event__c != null 
            && (thisEventOrder.Order_Status__c == 'Waiting List' || thisEventOrder.Order_Status__c == 'Waiting List Invitation')
            ){
              eventIds.add(thisEventOrder.Event__c);
        }
      }
      if(!eventDetailsDataList.isEmpty()){
        //Triggers the Web site submission platform event
        System.debug('triggerwebsite--1');
        ct_EventOrderTriggerHandlerHelper.triggerWebSiteSubmissionPlatformEvent(eventDetailsDataList);
      }
      if(!eventIds.isEmpty()){
        //calculate the number of event order
        ct_EventOrderTriggerHandlerHelper.updateEventswithEvtOrdCount(eventIds);
      }
    }
    
        // Before Update Logic
        // if (triggerAction == hed.TDTM_Runnable.Action.BeforeUpdate){
    global static void handleBeforeUpdate(Map<Id,Event_Order__c> triggerOldMap, Map<Id,Event_Order__c> triggerNewMap){
    //  Map<Id, Event_Order__c> triggerOldMap = new Map<Id, Event_Order__c>((list<Event_Order__c>)oldlist);
    //  Map<Id, Event_Order__c> triggerNewMap = new Map<Id, Event_Order__c>((list<Event_Order__c>)newlist);

      for(Event_Order__c thisEventOrder : triggerNewMap.values()){
        //Check If Event Order Is Paid & Set To Cancelled
        if(thisEventOrder.Paid_Order__c && thisEventOrder.Order_Status__c == ct_EventConstants.EVENT_ORDER_STATUS_CANCELLED
        && !thisEventOrder.Event_Manager_Refund_Warning__c
        && triggerOldMap.get(thisEventOrder.Id).Order_Status__c != thisEventOrder.Order_Status__c){
          thisEventOrder.Event_Manager_Refund_Warning__c = true;
        }
      }  
    }
        // After Update logic
        // if (triggerAction == hed.TDTM_Runnable.Action.AfterUpdate){
    global static void handleAfterUpdate(Map<Id,Event_Order__c> triggerOldMap, Map<Id,Event_Order__c> triggerNewMap){
      // Map<Id, Event_Order__c> triggerOldMap = new Map<Id, Event_Order__c>((list<Event_Order__c>)oldlist);
      // Map<Id, Event_Order__c> triggerNewMap = new Map<Id, Event_Order__c>((list<Event_Order__c>)newlist);
      List<Event_Order__c> refundAlertEventOrderList = new List<Event_Order__c>();
      for(Event_Order__c thisEventOrder : [SELECT Id, Paid_Order__c, Order_Status__c, Event__r.Event_Manager__r.Email,
                                                  Event__r.Event_Manager_Refund_Notification_Email__c, Event_Manager_Refund_Warning__c
                                                  FROM Event_Order__c
                                                  WHERE Id IN: triggerNewMap.keySet()
                                                  AND Event_Manager_Refund_Warning__c = true]){
          //Check If It Is Paid Order & Event Status Is Set To Cancelled
          if(triggerOldMap.get(thisEventOrder.Id).Event_Manager_Refund_Warning__c != thisEventOrder.Event_Manager_Refund_Warning__c
            && thisEventOrder.Event__r.Event_Manager_Refund_Notification_Email__c == 'On'){
            refundAlertEventOrderList.add(thisEventOrder);
          }
      }
        // update event Order status
      for(Event_Order__c thisEventOrder : [SELECT Id, Paid_Order__c, Order_Status__c, Event__r.Event_Manager__r.Email,
                                                  Event_Manager_Refund_Warning__c
                                                  FROM Event_Order__c
                                                  WHERE Id IN: triggerNewMap.keySet()]){
          if(thisEventOrder.Event__c != null 
              && ((triggerOldMap.get(thisEventOrder.Id).Order_Status__c != 'Waiting List' 
                  && thisEventOrder.Order_Status__c == 'Waiting List')
              || (triggerOldMap.get(thisEventOrder.Id).Order_Status__c != 'Waiting List Invitation' 
                  && thisEventOrder.Order_Status__c =='Waiting List Invitation'))
          ){
              eventIds.add(thisEventOrder.Event__c);
          }
        }

      if(!refundAlertEventOrderList.isEmpty()){
        ct_EventOrderTriggerHandlerHelper.sendEventManagerRefundAlert(refundAlertEventOrderList);
      }
      if(!eventIds.isEmpty()){
        ct_EventOrderTriggerHandlerHelper.updateEventswithEvtOrdCount(eventIds);
      }
            
    }
        //Before Delete logic
        // if (triggerAction == hed.TDTM_Runnable.Action.BeforeDelete){
    global static void handleBeforeDelete(list<Event_Order__c> oldlist){
      System.debug('>>>>>>>>>>>>>>>>>>>>>>>>>>>EVENT ORDER AFTER INSERT TRIGGER<<<<<<<<<<<<<<<<<<<<<<<<<<<');
      for(Event_Order__c thisEventOrder : oldlist){
        if(thisEventOrder.Event__c != null 
          && (thisEventOrder.Order_Status__c == 'Waiting List' || thisEventOrder.Order_Status__c == 'Waiting List Invitation')
          ){
          eventIds.add(thisEventOrder.Event__c);
        }
      }
      if(!eventIds.isEmpty()){
        ct_EventOrderTriggerHandlerHelper.updateEventswithEvtOrdCount(eventIds);
      }
    }

  }