force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Event_Description__c.field-meta.xml
<CustomField>
    <fullName>Event_Description__c</fullName>
    <inlineHelpText>255 characters are allowed on this field.</inlineHelpText>
    <label>Event Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Social_App_Visibility__c.field-meta.xml
<CustomField>
    <fullName>Social_App_Visibility__c</fullName>
    <label>Social App Visibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Visible</fullName>
            </value>
            <value>
                <fullName>Invisible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Visible_Social_App__c.field-meta.xml
<CustomField>
    <fullName>Visible_Social_App__c</fullName>
    <label>Visible Social App</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Social_App_Visibility__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Linkedin</fullName>
            </value>
            <value>
                <fullName>Twitter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ShareEventWithSocialMedia.cls
/**
 * @description       : Controller class for Share Event in Social Media component for sharing the Event details in Social media platform
 * @author            : Creation Admin
 * @group             : 
 * @last modified on  : 02-03-2021
 * @last modified by  : Creation Admin
 * Modifications Log 
 * Ver   Date         Author           Modification
 * 1.0   02-03-2021   Creation Admin   Initial Version
**/
global without sharing class ShareEventWithSocialMedia {
	/**
	* @description Method to retrieve details about event record
	* @param recordId Event record ID
	* @return Event__c 
	**/
	@AuraEnabled(cacheable=true)
	global static Event__c getEventRec(String recordId){
		Event__c evt = [Select Id, Name, Event_Description__c,Social_App_Visibility__c,Visible_Social_App__c from Event__c where Id=: recordId];
		return evt;
	}
}