force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <defaultValue>TIMEVALUE(&quot;12:00:00.000&quot;)</defaultValue>
    <description>The time the event is due to finish</description>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <defaultValue>TIMEVALUE(&quot;12:00:00.000&quot;)</defaultValue>
    <description>The time the event is due to start</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <displayFormat>REG-{0000000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This allows an event registration to be associated to an Account</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Enquirer__c.field-meta.xml
<CustomField>
    <fullName>Enquirer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Enquirer that has registered for the Event</description>
    <label>Enquirer</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Event_Email__c.field-meta.xml
<CustomField>
    <fullName>Event_Email__c</fullName>
    <label>Event Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Primary Session the individual is interested in attending</description>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description>The end time of a session</description>
    <label>Session End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>This associates a Session to an Event</description>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_End_Date__c</fullName>
    <description>This field is used to record the session end date</description>
    <inlineHelpText>Please choose an appropriate end date for this session</inlineHelpText>
    <label>Session End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_Start_Date__c</fullName>
    <description>Session Start Date</description>
    <inlineHelpText>Session Start Date</inlineHelpText>
    <label>Session Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>The start time of a session</description>
    <label>Session Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/Session_Registration__c.object-meta.xml
<CustomObject>
    <label>Session Registration</label>
    <nameField>
        <displayFormat>SAR - {00000}</displayFormat>
        <label>Session Registration Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Registration__c/fields/Event_Registration__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Registration</label>
    <referenceTo>Event_Registration__c</referenceTo>
    <relationshipName>Session_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipName>Session_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/fields/Session_Reg_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Session_Reg_Email_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Set to &apos;True&apos; when Confirmation Email is sent.</description>
    <label>Session Reg Email Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ct_SessionRegistrationEmailController.cls
/**
 * @description: Class to send Email when Registered from waiting List for Session.
 * Created By: Creation Admin
 * Created Date : 14/12/2020
 **/
global without sharing class ct_SessionRegistrationEmailController {
    @InvocableMethod
    global static void sendEmailofSessionRegistrationConfimation(List<String> sessRegIds){
        Session_Registration__c sessReg = [Select Id, Session__c, Session__r.Name, Session__r.Session_Start_Date__c,Session__r.Session_End_Date__c,
                                           Session__r.Start_Time__c,Session__r.End_Time__c,Event_Registration__c,Event_Registration__r.Event_Email__c,
                                           Event_Registration__r.Enquirer__c,Event_Registration__r.Contact__c,Event_Registration__r.Account_Name__c,Event_Registration__r.Event__r.Name,Session_Reg_Email_Sent__c
                                           From Session_Registration__c Where Id =: sessRegIds];
        
        EmailTemplate et = [Select Id, Name,Subject,HtmlValue,Body,Markup From EmailTemplate Where Name =: 'Session Registration Confirmation Email'];
       
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        message.setTemplateId(et.Id);
        message.setToAddresses(new list<String>{String.valueOf(sessReg.Event_Registration__r.Event_Email__c)});
        message.setWhatId(sessReg.Id);
        if(sessReg.Event_Registration__r.Enquirer__c != null){
            message.setTargetObjectId(sessReg.Event_Registration__r.Enquirer__c);
        }
        /*if(sessReg.Event_Registration__r.Contact__c != null){
            message.setTargetObjectId(sessReg.Event_Registration__r.Contact__c);
        }*/
        if(sessReg.Event_Registration__r.Account_Name__c != null){
            message.setTargetObjectId(sessReg.Event_Registration__r.Account_Name__c);
        }
        message.setTreatTargetObjectAsRecipient(false);
        message.setSaveAsActivity(false);
        
        Messaging.SendEmailResult[] emailResult = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {message});
        if(!emailResult[0].isSuccess()){
            System.debug('Error :' +emailResult[0].getErrors());
        } else{
            System.debug('Success>>');
            sessReg.Session_Reg_Email_Sent__c = true;
            try{
                update sessReg;
            }
            catch(Exception e){
                ct_Logger.logMessage(e, 'Session Registration');
                throw e;
            }
        }
    }

}