force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <defaultValue>TIMEVALUE(&quot;12:00:00.000&quot;)</defaultValue>
    <description>The time the event is due to finish</description>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_End_Date__c</fullName>
    <label>Event End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Start_Date__c</fullName>
    <label>Event Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Final_Event_Registration_Date__c.field-meta.xml
<CustomField>
    <fullName>Final_Event_Registration_Date__c</fullName>
    <label>Final Web Event Registration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <defaultValue>TIMEVALUE(&quot;12:00:00.000&quot;)</defaultValue>
    <description>The time the event is due to start</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Web_Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Web_Event_Name__c</fullName>
    <inlineHelpText>Please enter the display name that you wish to show people booking via the Event Registration page</inlineHelpText>
    <label>Web Event Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Clone_Setting__mdt/Event_Clone_Setting__mdt.object-meta.xml
<CustomObject>
    <description>This object is introduced to track the events and events related fields</description>
    <label>Event Clone Setting</label>
    <pluralLabel>Event Clone Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Event_Clone_Setting__mdt/fields/Fields__c.field-meta.xml
<CustomField>
    <fullName>Fields__c</fullName>
    <description>This is to track the fields details</description>
    <label>Fields</label>
    <metadataRelationshipControllingField>Event_Clone_Setting__mdt.Object__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Event_Clone_Settings</relationshipLabel>
    <relationshipName>Event_Clone_Settings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Event_Clone_Setting__mdt/fields/Values__c.field-meta.xml
<CustomField>
    <fullName>Values__c</fullName>
    <description>This is to track the values of each field related to the object</description>
    <label>Values</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Product__c/Event_Product__c.object-meta.xml
<CustomObject>
    <label>Event Product</label>
    <nameField>
        <label>Event Product	 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Product__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description>The end time of a session</description>
    <label>Session End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>This associates a Session to an Event</description>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_End_Date__c</fullName>
    <description>This field is used to record the session end date</description>
    <inlineHelpText>Please choose an appropriate end date for this session</inlineHelpText>
    <label>Session End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_Start_Date__c</fullName>
    <description>Session Start Date</description>
    <inlineHelpText>Session Start Date</inlineHelpText>
    <label>Session Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>The start time of a session</description>
    <label>Session Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Track__c.field-meta.xml
<CustomField>
    <fullName>Track__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Track</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Track__c.Event__c</field>
            <operation>equals</operation>
            <valueField>$Source.Event__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Track__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Track__c/Track__c.object-meta.xml
<CustomObject>
    <label>Track</label>
    <nameField>
        <label>Track Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tracks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Track__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Tracks</relationshipLabel>
    <relationshipName>Tracks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ct_EventStructureCloneController.cls
/**
 * @description       : Clone Event based on values configured in the Event Clone Setting metadata type
 * @author            : Creation Admin
 * @last modified on  : 01-17-2021
 * @last modified by  : Creation Admin
 * Modifications Log 
 * Ver   Date         Author           Modification
 * 1.0   09-22-2020   Creation Admin   Initial Version
**/
global without sharing class ct_EventStructureCloneController {
   /*
	* Description: Clone the Event and related records with the values configured in the Event Clone Setting metadata type
	* */
	@AuraEnabled
	global static String cloneEventWithEventStructure(String eventId, String newEventDetails){	
		try{
			Map<String, Object> eventDetails =  (Map<String, Object>)JSON.deserializeUntyped(newEventDetails);
			
			//Clone the event
			Event__c thisEventToBeCloned 						=  Database.query('SELECT ' + ct_Util.getAllFieldsQueryStringForSObject('Event__c')+' FROM Event__c WHERE Id =: eventId LIMIT 1');
			Event__c thisClonedEvent 							= thisEventToBeCloned.clone(false, true, false, false);
			
			thisClonedEvent.Event_Start_Date__c                = Date.valueOf(String.valueOf(eventDetails.get('Event_Start_Date__c')));
			thisClonedEvent.Event_End_Date__c                  = (eventDetails.containsKey('Event_End_Date__c') && eventDetails.get('Event_End_Date__c') != null)  ? Date.valueOf(String.valueOf(eventDetails.get('Event_End_Date__c'))) : null;
			thisClonedEvent.Final_Event_Registration_Date__c   = thisClonedEvent.Event_Start_Date__c;
			thisClonedEvent.Start_Time__c                      = Datetime.valueOf(String.valueOf(eventDetails.get('Event_Start_Date__c')) + ' ' +String.valueOf(eventDetails.get('Start_Time__c'))).time();
			thisClonedEvent.End_Time__c                        = (eventDetails.containsKey('Event_End_Date__c') && eventDetails.get('Event_End_Date__c') != null && eventDetails.containsKey('End_Time__c') && eventDetails.get('End_Time__c') != null) ?  Datetime.valueOf(String.valueOf(eventDetails.get('Event_End_Date__c')) + ' ' +String.valueOf(eventDetails.get('End_Time__c'))).time() : null;
			thisClonedEvent.Name                               = thisClonedEvent.Name + ' - Clone';
			thisClonedEvent.Web_Event_Name__c                  = thisClonedEvent.Name + ' - Clone';
			//Calling metaDataValues method to get fields and values for event
			prePopulateValueFromCloneMetadata(thisClonedEvent, ct_MetadataService.getEventCloneSettingByObjectName('Event__c'));

			insert thisClonedEvent;
			Map<String, Track__c> clonedTrackToBeInserted = new Map<String, Track__c>();
			List<SObject> sobjectListToInsert = new List<SObject>();
            
			for(Track__c thisTrackToBeCloned : Database.query('SELECT ' + ct_Util.getAllFieldsQueryStringForSObject('Track__c')+' FROM Track__c WHERE Event__c =: eventId')){
				Track__c thisClonedTrack = thisTrackToBeCloned.clone(false, true, false, false);
				thisClonedTrack.Event__c = thisClonedEvent.Id;
				//Calling metaDataValues method to get fields and values for track				
				prePopulateValueFromCloneMetadata(thisClonedTrack, ct_MetadataService.getEventCloneSettingByObjectName('Track__c'));

				clonedTrackToBeInserted.put(thisTrackToBeCloned.Id, thisClonedTrack);	
			}
			
			insert clonedTrackToBeInserted.values();

			for(Event_Product__c thisEventProductToClone : Database.query('SELECT ' + ct_Util.getAllFieldsQueryStringForSObject('Event_Product__c')+' FROM Event_Product__c WHERE Event__c =: eventId')){
				Event_Product__c thisEventProduct = thisEventProductToClone.clone(false, true, false, false);
				thisEventProduct.Event__c 				= thisClonedEvent.Id;
				//Calling metaDataValues method to get fields and values for event product
				prePopulateValueFromCloneMetadata(thisEventProduct, ct_MetadataService.getEventCloneSettingByObjectName('Event_Product__c'));
				sobjectListToInsert.add(thisEventProduct);
			}

			for(Session__c thisSessionToBeCloned : Database.query('SELECT ' + ct_Util.getAllFieldsQueryStringForSObject('Session__c')+' FROM Session__c WHERE Event__c =: eventId')){
				Session__c thisClonedSession = thisSessionToBeCloned.clone(false, true, false, false);
				if(!clonedTrackToBeInserted.isEmpty()
					&& clonedTrackToBeInserted.containsKey(thisSessionToBeCloned.Track__c)){
					thisClonedSession.Track__c                 = clonedTrackToBeInserted.get(thisSessionToBeCloned.Track__c).Id;
					}

					thisClonedSession.Event__c                 = thisClonedEvent.Id;
					thisClonedSession.Session_Start_Date__c    = thisClonedEvent.Event_Start_Date__c;
					thisClonedSession.Start_Time__c            = thisSessionToBeCloned.Start_Time__c;
					thisClonedSession.Session_End_Date__c      = thisClonedEvent.Event_End_Date__c;
					thisClonedSession.End_Time__c              = thisSessionToBeCloned.End_Time__c;
					//Calling metaDataValues method to get fields and values for session
					prePopulateValueFromCloneMetadata(thisClonedSession, ct_MetadataService.getEventCloneSettingByObjectName('Session__c'));

					sobjectListToInsert.add(thisClonedSession);
				
			}
	
            insert sobjectListToInsert;
			return thisClonedEvent.Id;
		}
		catch(Exception e){
			//Exception mechanism to log any exceptions occured during the dml operation
			ct_Logger.logMessage(e, 'Event & Event Structure clone');
			throw new AuraHandledException('Error '+ e.getMessage());    
		}
	}

	
	global static void prePopulateValueFromCloneMetadata(SObject thisSobject, Map<String, Event_Clone_Setting__mdt> eventCloneSettings){
		if(eventCloneSettings != null
		&& !eventCloneSettings.isEmpty()){
			for(String thisFieldAPIName : eventCloneSettings.keyset()){
				String fieldType = eventCloneSettings.get(thisFieldAPIName).Fields__r.DataType;
				Object fieldDataTypeToSet = eventCloneSettings.get(thisFieldAPIName).Values__c;

				if(fieldDataTypeToSet != null){
					if(fieldType == 'Checkbox' && fieldDataTypeToSet != null){
						fieldDataTypeToSet = Boolean.valueOf(eventCloneSettings.get(thisFieldAPIName).Values__c);
					} else if(fieldType == 'Number(18, 0)' && fieldDataTypeToSet != null){
						fieldDataTypeToSet = Decimal.valueOf(eventCloneSettings.get(thisFieldAPIName).Values__c);
					} else if(fieldType == 'Date' && fieldDataTypeToSet != null){
						fieldDataTypeToSet = Date.valueOf(eventCloneSettings.get(thisFieldAPIName).Values__c);
					} else if(fieldType == 'Date/Time' && fieldDataTypeToSet != null){
						fieldDataTypeToSet = DateTime.valueOf(eventCloneSettings.get(thisFieldAPIName).Values__c);
					} 
				}
				thisSobject.put(thisFieldAPIName, fieldDataTypeToSet);
			}
		}
	}	
}