force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Consent_Required_to_Register__c.field-meta.xml
<CustomField>
    <fullName>Consent_Required_to_Register__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Consent Required to Register</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Declaration_Text__c.field-meta.xml
<CustomField>
    <fullName>Declaration_Text__c</fullName>
    <label>Declaration Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/GDPR_Statement_Used__c.field-meta.xml
<CustomField>
    <fullName>GDPR_Statement_Used__c</fullName>
    <inlineHelpText>Each university business area has its own consent message / statement. The below consent capture fields will be auto populated further to the values in the custom settings. To change values contact the Salesforce Administrator.</inlineHelpText>
    <label>Consent Statement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consent 1</fullName>
            </value>
            <value>
                <fullName>Consent 2</fullName>
            </value>
            <value>
                <fullName>Alumni &amp; Advancement</fullName>
                <isActive>false</isActive>
                <label>Alumni &amp; Advancement</label>
            </value>
            <value>
                <fullName>Marketing (RAO)</fullName>
                <isActive>false</isActive>
                <label>Marketing (RAO)</label>
            </value>
            <value>
                <fullName>Marketing (Student Recruitment)</fullName>
                <isActive>false</isActive>
                <label>Marketing (Student Recruitment)</label>
            </value>
            <value>
                <fullName>R&amp;I / B2B</fullName>
                <isActive>false</isActive>
                <label>R&amp;I / B2B</label>
            </value>
            <value>
                <fullName>Student Recruitment &amp; RAO</fullName>
                <isActive>false</isActive>
                <label>Student Recruitment &amp; RAO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Statement_Text_above_dec__c.field-meta.xml
<CustomField>
    <fullName>Statement_Text_above_dec__c</fullName>
    <inlineHelpText>This text appears above the declaration options on the web event registration page</inlineHelpText>
    <label>Statement Text (above dec)</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Statement_Text_below_dec__c.field-meta.xml
<CustomField>
    <fullName>Statement_Text_below_dec__c</fullName>
    <inlineHelpText>This text appears below the declaration options on the web event registration page</inlineHelpText>
    <label>Statement Text (below dec)</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Statement_Title__c.field-meta.xml
<CustomField>
    <fullName>Statement_Title__c</fullName>
    <inlineHelpText>The title of the consent statement used on the web registration page</inlineHelpText>
    <label>Statement Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Order__c/Event_Order__c.object-meta.xml
<CustomObject>
    <label>Event Order</label>
    <nameField>
        <displayFormat>O - {00000000}</displayFormat>
        <label>Event Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Order__c/fields/Consent_Given__c.field-meta.xml
<CustomField>
    <fullName>Consent_Given__c</fullName>
    <inlineHelpText>Populated from the event registration</inlineHelpText>
    <label>Consent Given</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Event Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Ticket_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/GDPR_Statement_Used__c.field-meta.xml
<CustomField>
    <fullName>GDPR_Statement_Used__c</fullName>
    <label>GDPR Statement Used - XX</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Event Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/Order_Source__c.field-meta.xml
<CustomField>
    <fullName>Order_Source__c</fullName>
    <label>Order Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Web Order</fullName>
            </value>
            <value>
                <fullName>Internal Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Payment</fullName>
            </value>
            <value>
                <fullName>Waiting List</fullName>
            </value>
            <value>
                <fullName>Waiting List Invitation</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/Receive_SMS_notification__c.field-meta.xml
<CustomField>
    <fullName>Receive_SMS_notification__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Receive  SMS notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/Total_number_of_ticket_requested__c.field-meta.xml
<CustomField>
    <fullName>Total_number_of_ticket_requested__c</fullName>
    <description>This field is used to store number of tickets requested by the person who submitted the waiting list web form</description>
    <inlineHelpText>The number of tickets requested by the person who submitted the waiting list web form</inlineHelpText>
    <label>Total Number of Tickets Requested</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ct_WaitingListController.cls
/**
* @File Name          : ct_WaitingListController.cls
* @Description        : Test class for CT_AddToCalendarController
* @Author             : Creation Admin
* @Last Modified By   : Creation Admin
* @Last Modified On   : 10/12/2020, 12:40:58 PM
* Modifications Log 
* Ver   Date         Author           Modification
* 1.0   09-18-2020   Creation Admin   Initial Version
**/
global without sharing class ct_WaitingListController {
    /*
	* Description: Method to store the Event Order with the status as Waiting List when user submit it from Waiting List form
	* */
    @AuraEnabled
    global static Event_Order__c saveWaitingListEvtOrd(String evtOrderAsJson){
        String response;
        EventOrder evtOrder = (EventOrder) Json.deserialize(evtOrderAsJson, EventOrder.class);
        Event_Order__c eventOrd = new Event_Order__c();
        eventOrd.Event__c                = evtOrder.eventId;
        eventOrd.First_Name__c           = evtOrder.firstName;
        eventOrd.Last_Name__c            = evtOrder.lastName;
        eventOrd.Email__c                = evtOrder.email;
        eventOrd.Receive_SMS_notification__c = evtOrder.receiveSMSnotification != null ? Boolean.valueOf(evtOrder.receiveSMSnotification) : false;
        eventOrd.Mobile__c                   = evtOrder.mobile;
        eventOrd.Total_number_of_ticket_requested__c         = Integer.valueOf(evtOrder.numberOfTicketsRequested);
        eventOrd.Order_Status__c                             = 'Waiting List';
        eventOrd.Order_Source__c                             = ct_EventConstants.ORDER_SOURCE_WEB_ORDER;
        eventOrd.Consent_Given__c                    = evtOrder.consentGiven;
        try{
            insert eventOrd;
        }
        catch(Exception e){
            ct_Logger.logMessage(e, 'Event Order');
            throw e;
        }
        return eventOrd;
        
    }
	 /*
		* Description: Method to fetch the Consent Capture information to show it in the waiting list form
	* */
    @AuraEnabled
    global static Event__c getEventGDPRdetails(String eventId){
        return  [Select Id, GDPR_Statement_Used__c, Statement_Text_above_dec__c, Statement_Text_below_dec__c, Statement_Title__c, Declaration_Text__c,Consent_Required_to_Register__c 
        FROM Event__c WHERE Id =: eventId];
       
    }
    
    global class EventOrder{
        global String firstName;
        global String lastName;
        global String email;
        global String eventId;
        global String receiveSMSnotification;
        global String mobile;
        global String numberOfTicketsRequested;
        global String consentGiven;
        
    }
}