force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <defaultValue>TIMEVALUE(&quot;12:00:00.000&quot;)</defaultValue>
    <description>The time the event is due to finish</description>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_End_Date__c</fullName>
    <label>Event End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Event_Start_Date__c</fullName>
    <label>Event Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Event_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Status__c</fullName>
    <label>Event Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Activation</fullName>
            </value>
            <value>
                <fullName>Pre-Event</fullName>
            </value>
            <value>
                <fullName>Check In / Management</fullName>
            </value>
            <value>
                <fullName>Post Event</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Registration_Status__c</fullName>
    <inlineHelpText>This field will show as ‘Closed’ until all event set up activities have been undertaken &amp; the event status has been moved to ‘Activation’.Once moved to Activation the User can change the status manually to ‘Open’. After this field updates are automatic.</inlineHelpText>
    <label>Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Waiting List</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <defaultValue>TIMEVALUE(&quot;12:00:00.000&quot;)</defaultValue>
    <description>The time the event is due to start</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Web_Event_Location__c.field-meta.xml
<CustomField>
    <fullName>Web_Event_Location__c</fullName>
    <inlineHelpText>Please enter the display location that you wish to show people booking via the Event Registration Page e.g. Launch ED Campus, Virtual Event, Halpern House etc.</inlineHelpText>
    <label>Web Event Location(s)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Web_Event_Name__c.field-meta.xml
<CustomField>
    <fullName>Web_Event_Name__c</fullName>
    <inlineHelpText>Please enter the display name that you wish to show people booking via the Event Registration page</inlineHelpText>
    <label>Web Event Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Order__c/Event_Order__c.object-meta.xml
<CustomObject>
    <label>Event Order</label>
    <nameField>
        <displayFormat>O - {00000000}</displayFormat>
        <label>Event Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Order__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Ticket_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Order__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <label>Event Registration</label>
    <nameField>
        <displayFormat>REG-{0000000}</displayFormat>
        <label>Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipName>Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Event_Email__c.field-meta.xml
<CustomField>
    <fullName>Event_Email__c</fullName>
    <label>Event Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Event_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Event_Mobile__c</fullName>
    <description>This field is used to store event attendee mobile number</description>
    <inlineHelpText>This field will be populated using ticket management web form</inlineHelpText>
    <label>Event Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Event_Registration_Status__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration_Status__c</fullName>
    <description>Event Registration Status</description>
    <inlineHelpText>Event Registration Status</inlineHelpText>
    <label>Event Registration Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Invited</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
                <default>true</default>
                <label>Registered</label>
            </value>
            <value>
                <fullName>Attended / Checked In</fullName>
            </value>
            <value>
                <fullName>Attended / Checked Out</fullName>
            </value>
            <value>
                <fullName>Did Not Attend</fullName>
            </value>
            <value>
                <fullName>Declined</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <description>Formula Field For combining First name and Last Name to be used in SOQL Query</description>
    <formula>First_Name__c + &quot; &quot; +  Last_Name__c</formula>
    <inlineHelpText>Event Registration Name</inlineHelpText>
    <label>Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Registration_Type__c</fullName>
    <label>Registration Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Complementary - Speaker</fullName>
            </value>
            <value>
                <fullName>Complementary - Vendor</fullName>
            </value>
            <value>
                <fullName>Complementary - Prospect</fullName>
            </value>
            <value>
                <fullName>Complementary - Media</fullName>
            </value>
            <value>
                <fullName>Myself</fullName>
            </value>
            <value>
                <fullName>Someone Else</fullName>
            </value>
            <value>
                <fullName>Unknown Guest</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Primary Session the individual is interested in attending</description>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Event Registrations</relationshipLabel>
    <relationshipName>Event_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description>The end time of a session</description>
    <label>Session End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <description>This associates a Session to an Event</description>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_End_Date__c</fullName>
    <description>This field is used to record the session end date</description>
    <inlineHelpText>Please choose an appropriate end date for this session</inlineHelpText>
    <label>Session End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_Start_Date__c</fullName>
    <description>Session Start Date</description>
    <inlineHelpText>Session Start Date</inlineHelpText>
    <label>Session Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>The start time of a session</description>
    <label>Session Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/Session_Registration__c.object-meta.xml
<CustomObject>
    <label>Session Registration</label>
    <nameField>
        <displayFormat>SAR - {00000}</displayFormat>
        <label>Session Registration Reference</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Registrations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Registration__c/fields/Event_Registration__c.field-meta.xml
<CustomField>
    <fullName>Event_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Event Registration</label>
    <referenceTo>Event_Registration__c</referenceTo>
    <relationshipName>Session_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <formula>Event_Registration__r.First_Name__c</formula>
    <label>First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <formula>Event_Registration__r.Last_Name__c</formula>
    <label>Last Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/fields/Registration_Type__c.field-meta.xml
<CustomField>
    <fullName>Registration_Type__c</fullName>
    <formula>TEXT(Event_Registration__r.Registration_Type__c)</formula>
    <label>Registration Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipName>Session_Registrations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Waiting List</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
            <value>
                <fullName>Attended / Checked In</fullName>
            </value>
            <value>
                <fullName>Attended / Checked Out</fullName>
            </value>
            <value>
                <fullName>Did Not Attend</fullName>
                <color>#A845DC</color>
                <label>Did Not Attend</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <color>#E27001</color>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Attending</fullName>
                <isActive>false</isActive>
                <label>Attending</label>
            </value>
            <value>
                <fullName>Checked In</fullName>
                <isActive>false</isActive>
                <label>Checked In</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ct_CheckInManagerController.cls
/**
 * @description       : Using this class to implemented the Check In Manager functionality
 * @author            : Creation Admin
 * @last modified on  : 01-08-2021
 * @last modified by  : Creation Admin
 * Modifications Log 
 * Ver   Date         Author           Modification
 * 1.0   08-31-2020   Creation Admin   Initial Version
**/
global without sharing class ct_CheckInManagerController {

	global static Map<String, String> checkInStatusMap = new Map<String, String>{
		ct_EventConstants.EVENT_REGISTRATION_REGISTERED 			=> ct_EventConstants.EVENT_CHECK_IN_STATUS_REGISTERED, 
		ct_EventConstants.EVENT_REGISTRATION_CHECKED_IN  		  => ct_EventConstants.EVENT_CHECK_IN_STATUS_CHECKED_IN,
		ct_EventConstants.EVENT_REGISTRATION_CHECKED_OUT  		=> ct_EventConstants.EVENT_CHECK_IN_STATUS_CHECKED_OUT,
		ct_EventConstants.EVENT_REGISTRATION_DID_NOT_ATTEND   => ct_EventConstants.EVENT_CHECK_IN_STATUS_DID_NOT_ATTEND};
		
	global static Set<String> checkInStatusKeySet = checkInStatusMap.keySet();

	global static Map<String, String> sessionRegCheckInStatusMap = new Map<String, String>{
		ct_EventConstants.SESSION_REGISTRATION_REGISTERED 			=> ct_EventConstants.EVENT_CHECK_IN_STATUS_REGISTERED, 
		ct_EventConstants.SESSION_REGISTRATION_CHECKED_IN  		  => ct_EventConstants.EVENT_CHECK_IN_STATUS_CHECKED_IN,
		ct_EventConstants.SESSION_REGISTRATION_CHECKED_OUT  		=> ct_EventConstants.EVENT_CHECK_IN_STATUS_CHECKED_OUT,
		ct_EventConstants.SESSION_REGISTRATION_DID_NOT_ATTEND   => ct_EventConstants.EVENT_CHECK_IN_STATUS_DID_NOT_ATTEND};

	global static Set<String> sessionRegCheckInStatusKeySet = sessionRegCheckInStatusMap.keySet();

	@AuraEnabled
  global static initialWrapper getInitialWrapper(){	
		try{
			initialWrapper thisInitialWrapper 										= new initialWrapper();
			thisInitialWrapper.eventOptions   										= getEventOptions();
			thisInitialWrapper.sessionOptions 										= getSessionOptions();
			return thisInitialWrapper;
		}
		catch(Exception e){
			//Exception mechanism to log any exceptions occured during the dml operation
			ct_Logger.logMessage(e, 'Event Registration Check In Manager');
			throw new AuraHandledException('Error '+ e.getMessage());    
		}
	}
	
	global static List<PicklistEntryWrapper> getEventOptions(){
		List<PicklistEntryWrapper> thisEventOptions = new List<PicklistEntryWrapper>();
		thisEventOptions.add(new PicklistEntryWrapper('NONE', ''));
		for(Event__c thisEvent : [SELECT Id, Name, Web_Event_Name__c, Web_Event_Location__c, Event_Start_Date__c, Event_Status__c,
															Event_End_Date__c, Registration_Status__c
															FROM Event__c
															WHERE Event_Status__c =:ct_EventConstants.EVENT_STATUS_CHECK_IN_MANAGEMENT
															ORDER BY Name]){
			thisEventOptions.add(new PicklistEntryWrapper(thisEvent.Name, thisEvent.Id));
		}
		return thisEventOptions;
	}
    
	global static Map<String, List<PicklistEntryWrapper>>  getSessionOptions(){
		String timesStamp;
		Map<String, List<PicklistEntryWrapper>>  thisSessionOptions = new Map<String, List<PicklistEntryWrapper>> ();
		for(Session__c thisSession : [SELECT Id, Event__c, Name, Event__r.Event_Status__c, Start_Time__c,End_Time__c, Session_End_Date__c,Session_Start_Date__c
																		FROM Session__c 
																		WHERE Event__c != null
																		AND Event__r.Event_Status__c =:ct_EventConstants.EVENT_STATUS_CHECK_IN_MANAGEMENT
																		ORDER BY Name]){
			if(!thisSessionOptions.containsKey(String.valueOf(thisSession.Event__c))){
				thisSessionOptions.put(String.valueOf(thisSession.Event__c), new List<PicklistEntryWrapper>());
			}

			if(thisSession.Session_Start_Date__c != null && thisSession.Start_Time__c != null){
				timesStamp = ' ('+DateTime.newInstance(thisSession.Session_Start_Date__c, thisSession.Start_Time__c).format('HH:mm');
				if(thisSession.Session_End_Date__c != null && thisSession.End_Time__c != null){
					timesStamp = timesStamp + +' - ' + DateTime.newInstance(thisSession.Session_End_Date__c, thisSession.End_Time__c).format('HH:mm') + ' )';
				}
				else {
					timesStamp = timesStamp + ' )';
				}
			}
			thisSessionOptions.get(String.valueOf(thisSession.Event__c)).add(new PicklistEntryWrapper(thisSession.Name + timesStamp, thisSession.Id));
		}
		return thisSessionOptions;
	}

	@AuraEnabled
	global static Map<String, Integer> getDashBoardAggregrate(String eventId, String sessionId, Boolean isMainEntrance){
		if(isMainEntrance){
			return getEventRegistrationAggregrate(eventId);
		}
		else{
			return getSessionRegistrationAggregrate(eventId, sessionId);
		}
	}

	@AuraEnabled
	global static Map<String, Integer> getEventRegistrationAggregrate(String eventId){

		String queryString = 'SELECT COUNT(ID) numberOfEventReg, Event_Registration_Status__c eventStatus FROM Event_Registration__c WHERE Event_Registration_Status__c != null AND Event_Registration_Status__c IN :checkInStatusKeySet';

		if(!String.isEmpty(eventId)){
			queryString = queryString +' AND Event__c =: eventId AND Event__r.Event_Status__c = '+'\''+ct_EventConstants.EVENT_STATUS_CHECK_IN_MANAGEMENT+'\'';
		}

		queryString = queryString + ' GROUP BY Event_Registration_Status__c';
		Map<String, Integer> eventRegistrationAggregrate = new Map<String, Integer>();
	  for (AggregateResult thisAggregateResult : Database.query(queryString)) {

			eventRegistrationAggregrate.put(checkInStatusMap.get(String.valueOf(thisAggregateResult.get('eventStatus'))), (Integer) thisAggregateResult.get('numberOfEventReg'));								
		}
		return eventRegistrationAggregrate;
	}

	@AuraEnabled
	global static Map<String, Integer> getSessionRegistrationAggregrate(String eventId, String sessionId){

		String queryString = 'SELECT COUNT(ID) numberOfSessionReg, Status__c sessionRegStatus FROM Session_Registration__c WHERE Status__c != null AND Status__c IN :checkInStatusKeySet';

		if(!String.isEmpty(eventId)){
			queryString = queryString +' AND Event_Registration__r.Event__c =: eventId AND Event_Registration__r.Event__r.Event_Status__c = '+'\''+ct_EventConstants.EVENT_STATUS_CHECK_IN_MANAGEMENT+'\'';
		}

		if(!String.isEmpty(sessionId)){
			queryString = queryString +' AND Session__c = :sessionId';
		}

		queryString = queryString + ' GROUP BY Status__c';
		Map<String, Integer> get = new Map<String, Integer>();
	  for (AggregateResult thisAggregateResult : Database.query(queryString)) {

			get.put(sessionRegCheckInStatusMap.get(String.valueOf(thisAggregateResult.get('sessionRegStatus'))), (Integer) thisAggregateResult.get('numberOfSessionReg'));								
		}
		return get;
	}

	@AuraEnabled
	global static List<SObject> getRegistrationRecords(String nameFilter, String orderRefNumber, String ticketRefNumber, String eventRegEmail, String eventId, String sessionId, Boolean isMainEntrance, String mobilenumber){
		if(isMainEntrance){
			return getEventRegistrations(nameFilter, orderRefNumber, ticketRefNumber, eventRegEmail, eventId, mobilenumber); 
		}
		else{
			return getSessionRegistrations(nameFilter, orderRefNumber, ticketRefNumber, eventRegEmail, eventId, sessionId, mobilenumber);
		}
	}

	@AuraEnabled
	global static List<Event_Registration__c> getEventRegistrations(String nameFilter, String orderRefNumber, String ticketRefNumber, String eventRegEmail, String eventId, String mobilenumber){
		Boolean hasNameFilter;
		Boolean hasOrderRefNumberFilter;
		Boolean hasTicketRefFilter;
		Boolean hasEventRegEmailFilter;
		Boolean hasEventIdFilter;
		Boolean hasMobileNumberFilter;

		hasNameFilter           = String.isEmpty(nameFilter) ? false : true;
		hasOrderRefNumberFilter = String.isEmpty(orderRefNumber) ? false : true;
		hasTicketRefFilter      = String.isEmpty(ticketRefNumber) ? false : true;
		hasEventRegEmailFilter  = String.isEmpty(eventRegEmail) ? false : true;
		hasEventIdFilter        = String.isEmpty(eventId) ? false : true;
		hasMobileNumberFilter   = String.isEmpty(mobilenumber) ? false : true;

		String queryString = 'SELECT Id, Name,Registration_Type__c, Event_Registration_Status__c, Name__c, Event__c, Session__c, Event_Email__c, Event_Mobile__c, First_Name__c, Last_Name__c, Event_Order__r.Name FROM Event_Registration__c WHERE Name != null AND Event_Registration_Status__c IN :checkInStatusKeySet';
		
		if(hasNameFilter || hasOrderRefNumberFilter || hasTicketRefFilter || hasEventRegEmailFilter ||  hasEventIdFilter || hasMobileNumberFilter){
			queryString = queryString +' AND';
		}

		if(hasNameFilter){
			nameFilter 			= '%' + nameFilter + '%';
			queryString = queryString + ' Name__c LIKE :nameFilter';
			if(hasOrderRefNumberFilter || hasTicketRefFilter || hasEventRegEmailFilter ||  hasEventIdFilter || hasMobileNumberFilter){
				queryString = queryString +' AND';
			}
		}

		if(hasOrderRefNumberFilter){
			orderRefNumber 	= '%' + orderRefNumber + '%';
			queryString = queryString +' Event_Order__r.Name LIKE :orderRefNumber';
			if(hasTicketRefFilter || hasEventRegEmailFilter ||  hasEventIdFilter || hasMobileNumberFilter){
				queryString = queryString +' AND';
			}
		}

		if(hasTicketRefFilter){
			ticketRefNumber 	= '%' + ticketRefNumber + '%';
			queryString = queryString +' Name LIKE :ticketRefNumber';
			if(hasEventRegEmailFilter ||  hasEventIdFilter || hasMobileNumberFilter){
				queryString = queryString +' AND';
			}
		}

		if(hasEventRegEmailFilter){
			eventRegEmail 	= '%' + eventRegEmail + '%';
			queryString = queryString +' Event_Email__c LIKE :eventRegEmail';
			if(hasEventIdFilter || hasMobileNumberFilter){
				queryString = queryString +' AND';
			}
		}

		if(hasMobileNumberFilter){
			mobilenumber 	= '%' + mobilenumber + '%';
			queryString = queryString +' Event_Mobile__c LIKE :mobilenumber';

			if(hasEventIdFilter){
				queryString = queryString +' AND';
			}
		}

		if(hasEventIdFilter){
			queryString = queryString +' Event__c =: eventId AND Event__r.Event_Status__c ='+'\''+ct_EventConstants.EVENT_STATUS_CHECK_IN_MANAGEMENT+'\'';
		}	

		queryString = queryString +' ORDER BY Last_Name__c ASC NULLS LAST';

		return Database.query(queryString);
	}

	@AuraEnabled
	global static List<Session_Registration__c> getSessionRegistrations(String nameFilter, String orderRefNumber, String ticketRefNumber, String eventRegEmail, String eventId, String sessionId, String mobilenumber){
		Boolean hasNameFilter;
		Boolean hasOrderRefNumberFilter;
		Boolean hasTicketRefFilter;
		Boolean hasEventRegEmailFilter;
		Boolean hasEventIdFilter;
		Boolean hasSessionIdFilter;
		Boolean hasMobileNumberFilter;
		

		hasNameFilter 					= String.isEmpty(nameFilter) ? false : true;
		hasOrderRefNumberFilter = String.isEmpty(orderRefNumber) ? false : true;
		hasTicketRefFilter 			= String.isEmpty(ticketRefNumber) ? false : true;
		hasEventRegEmailFilter 	= String.isEmpty(eventRegEmail) ? false : true;
		hasEventIdFilter 				= String.isEmpty(eventId) ? false : true;
		hasSessionIdFilter 			= String.isEmpty(sessionId) ? false : true;
		hasMobileNumberFilter   = String.isEmpty(mobilenumber) ? false : true;


		String queryString = 'SELECT Id, Event_Registration__c,Event_Registration__r.Name,  Event_Registration__r.Last_Name__c, Event_Registration__r.Registration_Type__c, Status__c, Event_Registration__r.Name__c, Event_Registration__r.Event__c, Session__c, Event_Registration__r.Event_Email__c, Event_Registration__r.Event_Registration_Status__c, Event_Registration__r.Event_Order__r.Name FROM Session_Registration__c WHERE Name != null AND Status__c IN :sessionRegCheckInStatusKeySet';
		
		if(hasNameFilter || hasOrderRefNumberFilter || hasTicketRefFilter || hasEventRegEmailFilter ||  hasEventIdFilter || hasSessionIdFilter || hasMobileNumberFilter){
			queryString = queryString +' AND';
		}

		if(hasNameFilter){
			nameFilter 			= '%' + nameFilter + '%';
			queryString = queryString + ' Event_Registration__r.Name__c LIKE :nameFilter';
			if(hasOrderRefNumberFilter || hasTicketRefFilter || hasEventRegEmailFilter ||  hasEventIdFilter || hasSessionIdFilter || hasMobileNumberFilter){
				queryString = queryString +' AND';
			}
		}

		if(hasOrderRefNumberFilter){
			orderRefNumber 	= '%' + orderRefNumber + '%';
			queryString = queryString +' Event_Registration__r.Event_Order__r.Name LIKE :orderRefNumber';
			if(hasTicketRefFilter || hasEventRegEmailFilter ||  hasEventIdFilter || hasSessionIdFilter || hasMobileNumberFilter){
				queryString = queryString +' AND';
			}
		}

		if(hasTicketRefFilter){
			ticketRefNumber 	= '%' + ticketRefNumber + '%';
			queryString = queryString +' Event_Registration__r.Name LIKE :ticketRefNumber';
			if(hasEventRegEmailFilter ||  hasEventIdFilter || hasSessionIdFilter || hasMobileNumberFilter){
				queryString = queryString +' AND';
			}
		}

		if(hasEventRegEmailFilter){
			eventRegEmail 	= '%' + eventRegEmail + '%';
			queryString = queryString +' Event_Registration__r.Event_Email__c LIKE :eventRegEmail';
			if(hasEventIdFilter || hasSessionIdFilter || hasMobileNumberFilter){
				queryString = queryString +' AND';
			}
		}

		if(hasEventIdFilter){
			queryString = queryString +' Event_Registration__r.Event__c =: eventId AND Event_Registration__r.Event__r.Event_Status__c ='+'\''+ct_EventConstants.EVENT_STATUS_CHECK_IN_MANAGEMENT+'\'';
			if(hasSessionIdFilter){
				queryString = queryString +' AND';
			}
		}

		if(hasMobileNumberFilter){
			mobilenumber 	= '%' + mobilenumber + '%';
			queryString = queryString +' Event_Registration__r.Event_Mobile__c LIKE :mobilenumber';

			if(hasSessionIdFilter){
				queryString = queryString +' AND';
			}
		}

		if(hasSessionIdFilter){
			queryString = queryString +' Session__c = :sessionId';
		}

		queryString = queryString +' ORDER BY Event_Registration__r.Last_Name__c ASC NULLS LAST';

		
		return Database.query(queryString);
	}

	@AuraEnabled
	global static void updateEventRegistrationStatus(String eventRegId, String checkInStatus){
		Map<String, String> checkInStatusMap = new Map<String, String>{
																																		ct_EventConstants.EVENT_CHECK_IN_STATUS_REGISTERED => ct_EventConstants.EVENT_REGISTRATION_REGISTERED,
																																		ct_EventConstants.EVENT_CHECK_IN_STATUS_CHECKED_IN => ct_EventConstants.EVENT_REGISTRATION_CHECKED_IN,
																																		ct_EventConstants.EVENT_CHECK_IN_STATUS_CHECKED_OUT => ct_EventConstants.EVENT_REGISTRATION_CHECKED_OUT,
																																		ct_EventConstants.EVENT_CHECK_IN_STATUS_DID_NOT_ATTEND => ct_EventConstants.EVENT_REGISTRATION_DID_NOT_ATTEND};
		try{
			if(checkInStatusMap.containsKey(checkInStatus)){
				Event_Registration__c thisEventRegistrationToUpdate = [SELECT Id, Event_Registration_Status__c FROM Event_Registration__c
																															WHERE Id =: eventRegId LIMIT 1];
				thisEventRegistrationToUpdate.Event_Registration_Status__c = checkInStatusMap.get(checkInStatus);
				update thisEventRegistrationToUpdate;
			}
		}
		catch(Exception e){
			//Exception mechanism to log any exceptions occured during the dml operation
			ct_Logger.logMessage(e, 'Event Registration Check In Manager');
			throw new AuraHandledException('Error '+ e.getMessage());    
		}
	}

	@AuraEnabled
	global static void updateSessionRegistrationStatus(String sessRegId, String checkInStatus){
		Map<String, String> checkInStatusMap = new Map<String, String>{
																								ct_EventConstants.EVENT_CHECK_IN_STATUS_REGISTERED => ct_EventConstants.SESSION_REGISTRATION_REGISTERED,
																								ct_EventConstants.EVENT_CHECK_IN_STATUS_CHECKED_IN => ct_EventConstants.SESSION_REGISTRATION_CHECKED_IN,
																								ct_EventConstants.EVENT_CHECK_IN_STATUS_CHECKED_OUT => ct_EventConstants.SESSION_REGISTRATION_CHECKED_OUT,
																								ct_EventConstants.EVENT_CHECK_IN_STATUS_DID_NOT_ATTEND => ct_EventConstants.SESSION_REGISTRATION_DID_NOT_ATTEND};
		try{
			if(checkInStatusMap.containsKey(checkInStatus)){
				Session_Registration__c thisSessionRegistrationToUpdate = [SELECT Id, Status__c, Event_Registration__c, Event_Registration__r.Event_Registration_Status__c FROM Session_Registration__c
																															WHERE Id =: sessRegId LIMIT 1];

				if(thisSessionRegistrationToUpdate.Event_Registration__c != null
				&& thisSessionRegistrationToUpdate.Event_Registration__r.Event_Registration_Status__c != null
				&& thisSessionRegistrationToUpdate.Event_Registration__r.Event_Registration_Status__c != ct_EventConstants.EVENT_REGISTRATION_CHECKED_IN){

					Event_Registration__c thisEventRegistrationToUpdate = [SELECT Id, Event_Registration_Status__c FROM Event_Registration__c
																															WHERE Id =: thisSessionRegistrationToUpdate.Event_Registration__c LIMIT 1];
					thisEventRegistrationToUpdate.Event_Registration_Status__c = ct_EventConstants.EVENT_REGISTRATION_CHECKED_IN;
					update thisEventRegistrationToUpdate;
				}

				thisSessionRegistrationToUpdate.Status__c = checkInStatusMap.get(checkInStatus);
				update thisSessionRegistrationToUpdate;
			}
		}
		catch(Exception e){
			//Exception mechanism to log any exceptions occured during the dml operation
			ct_Logger.logMessage(e, 'Session Registration Check In Manager');
			throw new AuraHandledException('Error '+ e.getMessage());    
		}
	}
	
	@AuraEnabled
	global static List<Session_Registration__c> getSessionRegistrationRecords(String eventId, String sessionId, Boolean isMainEntrance){
		List<Session_Registration__c> sessionRegistrationRecords = new 	List<Session_Registration__c>();

		String queryString = 'SELECT Id, Name, Event_Registration__c,Event_Registration__r.Name, Event_Registration__r.Event_Registration_Status__c,First_Name__c, Last_Name__c, Event_Registration__r.Event_Email__c,Event_Registration__r.Event_Mobile__c,Event_Registration__r.Registration_Type__c,Session__c,Status__c FROM Session_Registration__c	WHERE Event_Registration__r.Event__c =:eventId';
		if(!isMainEntrance){
			queryString = queryString + ' AND Session__c =:sessionId';
		}
		
		for(Session_Registration__c thisSessionRegisration : Database.query(queryString)){
			sessionRegistrationRecords.add(thisSessionRegisration);
		}
		return sessionRegistrationRecords;
	}

	global class initialWrapper{
		@AuraEnabled
		global List<PicklistEntryWrapper> eventOptions                	{get;set;}
		@AuraEnabled
		global Map<String, List<PicklistEntryWrapper>> sessionOptions		{get;set;}
		@AuraEnabled
		global Map<String, Integer> eventRegistrationAggregrateResult 	{get;set;}
	}

	/**
	* Wrapper that contains Picklist Values
	*/
  global class PicklistEntryWrapper{
    //get set string to store lable of picklist entry
    @AuraEnabled
    global String label                  {get;set;}
    //get set string to store value of picklist entry
    @AuraEnabled
    global string value                  {get;set;}
    
    global PicklistEntryWrapper(String entryLabel,String entryValue){
      this.label    = entryLabel;
      this.value    = entryValue;
		}
	}

}